// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"strings"
)

func (v *Validator) Validate() error {
	v.F1 = strings.ToLower(v.F1)
	if v.F2 != nil {
		*v.F2 = strings.ToLower(*v.F2)
	}
	return nil
}
