// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.VAT(v.F1, "us") {
		return errors.New("F1 must be a valid VAT number")
	}
	if v.F2 != nil && !valid.VAT(*v.F2, "us") {
		return errors.New("F2 must be a valid VAT number")
	}
	if !valid.VAT(v.F3, "gb") {
		return errors.New("F3 must be a valid VAT number")
	}
	if v.F4 != nil && !valid.VAT(*v.F4, "ru") {
		return errors.New("F4 must be a valid VAT number")
	}
	return nil
}
