// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.ISO31661A(v.F1, 0) {
		return errors.New("F1 must be a valid ISO 3166-1 Alpha value")
	}
	if v.F2 != nil && !valid.ISO31661A(*v.F2, 0) {
		return errors.New("F2 must be a valid ISO 3166-1 Alpha value")
	}
	if !valid.ISO31661A(v.F3, 2) {
		return errors.New("F3 must be a valid ISO 3166-1 Alpha value")
	}
	if v.F4 != nil && !valid.ISO31661A(*v.F4, 3) {
		return errors.New("F4 must be a valid ISO 3166-1 Alpha value")
	}
	return nil
}
