// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.Digits(v.F1) {
		return errors.New("F1 must contain only digits")
	}
	if v.F2 != nil && !valid.Digits(*v.F2) {
		return errors.New("F2 must contain only digits")
	}
	return nil
}
