// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if v.F1 != nil && !valid.Email(*v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if v.F2 != nil && len(v.F2) != 5 {
		return errors.New("F2 must be of length: 5")
	}
	return nil
}
