// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.Octal(v.F1) {
		return errors.New("F1 string content must match an octal number")
	}
	if v.F2 != nil && !valid.Octal(*v.F2) {
		return errors.New("F2 string content must match an octal number")
	}
	return nil
}
