// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.Alpha(v.F1, "en") {
		return errors.New("F1 must be an alphabetic string")
	}
	if v.F2 != nil && !valid.Alpha(*v.F2, "ja") {
		return errors.New("F2 must be an alphabetic string")
	}
	return nil
}
