// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.Base64(v.F1, false) {
		return errors.New("F1 must be a valid base64 string")
	}
	if v.F2 != nil && !valid.Base64(*v.F2, false) {
		return errors.New("F2 must be a valid base64 string")
	}
	if !valid.Base64(v.F3, true) {
		return errors.New("F3 must be a valid base64 string")
	}
	if v.F4 != nil && !valid.Base64(*v.F4, true) {
		return errors.New("F4 must be a valid base64 string")
	}
	return nil
}
