// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"strings"
)

func (v Validator) Validate() error {
	v.F1 = strings.TrimLeft(v.F1, "abc")
	if v.F2 != nil {
		*v.F2 = strings.TrimLeft(*v.F2, "xyz")
	}
	return nil
}
