// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.IPRange(v.F1) {
		return errors.New("F1 must be a valid IP range")
	}
	if v.F2 != nil && !valid.IPRange(*v.F2) {
		return errors.New("F2 must be a valid IP range")
	}
	return nil
}
