// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.Bool(v.F1) {
		return errors.New("F1 string content must match a boolean value")
	}
	if v.F2 != nil && !valid.Bool(*v.F2) {
		return errors.New("F2 string content must match a boolean value")
	}
	return nil
}
