// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"math"
	"strconv"
	"strings"
)

func (v T01Validator) Validate() error {
	v.F1 = strings.TrimSpace(v.F1)
	v.F2 = strings.Repeat(v.F2, 2)
	if v.F3 != nil {
		*v.F3 = strings.Repeat(strings.TrimSpace(*v.F3), 1)
	}
	v.F4 = strings.Replace(v.F4, "a", "b", 3)
	v.F5 = strings.Replace(v.F5, "foo", "bar", -1)
	v.F6 = strconv.Quote(strings.ToTitle(strings.TrimSpace(v.F6)))
	if v.F7 != nil && *v.F7 != nil {
		**v.F7 = math.Round(**v.F7)
	}
	return nil
}
