// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"strings"
)

func (v T02Validator) Validate() error {
	v.F1 = strings.TrimSpace(v.F1)
	if v.F2 != nil && *v.F2 != nil && **v.F2 != nil {
		***v.F2 = strings.TrimSpace(***v.F2)
	}
	if v.S1 != nil {
		if v.S1.S2.S3 != nil && *v.S1.S2.S3 != nil && **v.S1.S2.S3 != nil {
			f := ***v.S1.S2.S3
			if f.F != nil && *f.F != nil {
				**f.F = strings.TrimSpace(**f.F)
			}
		}
	}
	return nil
}
