// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
	"strings"

	"github.com/frk/valid"
)

func (v T05Validator) Validate() error {
	for i, e := range v.F1 {
		v.F1[i] = strings.TrimSpace(e)
	}
	for i, e := range v.F2 {
		v.F2[i] = strings.TrimSpace(e)
		e = v.F2[i]
		if !valid.Email(e) {
			return errors.New("F2 must be a valid email address")
		}
	}
	for _, e := range v.F3 {
		for _, e2 := range e {
			if e2 != nil {
				*e2 = strings.TrimSpace(*e2)
			}
		}
	}
	if len(v.F4) > 10 {
		return errors.New("F4 must be of length at most: 10")
	} else {
		for _, e := range v.F4 {
			if len(e) < 3 || len(e) > 5 {
				return errors.New("F4 must be of length between: 3 and 5 (inclusive)")
			} else {
				for _, e2 := range e {
					if len(e2) < 4 {
						return errors.New("F4 must be of length at least: 4")
					} else {
						for _, e := range e2 {
							if e != nil {
								*e = strings.TrimSpace(*e)
								if !valid.Email(*e) {
									return errors.New("F4 must be a valid email address")
								}
							}
						}
					}
				}
			}
		}
	}
	return nil
}
