// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
	"strings"

	"github.com/frk/valid"
)

func (v T06Validator) Validate() error {
	for k, e := range v.F1 {
		v.F1[k] = strings.TrimSpace(e)
	}
	for k, e := range v.F2 {
		v.F2[k] = strings.TrimSpace(e)
		e = v.F2[k]
		if !valid.Email(e) {
			return errors.New("F2 must be a valid email address")
		}
	}
	for _, e := range v.F3 {
		for _, e2 := range e {
			if e2 != nil {
				*e2 = strings.TrimSpace(*e2)
			}
		}
	}
	for _, e := range v.F4 {
		if len(e) < 4 {
			return errors.New("F4 must be of length at least: 4")
		} else {
			for k, e2 := range e {
				e[k] = strings.TrimSpace(e2)
				e2 = e[k]
				if !valid.Email(e2) {
					return errors.New("F4 must be a valid email address")
				}
			}
		}
	}
	return nil
}
