// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"strings"

	"github.com/frk/valid/cmd/internal/generator/testdata/mypkg"
)

func (v T07Validator) Validate() error {
	v.F1 = mypkg.PreWithOpt(v.F1, nil)
	if v.F2 != nil {
		*v.F2 = mypkg.PreWithOpt(strings.TrimSpace(*v.F2), nil)
	}
	v.F3 = strings.TrimSpace(mypkg.PreWithOpt(v.F3, nil))
	if v.F4 != nil {
		*v.F4 = strings.TrimSpace(mypkg.PreWithOpt(*v.F4, nil))
	}
	v.G1 = mypkg.PreWithOpt2(v.G1, "")
	if v.G2 != nil {
		*v.G2 = mypkg.PreWithOpt2(strings.TrimSpace(*v.G2), "")
	}
	v.G3 = strings.TrimSpace(mypkg.PreWithOpt2(v.G3, ""))
	if v.G4 != nil {
		*v.G4 = strings.TrimSpace(mypkg.PreWithOpt2(*v.G4, ""))
	}
	return nil
}
