// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v AlnumValidator) Validate() error {
	if !isvalid.Alnum(v.F1, "en") {
		return errors.New("F1 must be an alphanumeric string")
	}
	if v.F2 != nil && *v.F2 != nil && !isvalid.Alnum(**v.F2, "en") {
		return errors.New("F2 must be an alphanumeric string")
	}
	if v.F3 == nil || *v.F3 == nil || len(**v.F3) == 0 {
		return errors.New("F3 is required")
	} else if !isvalid.Alnum(**v.F3, "sk") {
		return errors.New("F3 must be an alphanumeric string")
	}
	if !isvalid.Alpha(v.F4, "en") {
		return errors.New("F4 must be an alphabetic string")
	}
	if v.F5 != nil && *v.F5 != nil && !isvalid.Alpha(**v.F5, "en") {
		return errors.New("F5 must be an alphabetic string")
	}
	if v.F6 == nil || *v.F6 == nil || len(**v.F6) == 0 {
		return errors.New("F6 is required")
	} else if !isvalid.Alpha(**v.F6, "cs") {
		return errors.New("F6 must be an alphabetic string")
	}
	return nil
}
