// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v ContextOptionValidator) Validate() error {
	if v.context == "new" && len(v.F1) == 0 {
		return errors.New("F1 is required")
	}
	if v.F2 != nil && (v.context == "update" && len(*v.F2) > 21) {
		return errors.New("F2 must be of length at most: 21")
	}
	return nil
}
