// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v ContextOption1Validator) Validate() error {
	if v.context == "new" {
		if len(v.F1) == 0 {
			return errors.New("F1 is required")
		}
		if v.F3 != nil && *v.F3 >= 8 {
			return errors.New("F3 must be less than: 8")
		}
	}
	if v.context == "update" {
		if v.F2 != nil && len(*v.F2) > 21 {
			return errors.New("F2 must be of length at most: 21")
		}
	}
	return nil
}
