// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid/internal/testdata/mypkg"
)

func (v CustomValidator) Validate() error {
	if !mypkg.MyRule(v.F1) {
		return errors.New("F1 is not valid")
	}
	if v.F2 != nil {
		f := *v.F2
		if !mypkg.MyRule2(f) {
			return errors.New("F2 is not valid")
		}
	}
	if v.F3 != nil && *v.F3 != nil {
		f := **v.F3
		if !mypkg.MyRule2(f, "foo", "bar", "baz") {
			return errors.New("F3 is not valid")
		}
	}
	if !mypkg.MyRule3(v.F4, 123, 32.54, "foo", true) {
		return errors.New("F4 is not valid")
	}
	return nil
}
