// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

func (v ErrorAggregatorValidator) Validate() error {
	if len(v.F1) == 0 {
		v.ea.Error("F1", v.F1, "required")
	} else if v.F1 != "foo" {
		v.ea.Error("F1", v.F1, "eq", "foo")
	}
	return v.ea.Out()
}
