// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v HooksValidator) Validate() error {
	if err := v.beforevalidate(); err != nil {
		return err
	}
	if len(v.F1) == 0 {
		return errors.New("F1 is required")
	}
	if err := v.AfterValidate(); err != nil {
		return err
	}
	return nil
}

func (v Hooks2Validator) Validate() error {
	if err := v.beforevalidate(); err != nil {
		return err
	}
	if len(v.F1) == 0 {
		v.ea.Error("F1", v.F1, "required")
	}
	if err := v.AfterValidate(); err != nil {
		return err
	}
	return v.ea.Out()
}
