// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v IsValiderValidator) Validate() error {
	if len(v.F1) == 0 {
		return errors.New("F1 is required")
	} else if !v.F1.IsValid() {
		return errors.New("F1 is not valid")
	}
	if v.F2 != nil && *v.F2 != nil && **v.F2 != nil && !(***v.F2).IsValid() {
		return errors.New("F2 is not valid")
	}
	if v.F3 != nil && !(*v.F3).IsValid() {
		return errors.New("F3 is not valid")
	}
	return nil
}
