// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v NotnilValidator) Validate() error {
	if v.F1 == nil {
		return errors.New("F1 cannot be nil")
	}
	if v.F2 == nil || *v.F2 == nil {
		return errors.New("F2 cannot be nil")
	}
	if v.F3 == nil || *v.F3 == nil {
		return errors.New("F3 cannot be nil")
	}
	if v.F4 == nil || *v.F4 == nil {
		return errors.New("F4 cannot be nil")
	}
	if v.F5 == nil {
		return errors.New("F5 cannot be nil")
	}
	if v.G1 != nil {
		f := *v.G1
		if f.F1 == nil {
			return errors.New("G1.F1 cannot be nil")
		}
		if f.G2 == nil {
			return errors.New("G1.G2 cannot be nil")
		} else {
			f := *f.G2
			if f.F1 == nil {
				return errors.New("G1.G2.F1 cannot be nil")
			}
		}
		if f.F2 == nil {
			return errors.New("G1.F2 cannot be nil")
		}
	}
	if v.FX == nil || *v.FX == nil || **v.FX == nil || ***v.FX == nil || ****v.FX == nil || *****v.FX == nil {
		return errors.New("FX cannot be nil")
	}
	if v.GX == nil || *v.GX == nil || **v.GX == nil || ***v.GX == nil || ****v.GX == nil {
		return errors.New("GX cannot be nil")
	} else {
		f := *****v.GX
		if f.F1 == nil {
			return errors.New("GX.F1 cannot be nil")
		}
		if f.F2 == nil || *f.F2 == nil {
			return errors.New("GX.F2 cannot be nil")
		}
		if f.F3 == nil || *f.F3 == nil || **f.F3 == nil {
			return errors.New("GX.F3 cannot be nil")
		}
	}
	return nil
}
