// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v OmitEmptyValidator) Validate() error {
	if len(v.F1) > 0 && !isvalid.Email(v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if len(v.F2) > 0 {
		f := v.F2
		if !isvalid.Email(f) {
			return errors.New("F2 must be a valid email address")
		} else if len(f) < 5 || len(f) > 85 {
			return errors.New("F2 must be of length between: 5 and 85 (inclusive)")
		}
	}
	if v.F3 != nil && len(*v.F3) > 0 && !isvalid.Email(*v.F3) {
		return errors.New("F3 must be a valid email address")
	}
	if v.F4 != nil && len(*v.F4) > 0 {
		f := *v.F4
		if !isvalid.Email(f) {
			return errors.New("F4 must be a valid email address")
		} else if len(f) < 5 || len(f) > 85 {
			return errors.New("F4 must be of length between: 5 and 85 (inclusive)")
		}
	}
	return nil
}
