// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
	"strings"
)

func (v PrefixValidator) Validate() error {
	if !strings.HasPrefix(v.F1, "foo") {
		return errors.New("F1 must be prefixed with: \"foo\"")
	}
	if v.F2 != nil {
		f := *v.F2
		if !strings.HasPrefix(f, "bar") {
			return errors.New("F2 must be prefixed with: \"bar\"")
		}
	}
	if v.F3 == nil || *v.F3 == nil || len(**v.F3) == 0 {
		return errors.New("F3 is required")
	} else {
		f := **v.F3
		if !strings.HasPrefix(f, "foo") && !strings.HasPrefix(f, "bar") && !strings.HasPrefix(f, "baz") {
			return errors.New("F3 must be prefixed with: \"foo\" or \"bar\" or \"baz\"")
		}
	}
	return nil
}
