// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func init() {
	isvalid.RegisterRegexp(`foo`)
	isvalid.RegisterRegexp(`^[a-z]+\[[0-9]+\]$`)
	isvalid.RegisterRegexp(`\w+`)
}

func (v RegexpValidator) Validate() error {
	if !isvalid.Match(v.F1, `foo`) {
		return errors.New("F1 must match the regular expression: \"foo\"")
	}
	if v.F2 != nil {
		f := *v.F2
		if !isvalid.Match(f, `^[a-z]+\[[0-9]+\]$`) {
			return errors.New("F2 must match the regular expression: \"^[a-z]+\\\\[[0-9]+\\\\]$\"")
		}
	}
	if v.F3 == nil || *v.F3 == nil || len(**v.F3) == 0 {
		return errors.New("F3 is required")
	} else {
		f := **v.F3
		if !isvalid.Match(f, `\w+`) {
			return errors.New("F3 must match the regular expression: \"\\\\w+\"")
		}
	}
	return nil
}
