// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v Required2Validator) Validate() error {
	if v.G1.F1 == nil || len(*v.G1.F1) == 0 {
		return errors.New("G1.F1 is required")
	}
	if v.G1.G3 == nil {
		return errors.New("G1.G3 is required")
	}
	return nil
}
