// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
)

func (v RequiredValidator) Validate() error {
	if v.F1 == nil || len(*v.F1) == 0 {
		return errors.New("F1 is required")
	}
	if len(v.F2) == 0 {
		return errors.New("F2 is required")
	}
	if v.F3 == 0 {
		return errors.New("F3 is required")
	}
	if v.F4 == nil || *v.F4 == 0.0 {
		return errors.New("F4 is required")
	}
	if v.F5 == nil || *v.F5 == nil {
		return errors.New("F5 is required")
	}
	if v.F6 == nil || *v.F6 == nil || **v.F6 == false {
		return errors.New("F6 is required")
	}
	if len(v.F7) == 0 {
		return errors.New("F7 is required")
	}
	if v.F8 == nil || len(*v.F8) == 0 {
		return errors.New("F8 is required")
	}
	if v.G1.F1 == nil || len(*v.G1.F1) == 0 {
		return errors.New("G1.F1 is required")
	}
	if v.G1.G2 == nil {
		return errors.New("G1.G2 is required")
	} else {
		f := *v.G1.G2
		if f.F1 == nil || len(*f.F1) == 0 {
			return errors.New("G1.G2.F1 is required")
		}
	}
	if v.G1.F2 == nil || len(*v.G1.F2) == 0 {
		return errors.New("G1.F2 is required")
	}
	if v.G1.G3 == nil {
		return errors.New("G1.G3 is required")
	}
	if v.FX == nil || *v.FX == nil || **v.FX == nil || ***v.FX == nil || ****v.FX == nil || *****v.FX == nil {
		return errors.New("FX is required")
	}
	if v.GX == nil || *v.GX == nil || **v.GX == nil || ***v.GX == nil || ****v.GX == nil {
		return errors.New("GX is required")
	} else {
		f := *****v.GX
		if len(f.F1) == 0 {
			return errors.New("GX.F1 is required")
		}
		if f.F2 == 0 {
			return errors.New("GX.F2 is required")
		}
		if f.F3 == 0.0 {
			return errors.New("GX.F3 is required")
		}
	}
	return nil
}
