// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v RFCValidator) Validate() error {
	if !isvalid.RFC(v.F1, 1234) {
		return errors.New("F1 must be a valid RFC: 1234")
	}
	if v.F2 != nil && *v.F2 != nil && !isvalid.RFC(**v.F2, 4321) {
		return errors.New("F2 must be a valid RFC: 4321")
	}
	if v.F3 == nil || *v.F3 == nil || len(**v.F3) == 0 {
		return errors.New("F3 is required")
	} else if !isvalid.RFC(**v.F3, 6) {
		return errors.New("F3 must be a valid RFC: 6")
	}
	return nil
}
