// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v SliceValidator) Validate() error {
	for _, e := range v.F1 {
		if !isvalid.Email(e) {
			return errors.New("F1 must be a valid email address")
		}
	}
	if v.F2 != nil && *v.F2 != nil && **v.F2 != nil {
		for _, e := range ***v.F2 {
			if !isvalid.Email(e) {
				return errors.New("F2 must be a valid email address")
			}
		}
	}
	if v.F3 != nil {
		for _, e := range *v.F3 {
			if e == nil || len(*e) == 0 {
				return errors.New("F3 is required")
			} else if !isvalid.Email(*e) {
				return errors.New("F3 must be a valid email address")
			}
		}
	}
	for k, e := range v.F4 {
		if !isvalid.Email(k) {
			return errors.New("F4 must be a valid email address")
		}
		if e < 18 || e > 64 {
			return errors.New("F4 must be between: 18 and 64")
		}
	}
	for _, e := range v.F5 {
		for k, e := range e {
			if k != nil {
				for k, e := range *k {
					if !isvalid.Email(k) {
						return errors.New("F5 must be a valid email address")
					}
					if !isvalid.Phone(e, "ca") {
						return errors.New("F5 must be a valid phone number")
					}
				}
			}
			if len(e) > 10 {
				return errors.New("F5 must be of length at most: 10")
			}
			for _, e := range e {
				if e < -54 || e > 256 {
					return errors.New("F5 must be between: -54 and 256")
				}
			}
		}
	}
	return nil
}
