// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v SliceValidator) Validate() error {
	for _, e := range v.F1 {
		if !isvalid.Email(e) {
			return errors.New("F1 must be a valid email")
		}
	}
	for _, e := range ***v.F2 {
		if !isvalid.Email(e) {
			return errors.New("F2 must be a valid email")
		}
	}
	for _, e := range *v.F3 {
		if e == nil || len(*e) == 0 {
			return errors.New("F3 is required")
		} else if !isvalid.Email(*e) {
			return errors.New("F3 must be a valid email")
		}
	}
	for k, e := range v.F4 {
		if !isvalid.Email(k) {
			return errors.New("F4 must be a valid email")
		}
		if e < 18 || e > 64 {
			return errors.New("F4 must be between: 18 and 64")
		}
	}
	return nil
}
