// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v Slice2Validator) Validate() error {
	if len(v.F1) == 0 {
		return errors.New("F1 is required")
	}
	for _, e := range v.F1 {
		if !isvalid.Email(e) {
			return errors.New("F1 must be a valid email address")
		}
	}
	if len(v.F2) < 1 {
		return errors.New("F2 must be of length at least: 1")
	}
	for _, e := range v.F2 {
		if !isvalid.Email(e) {
			return errors.New("F2 must be a valid email address")
		}
	}
	return nil
}
