// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"

	"github.com/frk/isvalid"
)

func (v StrongPasswordValidator) Validate() error {
	if !isvalid.StrongPassword(v.F1, nil) {
		return errors.New("F1 must be a strong password")
	}
	if !isvalid.StrongPassword(v.F2, nil) {
		return errors.New("F2 must be a strong password")
	}
	if !isvalid.StrongPassword(v.F3, v.opts) {
		return errors.New("F3 must be a strong password")
	}
	if !isvalid.StrongPassword(v.F4, &v.opts2) {
		return errors.New("F4 must be a strong password")
	}
	return nil
}
