// DO NOT EDIT. This file was generated by "github.com/frk/isvalid".

package testdata

import (
	"errors"
	"strings"
)

func (v SuffixValidator) Validate() error {
	if !strings.HasSuffix(v.F1, "foo") {
		return errors.New("F1 must be suffixed with: \"foo\"")
	}
	if v.F2 != nil && !strings.HasSuffix(*v.F2, "bar") {
		return errors.New("F2 must be suffixed with: \"bar\"")
	}
	if v.F3 == nil || *v.F3 == nil || len(**v.F3) == 0 {
		return errors.New("F3 is required")
	} else if !strings.HasSuffix(**v.F3, "foo") && !strings.HasSuffix(**v.F3, "bar") && !strings.HasSuffix(**v.F3, "baz") {
		return errors.New("F3 must be suffixed with: \"foo\" or \"bar\" or \"baz\"")
	}
	return nil
}
