// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.ASCII(v.F1) {
		return errors.New("F1 must contain only ASCII characters")
	}
	if v.F2 != nil && !valid.ASCII(*v.F2) {
		return errors.New("F2 must contain only ASCII characters")
	}
	return nil
}
