// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
	"strings"

	"github.com/frk/valid"
)

func (v *UserCreateParamsValidator) Validate() error {
	v.FName = strings.TrimSpace(v.FName)
	if len(v.FName) < 1 || len(v.FName) > 300 {
		return errors.New("FName must be of length between: 1 and 300 (inclusive)")
	}
	v.LName = strings.TrimSpace(v.LName)
	if v.LName == "" {
		return errors.New("LName is required")
	} else if len(v.LName) < 1 || len(v.LName) > 300 {
		return errors.New("LName must be of length between: 1 and 300 (inclusive)")
	}
	v.Email = strings.TrimSpace(strings.ToLower(v.Email))
	if v.Email == "" {
		return errors.New("Email is required")
	} else if !valid.Email(v.Email) {
		return errors.New("Email must be a valid email address")
	}
	v.Passw = strings.TrimSpace(v.Passw)
	if v.Passw == "" {
		return errors.New("Passw is required")
	} else if !valid.StrongPassword(v.Passw, nil) {
		return errors.New("Passw must be a strong password")
	}
	if v.Age < 3 {
		return errors.New("Age must be greater than or equal to: 3")
	} else if v.Age > 150 {
		return errors.New("Age must be less than or equal to: 150")
	}
	return nil
}
