// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.MAC(v.F1, 0) {
		return errors.New("F1 must be a valid MAC")
	}
	if v.F2 != nil && !valid.MAC(*v.F2, 0) {
		return errors.New("F2 must be a valid MAC")
	}
	if !valid.MAC(v.F3, 6) {
		return errors.New("F3 must be a valid MAC")
	}
	if v.F4 != nil && !valid.MAC(*v.F4, 8) {
		return errors.New("F4 must be a valid MAC")
	}
	return nil
}
