// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.StrongPassword(v.F1, nil) {
		return errors.New("F1 must be a strong password")
	}
	if v.F2 != nil && !valid.StrongPassword(*v.F2, nil) {
		return errors.New("F2 must be a strong password")
	}
	if !valid.StrongPassword(v.F3, v.pwOpts) {
		return errors.New("F3 must be a strong password")
	}
	return nil
}
