// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if v.F1 != "" && !valid.Email(v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if v.F2 != nil && *v.F2 > 0 && *v.F2 != 42 {
		return errors.New("F2 must be equal to: 42")
	}
	return nil
}
