package tables

var ISO4217 = make(map[string]struct{})

func init() {
	for _, ccy := range currencies {
		// set of ISO 4217 codes
		ISO4217[ccy.code] = struct{}{}
	}
}

type currency struct {
	// The ISO 4217 code of the currency.
	code string
	// The currency's three digit numeric code as assigned by ISO 4217.
	num string
	// The symbol(s) of the currency.
	sym string
	// The number of digits after the decimal separator.
	dec int
	// The decimal separator(s) of the currency.
	sep rune
	// The (short) name of the currency.
	name string
}

// https://en.wikipedia.org/wiki/ISO_4217

var currencies = []currency{
	{code: "AED", num: "784", sym: `د.إ`, dec: 2, name: "United Arab Emirates dirham"},
	{code: "AFN", num: "971", sym: `؋`, dec: 2, name: "Afghan afghani"},
	{code: "ALL", num: "008", sym: `L`, dec: 2, name: "Albanian lek"},
	{code: "AMD", num: "051", sym: `֏`, dec: 2, name: "Armenian dram"},
	{code: "ANG", num: "532", sym: `ƒ`, dec: 2, name: "Netherlands Antillean guilder"},
	{code: "AOA", num: "973", sym: `Kz`, dec: 2, name: "Angolan kwanza"},
	{code: "ARS", num: "032", sym: `$`, dec: 2, name: "Argentine peso"},
	{code: "AUD", num: "036", sym: `$`, dec: 2, name: "Australian dollar"},
	{code: "AWG", num: "533", sym: `ƒ`, dec: 2, name: "Aruban florin"},
	{code: "AZN", num: "944", sym: `₼`, dec: 2, name: "Azerbaijani manat"},
	{code: "BAM", num: "977", sym: `KM,КМ`, dec: 2, name: "Bosnia and Herzegovina convertible mark"},
	{code: "BBD", num: "052", sym: `$`, dec: 2, name: "Barbados dollar"},
	{code: "BDT", num: "050", sym: `৳`, dec: 2, name: "Bangladeshi taka"},
	{code: "BGN", num: "975", sym: `лв.`, dec: 2, name: "Bulgarian lev"},
	{code: "BHD", num: "048", sym: `.د.ب`, dec: 3, name: "Bahraini dinar"},
	{code: "BIF", num: "108", sym: `Fr`, dec: 0, name: "Burundian franc"},
	{code: "BMD", num: "060", sym: `$`, dec: 2, name: "Bermudian dollar"},
	{code: "BND", num: "096", sym: `$`, dec: 2, name: "Brunei dollar"},
	{code: "BOB", num: "068", sym: `Bs.`, dec: 2, name: "Boliviano"},
	{code: "BOV", num: "984", sym: ``, dec: 2, name: "Bolivian Mvdol (funds code)"},
	{code: "BRL", num: "986", sym: `R$`, dec: 2, name: "Brazilian real"},
	{code: "BSD", num: "044", sym: `$`, dec: 2, name: "Bahamian dollar"},
	{code: "BTN", num: "064", sym: `Nu.`, dec: 2, name: "Bhutanese ngultrum"},
	{code: "BWP", num: "072", sym: `P`, dec: 2, name: "Botswana pula"},
	{code: "BYN", num: "933", sym: `Br`, dec: 2, name: "Belarusian ruble"},
	{code: "BZD", num: "084", sym: `$`, dec: 2, name: "Belize dollar"},
	{code: "CAD", num: "124", sym: `$`, dec: 2, name: "Canadian dollar"},
	{code: "CDF", num: "976", sym: `Fr`, dec: 2, name: "Congolese franc"},
	{code: "CHE", num: "947", sym: ``, dec: 2, name: "WIR euro (complementary currency)"},
	{code: "CHF", num: "756", sym: `Fr.`, dec: 2, name: "Swiss franc"},
	{code: "CHW", num: "948", sym: ``, dec: 2, name: "WIR franc (complementary currency)"},
	{code: "CLF", num: "990", sym: ``, dec: 4, name: "Unidad de Fomento (funds code)"},
	{code: "CLP", num: "152", sym: `$`, dec: 0, name: "Chilean peso"},
	{code: "CNY", num: "156", sym: `¥,元`, dec: 2, name: "Chinese yuan"},
	{code: "COP", num: "170", sym: `$`, dec: 2, name: "Colombian peso"},
	{code: "COU", num: "970", sym: ``, dec: 2, name: "Unidad de Valor Real (UVR) (funds code)"},
	{code: "CRC", num: "188", sym: `₡`, dec: 2, name: "Costa Rican colon"},
	{code: "CUC", num: "931", sym: `$`, dec: 2, name: "Cuban convertible peso"},
	{code: "CUP", num: "192", sym: `$`, dec: 2, name: "Cuban peso"},
	{code: "CVE", num: "132", sym: `Esc,$`, dec: 2, name: "Cape Verdean escudo"},
	{code: "CZK", num: "203", sym: `Kč`, dec: 2, name: "Czech koruna"},
	{code: "DJF", num: "262", sym: `Fr`, dec: 0, name: "Djiboutian franc"},
	{code: "DKK", num: "208", sym: `kr`, dec: 2, name: "Danish krone"},
	{code: "DOP", num: "214", sym: `RD$`, dec: 2, name: "Dominican peso"},
	{code: "DZD", num: "012", sym: `د.ج`, dec: 2, name: "Algerian dinar"},
	{code: "EGP", num: "818", sym: `£,ج.م`, dec: 2, name: "Egyptian pound"},
	{code: "ERN", num: "232", sym: `Nfk`, dec: 2, name: "Eritrean nakfa"},
	{code: "ETB", num: "230", sym: `Br`, dec: 2, name: "Ethiopian birr"},
	{code: "EUR", num: "978", sym: `€`, dec: 2, name: "Euro"},
	{code: "FJD", num: "242", sym: `$`, dec: 2, name: "Fiji dollar"},
	{code: "FKP", num: "238", sym: `£`, dec: 2, name: "Falkland Islands pound"},
	{code: "GBP", num: "826", sym: `£`, dec: 2, name: "Pound sterling"},
	{code: "GEL", num: "981", sym: `₾`, dec: 2, name: "Georgian lari"},
	{code: "GHS", num: "936", sym: `₵`, dec: 2, name: "Ghanaian cedi"},
	{code: "GIP", num: "292", sym: `£`, dec: 2, name: "Gibraltar pound"},
	{code: "GMD", num: "270", sym: `D`, dec: 2, name: "Gambian dalasi"},
	{code: "GNF", num: "324", sym: `Fr`, dec: 0, name: "Guinean franc"},
	{code: "GTQ", num: "320", sym: `Q`, dec: 2, name: "Guatemalan quetzal"},
	{code: "GYD", num: "328", sym: `$`, dec: 2, name: "Guyanese dollar"},
	{code: "HKD", num: "344", sym: `$`, dec: 2, name: "Hong Kong dollar"},
	{code: "HNL", num: "340", sym: `L`, dec: 2, name: "Honduran lempira"},
	{code: "HRK", num: "191", sym: `kn`, dec: 2, name: "Croatian kuna"},
	{code: "HTG", num: "332", sym: `G`, dec: 2, name: "Haitian gourde"},
	{code: "HUF", num: "348", sym: `Ft`, dec: 2, name: "Hungarian forint"},
	{code: "IDR", num: "360", sym: `Rp`, dec: 2, name: "Indonesian rupiah"},
	{code: "ILS", num: "376", sym: `₪`, dec: 2, name: "Israeli new shekel"},
	{code: "INR", num: "356", sym: `₹`, dec: 2, name: "Indian rupee"},
	{code: "IQD", num: "368", sym: `ع.د`, dec: 3, name: "Iraqi dinar"},
	{code: "IRR", num: "364", sym: `﷼`, dec: 2, name: "Iranian rial"},
	{code: "ISK", num: "352", sym: `kr`, dec: 0, name: "Icelandic króna"},
	{code: "JMD", num: "388", sym: `$`, dec: 2, name: "Jamaican dollar"},
	{code: "JOD", num: "400", sym: `د.ا`, dec: 3, name: "Jordanian dinar"},
	{code: "JPY", num: "392", sym: `¥,円`, dec: 0, name: "Japanese yen"},
	{code: "KES", num: "404", sym: `Sh`, dec: 2, name: "Kenyan shilling"},
	{code: "KGS", num: "417", sym: `с`, dec: 2, name: "Kyrgyzstani som"},
	{code: "KHR", num: "116", sym: `៛`, dec: 2, name: "Cambodian riel"},
	{code: "KMF", num: "174", sym: `Fr`, dec: 0, name: "Comoro franc"},
	{code: "KPW", num: "408", sym: `₩`, dec: 2, name: "North Korean won"},
	{code: "KRW", num: "410", sym: `₩`, dec: 0, name: "South Korean won"},
	{code: "KWD", num: "414", sym: `د.ك`, dec: 3, name: "Kuwaiti dinar"},
	{code: "KYD", num: "136", sym: `$`, dec: 2, name: "Cayman Islands dollar"},
	{code: "KZT", num: "398", sym: `₸`, dec: 2, name: "Kazakhstani tenge"},
	{code: "LAK", num: "418", sym: `₭`, dec: 2, name: "Lao kip"},
	{code: "LBP", num: "422", sym: `ل.ل`, dec: 2, name: "Lebanese pound"},
	{code: "LKR", num: "144", sym: `Rs,රු,ரூ`, dec: 2, name: "Sri Lankan rupee"},
	{code: "LRD", num: "430", sym: `$`, dec: 2, name: "Liberian dollar"},
	{code: "LSL", num: "426", sym: `L`, dec: 2, name: "Lesotho loti"},
	{code: "LYD", num: "434", sym: `ل.د`, dec: 3, name: "Libyan dinar"},
	{code: "MAD", num: "504", sym: `د.م.`, dec: 2, name: "Moroccan dirham"},
	{code: "MDL", num: "498", sym: `L`, dec: 2, name: "Moldovan leu"},
	{code: "MGA", num: "969", sym: `Ar`, dec: 2, name: "Malagasy ariary"},
	{code: "MKD", num: "807", sym: `ден`, dec: 2, name: "Macedonian denar"},
	{code: "MMK", num: "104", sym: `Ks`, dec: 2, name: "Myanmar kyat"},
	{code: "MNT", num: "496", sym: `₮`, dec: 2, name: "Mongolian tögrög"},
	{code: "MOP", num: "446", sym: `MOP$`, dec: 2, name: "Macanese pataca"},
	{code: "MRU", num: "929", sym: `UM`, dec: 2, name: "Mauritanian ouguiya"},
	{code: "MUR", num: "480", sym: `₨`, dec: 2, name: "Mauritian rupee"},
	{code: "MVR", num: "462", sym: `.ރ`, dec: 2, name: "Maldivian rufiyaa"},
	{code: "MWK", num: "454", sym: `MK`, dec: 2, name: "Malawian kwacha"},
	{code: "MXN", num: "484", sym: `$`, dec: 2, name: "Mexican peso"},
	{code: "MXV", num: "979", sym: ``, dec: 2, name: "Mexican Unidad de Inversion (UDI) (funds code)"},
	{code: "MYR", num: "458", sym: `RM`, dec: 2, name: "Malaysian ringgit"},
	{code: "MZN", num: "943", sym: `MT`, dec: 2, name: "Mozambican metical"},
	{code: "NAD", num: "516", sym: `$`, dec: 2, name: "Namibian dollar"},
	{code: "NGN", num: "566", sym: `₦`, dec: 2, name: "Nigerian naira"},
	{code: "NIO", num: "558", sym: `C$`, dec: 2, name: "Nicaraguan córdoba"},
	{code: "NOK", num: "578", sym: `kr`, dec: 2, name: "Norwegian krone"},
	{code: "NPR", num: "524", sym: `रू`, dec: 2, name: "Nepalese rupee"},
	{code: "NZD", num: "554", sym: `$`, dec: 2, name: "New Zealand dollar"},
	{code: "OMR", num: "512", sym: `ر.ع.`, dec: 3, name: "Omani rial"},
	{code: "PAB", num: "590", sym: `B/.`, dec: 2, name: "Panamanian balboa"},
	{code: "PEN", num: "604", sym: `S/.`, dec: 2, name: "Peruvian sol"},
	{code: "PGK", num: "598", sym: `K`, dec: 2, name: "Papua New Guinean kina"},
	{code: "PHP", num: "608", sym: `₱`, dec: 2, name: "Philippine peso"},
	{code: "PKR", num: "586", sym: `₨`, dec: 2, name: "Pakistani rupee"},
	{code: "PLN", num: "985", sym: `zł`, dec: 2, name: "Polish złoty"},
	{code: "PYG", num: "600", sym: `₲`, dec: 0, name: "Paraguayan guaraní"},
	{code: "QAR", num: "634", sym: `ر.ق`, dec: 2, name: "Qatari riyal"},
	{code: "RON", num: "946", sym: `lei`, dec: 2, name: "Romanian leu"},
	{code: "RSD", num: "941", sym: `дин.,din.`, dec: 2, name: "Serbian dinar"},
	{code: "RUB", num: "643", sym: `₽`, dec: 2, name: "Russian ruble"},
	{code: "RWF", num: "646", sym: `Fr`, dec: 0, name: "Rwandan franc"},
	{code: "SAR", num: "682", sym: `﷼`, dec: 2, name: "Saudi riyal"},
	{code: "SBD", num: "090", sym: `$`, dec: 2, name: "Solomon Islands dollar"},
	{code: "SCR", num: "690", sym: `₨`, dec: 2, name: "Seychelles rupee"},
	{code: "SDG", num: "938", sym: `ج.س.`, dec: 2, name: "Sudanese pound"},
	{code: "SEK", num: "752", sym: `kr`, dec: 2, name: "Swedish krona/kronor"},
	{code: "SGD", num: "702", sym: `$`, dec: 2, name: "Singapore dollar"},
	{code: "SHP", num: "654", sym: `£`, dec: 2, name: "Saint Helena pound"},
	{code: "SLL", num: "694", sym: `Le`, dec: 2, name: "Sierra Leonean leone"},
	{code: "SOS", num: "706", sym: `Sh`, dec: 2, name: "Somali shilling"},
	{code: "SRD", num: "968", sym: `$`, dec: 2, name: "Surinamese dollar"},
	{code: "SSP", num: "728", sym: `£`, dec: 2, name: "South Sudanese pound"},
	{code: "STN", num: "930", sym: `Db`, dec: 2, name: "São Tomé and Príncipe dobra"},
	{code: "SVC", num: "222", sym: ``, dec: 2, name: "Salvadoran colón"},
	{code: "SYP", num: "760", sym: `£,ل.س`, dec: 2, name: "Syrian pound"},
	{code: "SZL", num: "748", sym: `L`, dec: 2, name: "Swazi lilangeni"},
	{code: "THB", num: "764", sym: `฿`, dec: 2, name: "Thai baht"},
	{code: "TJS", num: "972", sym: `ЅМ`, dec: 2, name: "Tajikistani somoni"},
	{code: "TMT", num: "934", sym: `m`, dec: 2, name: "Turkmenistan manat"},
	{code: "TND", num: "788", sym: `د.ت`, dec: 3, name: "Tunisian dinar"},
	{code: "TOP", num: "776", sym: `T$`, dec: 2, name: "Tongan paʻanga"},
	{code: "TRY", num: "949", sym: `₺`, dec: 2, name: "Turkish lira"},
	{code: "TTD", num: "780", sym: `$`, dec: 2, name: "Trinidad and Tobago dollar"},
	{code: "TWD", num: "901", sym: `$`, dec: 2, name: "New Taiwan dollar"},
	{code: "TZS", num: "834", sym: `Sh`, dec: 2, name: "Tanzanian shilling"},
	{code: "UAH", num: "980", sym: `₴`, dec: 2, name: "Ukrainian hryvnia"},
	{code: "UGX", num: "800", sym: `Sh`, dec: 0, name: "Ugandan shilling"},
	{code: "USD", num: "840", sym: `$`, dec: 2, name: "United States dollar"},
	{code: "USN", num: "997", sym: `$`, dec: 2, name: "United States dollar"},
	{code: "UYI", num: "940", sym: ``, dec: 0, name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"},
	{code: "UYU", num: "858", sym: `$`, dec: 2, name: "Uruguayan peso"},
	{code: "UYW", num: "927", sym: ``, dec: 4, name: "Unidad previsional"},
	{code: "UZS", num: "860", sym: `so'm,сўм`, dec: 2, name: "Uzbekistan som"},
	{code: "VES", num: "928", sym: `Bs.S.,Bs.`, dec: 2, name: "Venezuelan bolívar soberano"},
	{code: "VND", num: "704", sym: `₫`, dec: 0, name: "Vietnamese đồng"},
	{code: "VUV", num: "548", sym: `Vt`, dec: 0, name: "Vanuatu vatu"},
	{code: "WST", num: "882", sym: `T`, dec: 2, name: "Samoan tala"},
	{code: "XAF", num: "950", sym: `Fr`, dec: 0, name: "CFA franc BEAC"},
	{code: "XAG", num: "961", sym: ``, dec: -1, name: "Silver (one troy ounce)"},
	{code: "XAU", num: "959", sym: ``, dec: -1, name: "Gold (one troy ounce)"},
	{code: "XBA", num: "955", sym: ``, dec: -1, name: "European Composite Unit (EURCO) (bond market unit)"},
	{code: "XBB", num: "956", sym: ``, dec: -1, name: "European Monetary Unit (E.M.U.-6) (bond market unit)"},
	{code: "XBC", num: "957", sym: ``, dec: -1, name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)"},
	{code: "XBD", num: "958", sym: ``, dec: -1, name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)"},
	{code: "XCD", num: "951", sym: `$`, dec: 2, name: "East Caribbean dollar"},
	{code: "XDR", num: "960", sym: ``, dec: -1, name: "Special drawing rights"},
	{code: "XOF", num: "952", sym: `Fr`, dec: 0, name: "CFA franc BCEAO"},
	{code: "XPD", num: "964", sym: ``, dec: -1, name: "Palladium (one troy ounce)"},
	{code: "XPF", num: "953", sym: `₣`, dec: 0, name: "CFP franc (franc Pacifique)"},
	{code: "XPT", num: "962", sym: ``, dec: -1, name: "Platinum (one troy ounce)"},
	{code: "XSU", num: "994", sym: ``, dec: -1, name: "SUCRE"},
	{code: "XTS", num: "963", sym: ``, dec: -1, name: "Code reserved for testing"},
	{code: "XUA", num: "965", sym: ``, dec: -1, name: "ADB Unit of Account"},
	{code: "XXX", num: "999", sym: ``, dec: -1, name: "No currency"},
	{code: "YER", num: "886", sym: `ر.ي`, dec: 2, name: "Yemeni rial"},
	{code: "ZAR", num: "710", sym: `R`, dec: 2, name: "South African rand"},
	{code: "ZMW", num: "967", sym: `ZK`, dec: 2, name: "Zambian kwacha"},
	{code: "ZWL", num: "932", sym: `$`, dec: 2, name: "Zimbabwean dollar"},
}
