package tables

var ISO4217 = make(map[string]Currency)

func init() {
	for _, ccy := range currencies {
		// set of ISO 4217 codes
		ISO4217[ccy.code] = ccy
	}
}

type Currency struct {
	// The ISO 4217 code of the currency.
	code string
	// The currency's three digit numeric code as assigned by ISO 4217.
	num string
	// The (short) name of the currency.
	name string

	// The symbol(s) of the currency.
	Sym []string
	// List of strings that can optionally be used to separate the
	// symbol from the monetary value.
	Sep []string
	// Inidicates whether or not the currency's symbol should be on
	// the left side of the monetary value.
	Left bool
	// Inidicates whether or not the currency's symbol should be on
	// the right side of the monetary value.
	Right bool
	// The number of digits after the decimal separator.
	DecNum int
	// The decimal separator(s) of the currency.
	DecSep []rune
	// The thousands separator(s) of the currency.
	ThoSep []rune
	// Optional alternative numerals of the currency.
	AltNum string
}

// https://en.wikipedia.org/wiki/ISO_4217

var currencies = []Currency{
	{code: "AED", num: "784", name: "United Arab Emirates dirham",
		Sym: []string{`د.إ`}, DecNum: 2},
	{code: "AFN", num: "971", name: "Afghan afghani",
		Sym: []string{`؋`}, DecNum: 2},
	{code: "ALL", num: "008", name: "Albanian lek",
		Sym: []string{`L`}, DecNum: 2},
	{code: "AMD", num: "051", name: "Armenian dram",
		Sym: []string{`֏`}, DecNum: 2},
	{code: "ANG", num: "532", name: "Netherlands Antillean guilder",
		Sym: []string{`ƒ`}, DecNum: 2},
	{code: "AOA", num: "973", name: "Angolan kwanza",
		Sym: []string{`Kz`}, DecNum: 2},
	{code: "ARS", num: "032", name: "Argentine peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "AUD", num: "036", name: "Australian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "AWG", num: "533", name: "Aruban florin",
		Sym: []string{`ƒ`}, DecNum: 2},
	{code: "AZN", num: "944", name: "Azerbaijani manat",
		Sym: []string{`₼`}, DecNum: 2},
	{code: "BAM", num: "977", name: "Bosnia and Herzegovina convertible mark",
		Sym: []string{`KM`, `КМ`}, DecNum: 2},
	{code: "BBD", num: "052", name: "Barbados dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "BDT", num: "050", name: "Bangladeshi taka",
		Sym: []string{`৳`}, DecNum: 2},
	{code: "BGN", num: "975", name: "Bulgarian lev",
		Sym: []string{`лв.`}, DecNum: 2},
	{code: "BHD", num: "048", name: "Bahraini dinar",
		Sym: []string{`.د.ب`}, DecNum: 3},
	{code: "BIF", num: "108", name: "Burundian franc",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "BMD", num: "060", name: "Bermudian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "BND", num: "096", name: "Brunei dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "BOB", num: "068", name: "Boliviano",
		Sym: []string{`Bs.`}, DecNum: 2},
	{code: "BOV", num: "984", name: "Bolivian Mvdol (funds code)",
		Sym: nil, DecNum: 2},
	{code: "BRL", num: "986", name: "Brazilian real",
		Sym: []string{`R$`}, DecNum: 2},
	{code: "BSD", num: "044", name: "Bahamian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "BTN", num: "064", name: "Bhutanese ngultrum",
		Sym: []string{`Nu.`}, DecNum: 2},
	{code: "BWP", num: "072", name: "Botswana pula",
		Sym: []string{`P`}, DecNum: 2},
	{code: "BYN", num: "933", name: "Belarusian ruble",
		Sym: []string{`Br`}, DecNum: 2},
	{code: "BZD", num: "084", name: "Belize dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "CAD", num: "124", name: "Canadian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "CDF", num: "976", name: "Congolese franc",
		Sym: []string{`Fr`}, DecNum: 2},
	{code: "CHE", num: "947", name: "WIR euro (complementary currency)",
		Sym: nil, DecNum: 2},
	{code: "CHF", num: "756", name: "Swiss franc",
		Sym: []string{`Fr.`}, DecNum: 2},
	{code: "CHW", num: "948", name: "WIR franc (complementary currency)",
		Sym: nil, DecNum: 2},
	{code: "CLF", num: "990", name: "Unidad de Fomento (funds code)",
		Sym: nil, DecNum: 4},
	{code: "CLP", num: "152", name: "Chilean peso",
		Sym: []string{`$`}, DecNum: 0},
	{code: "CNY", num: "156", name: "Chinese yuan",
		Sym: []string{`¥`, `元`}, DecNum: 2},
	{code: "COP", num: "170", name: "Colombian peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "COU", num: "970", name: "Unidad de Valor Real (UVR) (funds code)",
		Sym: nil, DecNum: 2},
	{code: "CRC", num: "188", name: "Costa Rican colon",
		Sym: []string{`₡`}, DecNum: 2},
	{code: "CUC", num: "931", name: "Cuban convertible peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "CUP", num: "192", name: "Cuban peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "CVE", num: "132", name: "Cape Verdean escudo",
		Sym: []string{`Esc`, `$`}, DecNum: 2},
	{code: "CZK", num: "203", name: "Czech koruna",
		Sym: []string{`Kč`}, DecNum: 2},
	{code: "DJF", num: "262", name: "Djiboutian franc",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "DKK", num: "208", name: "Danish krone",
		Sym: []string{`kr`}, DecNum: 2},
	{code: "DOP", num: "214", name: "Dominican peso",
		Sym: []string{`RD$`}, DecNum: 2},
	{code: "DZD", num: "012", name: "Algerian dinar",
		Sym: []string{`د.ج`}, DecNum: 2},
	{code: "EGP", num: "818", name: "Egyptian pound",
		Sym: []string{`ج.م`, `£`}, DecNum: 2},
	{code: "ERN", num: "232", name: "Eritrean nakfa",
		Sym: []string{`Nfk`}, DecNum: 2},
	{code: "ETB", num: "230", name: "Ethiopian birr",
		Sym: []string{`Br`}, DecNum: 2},
	{code: "EUR", num: "978", name: "Euro",
		Sym: []string{`€`}, DecNum: 2},
	{code: "FJD", num: "242", name: "Fiji dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "FKP", num: "238", name: "Falkland Islands pound",
		Sym: []string{`£`}, DecNum: 2},
	{code: "GBP", num: "826", name: "Pound sterling",
		Sym: []string{`£`}, Sep: []string{"\u2009", "\u202F"}, Left: true,
		DecNum: 2, DecSep: []rune{'.', '·'},
		ThoSep: []rune{',', ' '},
	},
	{code: "GEL", num: "981", name: "Georgian lari",
		Sym: []string{`₾`}, DecNum: 2},
	{code: "GHS", num: "936", name: "Ghanaian cedi",
		Sym: []string{`₵`}, DecNum: 2},
	{code: "GIP", num: "292", name: "Gibraltar pound",
		Sym: []string{`£`}, DecNum: 2},
	{code: "GMD", num: "270", name: "Gambian dalasi",
		Sym: []string{`D`}, DecNum: 2},
	{code: "GNF", num: "324", name: "Guinean franc",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "GTQ", num: "320", name: "Guatemalan quetzal",
		Sym: []string{`Q`}, DecNum: 2},
	{code: "GYD", num: "328", name: "Guyanese dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "HKD", num: "344", name: "Hong Kong dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "HNL", num: "340", name: "Honduran lempira",
		Sym: []string{`L`}, DecNum: 2},
	{code: "HRK", num: "191", name: "Croatian kuna",
		Sym: []string{`kn`}, DecNum: 2},
	{code: "HTG", num: "332", name: "Haitian gourde",
		Sym: []string{`G`}, DecNum: 2},
	{code: "HUF", num: "348", name: "Hungarian forint",
		Sym: []string{`Ft`}, DecNum: 2},
	{code: "IDR", num: "360", name: "Indonesian rupiah",
		Sym: []string{`Rp`}, DecNum: 2},
	{code: "ILS", num: "376", name: "Israeli new shekel",
		Sym: []string{`₪`}, DecNum: 2},
	{code: "INR", num: "356", name: "Indian rupee",
		Sym: []string{`₹`}, DecNum: 2},
	{code: "IQD", num: "368", name: "Iraqi dinar",
		Sym: []string{`ع.د`}, DecNum: 3},
	{code: "IRR", num: "364", name: "Iranian rial",
		Sym: []string{`﷼`}, DecNum: 2},
	{code: "ISK", num: "352", name: "Icelandic króna",
		Sym: []string{`kr`}, DecNum: 0},
	{code: "JMD", num: "388", name: "Jamaican dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "JOD", num: "400", name: "Jordanian dinar",
		Sym: []string{`د.ا`}, DecNum: 3},
	{code: "JPY", num: "392", name: "Japanese yen",
		Sym: []string{`¥`, `円`}, DecNum: 0},
	{code: "KES", num: "404", name: "Kenyan shilling",
		Sym: []string{`Sh`}, DecNum: 2},
	{code: "KGS", num: "417", name: "Kyrgyzstani som",
		Sym: []string{`с`}, DecNum: 2},
	{code: "KHR", num: "116", name: "Cambodian riel",
		Sym: []string{`៛`}, DecNum: 2},
	{code: "KMF", num: "174", name: "Comoro franc",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "KPW", num: "408", name: "North Korean won",
		Sym: []string{`₩`}, DecNum: 2},
	{code: "KRW", num: "410", name: "South Korean won",
		Sym: []string{`₩`}, DecNum: 0},
	{code: "KWD", num: "414", name: "Kuwaiti dinar",
		Sym: []string{`د.ك`}, DecNum: 3},
	{code: "KYD", num: "136", name: "Cayman Islands dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "KZT", num: "398", name: "Kazakhstani tenge",
		Sym: []string{`₸`}, DecNum: 2},
	{code: "LAK", num: "418", name: "Lao kip",
		Sym: []string{`₭`}, DecNum: 2},
	{code: "LBP", num: "422", name: "Lebanese pound",
		Sym: []string{`ل.ل`}, DecNum: 2},
	{code: "LKR", num: "144", name: "Sri Lankan rupee",
		Sym: []string{`Rs`, `රු`, "\u0BB0\u0BC2"}, DecNum: 2},
	{code: "LRD", num: "430", name: "Liberian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "LSL", num: "426", name: "Lesotho loti",
		Sym: []string{`L`}, DecNum: 2},
	{code: "LYD", num: "434", name: "Libyan dinar",
		Sym: []string{`ل.د`}, DecNum: 3},
	{code: "MAD", num: "504", name: "Moroccan dirham",
		Sym: []string{`د.م.`}, DecNum: 2},
	{code: "MDL", num: "498", name: "Moldovan leu",
		Sym: []string{`L`}, DecNum: 2},
	{code: "MGA", num: "969", name: "Malagasy ariary",
		Sym: []string{`Ar`}, DecNum: 2},
	{code: "MKD", num: "807", name: "Macedonian denar",
		Sym: []string{`ден`}, DecNum: 2},
	{code: "MMK", num: "104", name: "Myanmar kyat",
		Sym: []string{`Ks`}, DecNum: 2},
	{code: "MNT", num: "496", name: "Mongolian tögrög",
		Sym: []string{`₮`}, DecNum: 2},
	{code: "MOP", num: "446", name: "Macanese pataca",
		Sym: []string{`MOP$`}, DecNum: 2},
	{code: "MRU", num: "929", name: "Mauritanian ouguiya",
		Sym: []string{`UM`}, DecNum: 2},
	{code: "MUR", num: "480", name: "Mauritian rupee",
		Sym: []string{`₨`}, DecNum: 2},
	{code: "MVR", num: "462", name: "Maldivian rufiyaa",
		Sym: []string{`.ރ`}, DecNum: 2},
	{code: "MWK", num: "454", name: "Malawian kwacha",
		Sym: []string{`MK`}, DecNum: 2},
	{code: "MXN", num: "484", name: "Mexican peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "MXV", num: "979", name: "Mexican Unidad de Inversion (UDI) (funds code)",
		Sym: nil, DecNum: 2},
	{code: "MYR", num: "458", name: "Malaysian ringgit",
		Sym: []string{`RM`}, DecNum: 2},
	{code: "MZN", num: "943", name: "Mozambican metical",
		Sym: []string{`MT`}, DecNum: 2},
	{code: "NAD", num: "516", name: "Namibian dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "NGN", num: "566", name: "Nigerian naira",
		Sym: []string{`₦`}, DecNum: 2},
	{code: "NIO", num: "558", name: "Nicaraguan córdoba",
		Sym: []string{`C$`}, DecNum: 2},
	{code: "NOK", num: "578", name: "Norwegian krone",
		Sym: []string{`kr`}, DecNum: 2},
	{code: "NPR", num: "524", name: "Nepalese rupee",
		Sym: []string{`रू`}, DecNum: 2},
	{code: "NZD", num: "554", name: "New Zealand dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "OMR", num: "512", name: "Omani rial",
		Sym: []string{`ر.ع.`}, DecNum: 3},
	{code: "PAB", num: "590", name: "Panamanian balboa",
		Sym: []string{`B/.`}, DecNum: 2},
	{code: "PEN", num: "604", name: "Peruvian sol",
		Sym: []string{`S/.`}, DecNum: 2},
	{code: "PGK", num: "598", name: "Papua New Guinean kina",
		Sym: []string{`K`}, DecNum: 2},
	{code: "PHP", num: "608", name: "Philippine peso",
		Sym: []string{`₱`}, DecNum: 2},
	{code: "PKR", num: "586", name: "Pakistani rupee",
		Sym: []string{`₨`}, DecNum: 2},
	{code: "PLN", num: "985", name: "Polish złoty",
		Sym: []string{`zł`}, DecNum: 2},
	{code: "PYG", num: "600", name: "Paraguayan guaraní",
		Sym: []string{`₲`}, DecNum: 0},
	{code: "QAR", num: "634", name: "Qatari riyal",
		Sym: []string{`ر.ق`}, DecNum: 2},
	{code: "RON", num: "946", name: "Romanian leu",
		Sym: []string{`lei`}, DecNum: 2},
	{code: "RSD", num: "941", name: "Serbian dinar",
		Sym: []string{`дин.`, `din.`}, DecNum: 2},
	{code: "RUB", num: "643", name: "Russian ruble",
		Sym: []string{`₽`}, DecNum: 2},
	{code: "RWF", num: "646", name: "Rwandan franc",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "SAR", num: "682", name: "Saudi riyal",
		Sym: []string{`﷼`}, DecNum: 2},
	{code: "SBD", num: "090", name: "Solomon Islands dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "SCR", num: "690", name: "Seychelles rupee",
		Sym: []string{`₨`}, DecNum: 2},
	{code: "SDG", num: "938", name: "Sudanese pound",
		Sym: []string{`ج.س.`}, DecNum: 2},
	{code: "SEK", num: "752", name: "Swedish krona/kronor",
		Sym: []string{`kr`}, DecNum: 2},
	{code: "SGD", num: "702", name: "Singapore dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "SHP", num: "654", name: "Saint Helena pound",
		Sym: []string{`£`}, DecNum: 2},
	{code: "SLL", num: "694", name: "Sierra Leonean leone",
		Sym: []string{`Le`}, DecNum: 2},
	{code: "SOS", num: "706", name: "Somali shilling",
		Sym: []string{`Sh`}, DecNum: 2},
	{code: "SRD", num: "968", name: "Surinamese dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "SSP", num: "728", name: "South Sudanese pound",
		Sym: []string{`£`}, DecNum: 2},
	{code: "STN", num: "930", name: "São Tomé and Príncipe dobra",
		Sym: []string{`Db`}, DecNum: 2},
	{code: "SVC", num: "222", name: "Salvadoran colón",
		Sym: nil, DecNum: 2},
	{code: "SYP", num: "760", name: "Syrian pound",
		Sym: []string{`£`, `ل.س`}, DecNum: 2},
	{code: "SZL", num: "748", name: "Swazi lilangeni",
		Sym: []string{`L`}, DecNum: 2},
	{code: "THB", num: "764", name: "Thai baht",
		Sym: []string{`฿`}, DecNum: 2, AltNum: `๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙`},
	{code: "TJS", num: "972", name: "Tajikistani somoni",
		Sym: []string{`ЅМ`}, DecNum: 2},
	{code: "TMT", num: "934", name: "Turkmenistan manat",
		Sym: []string{`m`}, DecNum: 2},
	{code: "TND", num: "788", name: "Tunisian dinar",
		Sym: []string{`د.ت`}, DecNum: 3},
	{code: "TOP", num: "776", name: "Tongan paʻanga",
		Sym: []string{`T$`}, DecNum: 2},
	{code: "TRY", num: "949", name: "Turkish lira",
		Sym: []string{`₺`}, DecNum: 2},
	{code: "TTD", num: "780", name: "Trinidad and Tobago dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "TWD", num: "901", name: "New Taiwan dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "TZS", num: "834", name: "Tanzanian shilling",
		Sym: []string{`Sh`}, DecNum: 2},
	{code: "UAH", num: "980", name: "Ukrainian hryvnia",
		Sym: []string{`₴`}, DecNum: 2},
	{code: "UGX", num: "800", name: "Ugandan shilling",
		Sym: []string{`Sh`}, DecNum: 0},
	{code: "USD", num: "840", name: "United States dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "USN", num: "997", name: "United States dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "UYI", num: "940", name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)",
		Sym: nil, DecNum: 0},
	{code: "UYU", num: "858", name: "Uruguayan peso",
		Sym: []string{`$`}, DecNum: 2},
	{code: "UYW", num: "927", name: "Unidad previsional",
		Sym: nil, DecNum: 4},
	{code: "UZS", num: "860", name: "Uzbekistan som",
		Sym: []string{`so'm`, `сўм`}, DecNum: 2},
	{code: "VES", num: "928", name: "Venezuelan bolívar soberano",
		Sym: []string{`Bs.S.`, `Bs.`}, DecNum: 2},
	{code: "VND", num: "704", name: "Vietnamese đồng",
		Sym: []string{`₫`}, DecNum: 0},
	{code: "VUV", num: "548", name: "Vanuatu vatu",
		Sym: []string{`Vt`}, DecNum: 0},
	{code: "WST", num: "882", name: "Samoan tala",
		Sym: []string{`T`}, DecNum: 2},
	{code: "XAF", num: "950", name: "CFA franc BEAC",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "XAG", num: "961", name: "Silver (one troy ounce)",
		Sym: nil, DecNum: -1},
	{code: "XAU", num: "959", name: "Gold (one troy ounce)",
		Sym: nil, DecNum: -1},
	{code: "XBA", num: "955", name: "European Composite Unit (EURCO) (bond market unit)",
		Sym: nil, DecNum: -1},
	{code: "XBB", num: "956", name: "European Monetary Unit (E.M.U.-6) (bond market unit)",
		Sym: nil, DecNum: -1},
	{code: "XBC", num: "957", name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)",
		Sym: nil, DecNum: -1},
	{code: "XBD", num: "958", name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)",
		Sym: nil, DecNum: -1},
	{code: "XCD", num: "951", name: "East Caribbean dollar",
		Sym: []string{`$`}, DecNum: 2},
	{code: "XDR", num: "960", name: "Special drawing rights",
		Sym: nil, DecNum: -1},
	{code: "XOF", num: "952", name: "CFA franc BCEAO",
		Sym: []string{`Fr`}, DecNum: 0},
	{code: "XPD", num: "964", name: "Palladium (one troy ounce)",
		Sym: nil, DecNum: -1},
	{code: "XPF", num: "953", name: "CFP franc (franc Pacifique)",
		Sym: []string{`₣`}, DecNum: 0},
	{code: "XPT", num: "962", name: "Platinum (one troy ounce)",
		Sym: nil, DecNum: -1},
	{code: "XSU", num: "994", name: "SUCRE",
		Sym: nil, DecNum: -1},
	{code: "XTS", num: "963", name: "Code reserved for testing",
		Sym: nil, DecNum: -1},
	{code: "XUA", num: "965", name: "ADB Unit of Account",
		Sym: nil, DecNum: -1},
	{code: "XXX", num: "999", name: "No currency",
		Sym: nil, DecNum: -1},
	{code: "YER", num: "886", name: "Yemeni rial",
		Sym: []string{`ر.ي`}, DecNum: 2},
	{code: "ZAR", num: "710", name: "South African rand",
		Sym: []string{`R`}, DecNum: 2},
	{code: "ZMW", num: "967", name: "Zambian kwacha",
		Sym: []string{`ZK`}, DecNum: 2},
	{code: "ZWL", num: "932", name: "Zimbabwean dollar",
		Sym: []string{`$`}, DecNum: 2},
}
