package tables

import (
	"regexp"
	"strings"
)

var ISO639_1 = make(map[string]struct{})
var ISO639_2 = make(map[string]struct{})
var Alpha = make(map[string]*regexp.Regexp)
var Alnum = make(map[string]*regexp.Regexp)

func init() {
	for _, lang := range languages {
		// set of ISO 639‑2 (two letter codes)
		ISO639_2[lang.c3] = struct{}{}

		// set of ISO 639‑1 (two letter codes)
		if lang.c2 != "--" {
			ISO639_1[lang.c2] = struct{}{}
		}

		abc := strings.ReplaceAll(lang.abc, " ", "")
		num := strings.ReplaceAll(lang.num, " ", "")
		if len(abc) > 0 {
			// Alpha
			rxabc := regexp.MustCompile(`^(?i)[` + abc + `]+$`)
			Alpha[lang.c3] = rxabc
			if lang.c2 != "--" {
				Alpha[lang.c2] = rxabc
			}

			// Alnum
			rxnum := regexp.MustCompile(`^(?i)[` + abc + num + `]+$`)
			Alnum[lang.c3] = rxnum
			if lang.c2 != "--" {
				Alnum[lang.c2] = rxnum
			}
		}

	}
}

// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

type language struct {
	c3   string // ISO 639‑2 (three letter codes)
	c2   string // ISO 639‑1 (two letter codes)
	name string // english name of the language
	abc  string // alphabet of the language
	num  string // numerals of the language
}

var languages = []language{
	{c3: "aar", c2: "aa", name: "Afar",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		num: `0-9`},
	{c3: "abk", c2: "ab", name: "Abkhazian",
		abc: `А Б В Г Ӷ Д Е Ж З Ӡ И К Қ Ҟ Л М Н О П Ԥ Р С Т Ҭ У Ф Х Ҳ Ц Ҵ Ч Ҷ Ҽ Ҿ Ш Ы Ҩ Џ Ь Ә`,
		num: `0-9`},
	{c3: "ace", c2: "--", name: "Achinese", abc: ``, num: ""},
	{c3: "ach", c2: "--", name: "Acoli", abc: ``, num: ""},
	{c3: "ada", c2: "--", name: "Adangme", abc: ``, num: ""},
	{c3: "ady", c2: "--", name: "Adyghe; Adygei", abc: ``, num: ""},
	{c3: "afa", c2: "--", name: "Afro-Asiatic languages", abc: ``, num: ""},
	{c3: "afh", c2: "--", name: "Afrihili", abc: ``, num: ""},
	{c3: "afr", c2: "af", name: "Afrikaans",
		abc: `A Á B C D E É È Ê Ë F G H I Í Î Ï J K L M N O Ó Ô Ö P Q R S T U Ú Û Ü V W X Y Ý Z`,
		num: `0-9`},
	{c3: "ain", c2: "--", name: "Ainu", abc: ``, num: ""},
	{c3: "aka", c2: "ak", name: "Akan",
		abc: `A B D E Ɛ F G H I K L M N O Ɔ P R S T U W Y`,
		num: `0-9`},
	{c3: "akk", c2: "--", name: "Akkadian", abc: ``, num: ""},
	{c3: "amh", c2: "am", name: "Amharic",
		abc: `ሀ ሁ ሂ ሃ ሄ ህ ሆ ለ ሉ ሊ ላ ሌ ል ሎ ሐ ሑ ሒ ሓ ሔ ሕ ሖ መ ሙ ሚ ማ ሜ ም ሞ
		ሠ ሡ ሢ ሣ ሤ ሥ ሦ ረ ሩ ሪ ራ ሬ ር ሮ ሰ ሱ ሲ ሳ ሴ ስ ሶ ሸ ሹ ሺ ሻ ሼ ሽ ሾ ቀ ቁ ቂ ቃ ቄ ቅ ቆ
		ቐ ቑ ቒ ቓ ቔ ቕ ቖ በ ቡ ቢ ባ ቤ ብ ቦ ቨ ቩ ቪ ቫ ቬ ቭ ቮ ተ ቱ ቲ ታ ቴ ት ቶ ቸ ቹ ቺ ቻ ቼ ች ቾ
		ኀ ኁ ኂ ኃ ኄ ኅ ኆ ነ ኑ ኒ ና ኔ ን ኖ ኘ ኙ ኚ ኛ ኜ ኝ ኞ አ ኡ ኢ ኣ ኤ እ ኦ ከ ኩ ኪ ካ ኬ ክ ኮ
		ኸ ኹ ኺ ኻ ኼ ኽ ኾ ወ ዉ ዊ ዋ ዌ ው ዎ ዐ ዑ ዒ ዓ ዔ ዕ ዖ ዘ ዙ ዚ ዛ ዜ ዝ ዞ ዠ ዡ ዢ ዣ ዤ ዥ ዦ
		የ ዩ ዪ ያ ዬ ይ ዮ ደ ዱ ዲ ዳ ዴ ድ ዶ ዸ ዹ ዺ ዻ ዼ ዽ ዾ ጀ ጁ ጂ ጃ ጄ ጅ ጆ ገ ጉ ጊ ጋ ጌ ግ ጎ
		ጘ ጙ ጚ ጛ ጜ ጝ ጞ ጠ ጡ ጢ ጣ ጤ ጥ ጦ ጨ ጩ ጪ ጫ ጬ ጭ ጮ ጰ ጱ ጲ ጳ ጴ ጵ ጶ ጸ ጹ ጺ ጻ ጼ ጽ ጾ
		ፀ ፁ ፂ ፃ ፄ ፅ ፆ ፈ ፉ ፊ ፋ ፌ ፍ ፎ ፐ ፑ ፒ ፓ ፔ ፕ ፖ`,
		num: `፩ ፪ ፫ ፬ ፭ ፮ ፯ ፰ ፱ ፲ ፳ ፴ ፵ ፶ ፷ ፸ ፹ ፺ ፻ ፼`},
	{c3: "ale", c2: "--", name: "Aleut", abc: ``, num: ""},
	{c3: "alg", c2: "--", name: "Algonquian languages", abc: ``, num: ""},
	{c3: "alt", c2: "--", name: "Southern Altai", abc: ``, num: ""},
	{c3: "ang", c2: "--", name: "English, Old (ca.450–1100)", abc: ``, num: ""},
	{c3: "anp", c2: "--", name: "Angika", abc: ``, num: ""},
	{c3: "apa", c2: "--", name: "Apache languages", abc: ``, num: ""},
	{c3: "ara", c2: "ar", name: "Arabic",
		abc: `ء آ أ ؤ إ ئ ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ
		ف ق ك ل م ن ه و ي  ً  ٌ  ٍ  َ  ُ  ِ  ّ  ْ  ٓ  ٔ  ٕ  ٰ  ٱ `,
		num: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ 0-9`},
	{c3: "arc", c2: "--", name: "Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)", abc: ``, num: ""},
	{c3: "arg", c2: "an", name: "Aragonese",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		num: `0-9`},
	{c3: "arn", c2: "--", name: "Mapudungun; Mapuche", abc: ``, num: ""},
	{c3: "arp", c2: "--", name: "Arapaho", abc: ``, num: ""},
	{c3: "art", c2: "--", name: "Artificial languages", abc: ``, num: ""},
	{c3: "arw", c2: "--", name: "Arawak", abc: ``, num: ""},
	{c3: "asm", c2: "as", name: "Assamese",
		abc: `অ অʼআ  ই ঈ উ ঊ ঋ এ ঐ ও ঔ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ
		ড ঢ ণ ত থ দ ধ ন প ফ ব ভ ম য ৰ ল ৱ শ ষ স হ ড় ঢ় য়`,
		num: `০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯`},
	{c3: "ast", c2: "--", name: "Asturian; Bable; Leonese; Asturleonese", abc: ``, num: ""},
	{c3: "ath", c2: "--", name: "Athapascan languages", abc: ``, num: ""},
	{c3: "aus", c2: "--", name: "Australian languages", abc: ``, num: ""},
	{c3: "ava", c2: "av", name: "Avaric",
		abc: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ӏ`,
		num: `0-9`},
	{c3: "ave", c2: "ae", name: "Avestan",
		abc: `𐬀  𐬁  𐬂 𐬃  𐬄 𐬅 𐬆 𐬇 𐬈 𐬉 𐬊 𐬋 𐬌 𐬍 𐬎 𐬏 𐬐 𐬑 𐬒 𐬓 𐬔 𐬕 𐬖 𐬗 𐬘 𐬙 𐬚
		𐬛 𐬜 𐬝 𐬞 𐬟  𐬠 𐬡 𐬢 𐬣 𐬤 𐬥 𐬦 𐬧 𐬨 𐬩 𐬪 𐬫 𐬬 𐬭 𐬯 𐬰 𐬱 𐬲 𐬳  𐬴  𐬵`,
		// According to http://www.heritageinstitute.com/zoroastrianism/pdf/avestanKaranjia.pdf
		// (Teach Yourself Avesta Language) The numerals in Avesta have only word forms.
		// There are no figures to indicate the numerals.
		num: ``},
	{c3: "awa", c2: "--", name: "Awadhi", abc: ``, num: ""},
	{c3: "aym", c2: "ay", name: "Aymara",
		abc: `A Ä C H I Ï J K L M N Ñ P Q R S T U Ü W X Y '`,
		num: `0-9`},
	{c3: "aze", c2: "az", name: "Azerbaijani",
		abc: `A B C Ç D E Ə F G Ğ H X I İ J K Q L M N O Ö P R S Ş T U Ü V Y Z ı`,
		num: `0-9`},
	{c3: "bad", c2: "--", name: "Banda languages", abc: ``, num: ""},
	{c3: "bai", c2: "--", name: "Bamileke languages", abc: ``, num: ""},
	{c3: "bak", c2: "ba", name: "Bashkir", abc: ``},
	{c3: "bal", c2: "--", name: "Baluchi", abc: ``, num: ""},
	{c3: "bam", c2: "bm", name: "Bambara", abc: ``, num: ""},
	{c3: "ban", c2: "--", name: "Balinese", abc: ``, num: ""},
	{c3: "bas", c2: "--", name: "Basa", abc: ``, num: ""},
	{c3: "bat", c2: "--", name: "Baltic languages", abc: ``, num: ""},
	{c3: "bej", c2: "--", name: "Beja; Bedawiyet", abc: ``, num: ""},
	{c3: "bel", c2: "be", name: "Belarusian",
		abc: `А Б В Г Д Е Ё Ж З І Й К Л М Н О П Р С Т У Ў Ф Х Ц Ч Ш Ы Ь Э Ю Я`,
		num: `0-9`},
	{c3: "bem", c2: "--", name: "Bemba", abc: ``, num: ""},
	{c3: "ben", c2: "bn", name: "Bengali", abc: ``, num: ""},
	{c3: "ber", c2: "--", name: "Berber languages", abc: ``, num: ""},
	{c3: "bho", c2: "--", name: "Bhojpuri", abc: ``, num: ""},
	{c3: "bih", c2: "bh", name: "Bihari languages", abc: ``, num: ""},
	{c3: "bik", c2: "--", name: "Bikol", abc: ``, num: ""},
	{c3: "bin", c2: "--", name: "Bini; Edo", abc: ``, num: ""},
	{c3: "bis", c2: "bi", name: "Bislama", abc: ``, num: ""},
	{c3: "bla", c2: "--", name: "Siksika", abc: ``, num: ""},
	{c3: "bnt", c2: "--", name: "Bantu languages", abc: ``, num: ""},
	{c3: "bod", c2: "bo", name: "Tibetan", abc: ``, num: ""},
	{c3: "bos", c2: "bs", name: "Bosnian", abc: ``, num: ""},
	{c3: "bra", c2: "--", name: "Braj", abc: ``, num: ""},
	{c3: "bre", c2: "br", name: "Breton", abc: ``, num: ""},
	{c3: "btk", c2: "--", name: "Batak languages", abc: ``, num: ""},
	{c3: "bua", c2: "--", name: "Buriat", abc: ``, num: ""},
	{c3: "bug", c2: "--", name: "Buginese", abc: ``, num: ""},
	{c3: "bul", c2: "bg", name: "Bulgarian",
		abc: `А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ь Ю Я`,
		num: `0-9`},
	{c3: "byn", c2: "--", name: "Blin; Bilin", abc: ``, num: ""},
	{c3: "cad", c2: "--", name: "Caddo", abc: ``, num: ""},
	{c3: "cai", c2: "--", name: "Central American Indian languages", abc: ``, num: ""},
	{c3: "car", c2: "--", name: "Galibi Carib", abc: ``, num: ""},
	{c3: "cat", c2: "ca", name: "Catalan, Valencian", abc: ``, num: ""},
	{c3: "cau", c2: "--", name: "Caucasian languages", abc: ``, num: ""},
	{c3: "ceb", c2: "--", name: "Cebuano", abc: ``, num: ""},
	{c3: "cel", c2: "--", name: "Celtic languages", abc: ``, num: ""},
	{c3: "ces", c2: "cs", name: "Czech",
		abc: `A Á B C Č D Ď E É Ě F G H I Í J K L M N Ň O Ó P Q R Ř S Š T Ť U Ú Ů V W X Y Ý Z Ž`,
		num: `0-9`},
	{c3: "cha", c2: "ch", name: "Chamorro", abc: ``, num: ""},
	{c3: "chb", c2: "--", name: "Chibcha", abc: ``, num: ""},
	{c3: "che", c2: "ce", name: "Chechen", abc: ``, num: ""},
	{c3: "chg", c2: "--", name: "Chagatai", abc: ``, num: ""},
	{c3: "chk", c2: "--", name: "Chuukese", abc: ``, num: ""},
	{c3: "chm", c2: "--", name: "Mari", abc: ``, num: ""},
	{c3: "chn", c2: "--", name: "Chinook jargon", abc: ``, num: ""},
	{c3: "cho", c2: "--", name: "Choctaw", abc: ``, num: ""},
	{c3: "chp", c2: "--", name: "Chipewyan; Dene Suline", abc: ``, num: ""},
	{c3: "chr", c2: "--", name: "Cherokee", abc: ``, num: ""},
	{c3: "chu", c2: "cu", name: "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", abc: ``, num: ""},
	{c3: "chv", c2: "cv", name: "Chuvash", abc: ``, num: ""},
	{c3: "chy", c2: "--", name: "Cheyenne", abc: ``, num: ""},
	{c3: "cmc", c2: "--", name: "Chamic languages", abc: ``, num: ""},
	{c3: "cnr", c2: "--", name: "Montenegrin",
		// Accoding to https://en.wikipedia.org/wiki/Montenegrin_alphabet
		// Montenegrin seems to be using both the Latin and Cyrillic alphabet.
		abc: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š Ś T U V Z Ž Ź
		А Б В Г Д Ђ Е Ж З З́ И Ј К Л Љ М Н Њ О П Р С С́ Т Ћ У Ф Х Ц Ч Џ Ш`,
		num: `0-9`},
	{c3: "cnr", c2: "--", name: "Montenegrin", abc: ``, num: ""},
	{c3: "cop", c2: "--", name: "Coptic", abc: ``, num: ""},
	{c3: "cor", c2: "kw", name: "Cornish", abc: ``, num: ""},
	{c3: "cos", c2: "co", name: "Corsican", abc: ``, num: ""},
	{c3: "cpe", c2: "--", name: "Creoles and pidgins, English based", abc: ``, num: ""},
	{c3: "cpf", c2: "--", name: "Creoles and pidgins, French-based", abc: ``, num: ""},
	{c3: "cpp", c2: "--", name: "Creoles and pidgins, Portuguese-based", abc: ``, num: ""},
	{c3: "cre", c2: "cr", name: "Cree", abc: ``, num: ""},
	{c3: "crh", c2: "--", name: "Crimean Tatar; Crimean Turkish", abc: ``, num: ""},
	{c3: "crp", c2: "--", name: "Creoles and pidgins", abc: ``, num: ""},
	{c3: "csb", c2: "--", name: "Kashubian", abc: ``, num: ""},
	{c3: "cus", c2: "--", name: "Cushitic languages", abc: ``, num: ""},
	{c3: "cym", c2: "cy", name: "Welsh", abc: ``, num: ""},
	{c3: "dak", c2: "--", name: "Dakota", abc: ``, num: ""},
	{c3: "dan", c2: "da", name: "Danish",
		abc: `A Á B C D E É F G H I Í J K L M N O Ó P Q R S T U Ú V W X Y Ý Z Æ Ǽ Ø Ǿ Å`,
		num: `0-9`},
	{c3: "dar", c2: "--", name: "Dargwa", abc: ``, num: ""},
	{c3: "day", c2: "--", name: "Land Dayak languages", abc: ``, num: ""},
	{c3: "del", c2: "--", name: "Delaware", abc: ``, num: ""},
	{c3: "den", c2: "--", name: "Slave (Athapascan)", abc: ``, num: ""},
	{c3: "deu", c2: "de", name: "German",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ö Ü ß`,
		num: `0-9`},
	{c3: "dgr", c2: "--", name: "Dogrib", abc: ``, num: ""},
	{c3: "din", c2: "--", name: "Dinka", abc: ``, num: ""},
	{c3: "div", c2: "dv", name: "Divehi, Dhivehi, Maldivian", abc: ``, num: ""},
	{c3: "doi", c2: "--", name: "Dogri", abc: ``, num: ""},
	{c3: "dra", c2: "--", name: "Dravidian languages", abc: ``, num: ""},
	{c3: "dsb", c2: "--", name: "Lower Sorbian", abc: ``, num: ""},
	{c3: "dua", c2: "--", name: "Duala", abc: ``, num: ""},
	{c3: "dum", c2: "--", name: "Dutch, Middle (ca. 1050–1350)", abc: ``, num: ""},
	{c3: "dyu", c2: "--", name: "Dyula", abc: ``, num: ""},
	{c3: "dzo", c2: "dz", name: "Dzongkha", abc: ``, num: ""},
	{c3: "efi", c2: "--", name: "Efik", abc: ``, num: ""},
	{c3: "egy", c2: "--", name: "Egyptian (Ancient)", abc: ``, num: ""},
	{c3: "eka", c2: "--", name: "Ekajuk", abc: ``, num: ""},
	{c3: "ell", c2: "el", name: "Greek Modern (1453–)",
		abc: `Α Β Γ Δ Ε Ζ Η Ή Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω Ϊ Ϋ Ά Ώ Έ Ί Ό Ύ ΰ`,
		// NOTE: The "dexia keraia" ( ´ ) and "aristeri keraia" ( ͵ ) are
		// used to indicate the numeric use of letters, for example ͵ΒΙΘʹ
		// represents the number 2019.
		num: `0-9´͵`},
	{c3: "elx", c2: "--", name: "Elamite", abc: ``, num: ""},
	{c3: "eng", c2: "en", name: "English",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		num: `0-9`},
	{c3: "enm", c2: "--", name: "English, Middle (1100–1500)", abc: ``, num: ""},
	{c3: "epo", c2: "eo", name: "Esperanto", abc: ``, num: ""},
	{c3: "est", c2: "et", name: "Estonian", abc: ``, num: ""},
	{c3: "eus", c2: "eu", name: "Basque", abc: ``, num: ""},
	{c3: "ewe", c2: "ee", name: "Ewe", abc: ``, num: ""},
	{c3: "ewo", c2: "--", name: "Ewondo", abc: ``, num: ""},
	{c3: "fan", c2: "--", name: "Fang", abc: ``, num: ""},
	{c3: "fao", c2: "fo", name: "Faroese",
		abc: `A Á B D Ð E F G H I Í J K L M N O Ó P R S T U Ú V Y Ý Æ Ø`,
		num: `0-9`},
	{c3: "fas", c2: "fa", name: "Persian",
		abc: `ء أ ئ ؤ ؤ ا ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی`,
		num: `۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹`},
	{c3: "fat", c2: "--", name: "Fanti", abc: ``, num: ""},
	{c3: "fij", c2: "fj", name: "Fijian", abc: ``, num: ""},
	{c3: "fil", c2: "--", name: "Filipino; Pilipino", abc: ``, num: ""},
	{c3: "fin", c2: "fi", name: "Finnish", abc: ``, num: ""},
	{c3: "fiu", c2: "--", name: "Finno-Ugrian languages", abc: ``, num: ""},
	{c3: "fon", c2: "--", name: "Fon", abc: ``, num: ""},
	{c3: "fra", c2: "fr", name: "French",
		abc: `A À Â Æ B C Ç D E É È Ê Ë F G H I Î Ï J K L M N O Ô Œ P Q R S T U Ù Û Ü V W X Y Ÿ Z`,
		num: `0-9`},
	{c3: "frm", c2: "--", name: "French, Middle (ca. 1400–1600)", abc: ``, num: ""},
	{c3: "fro", c2: "--", name: "French, Old (842–ca. 1400)", abc: ``, num: ""},
	{c3: "frr", c2: "--", name: "Northern Frisian", abc: ``, num: ""},
	{c3: "frs", c2: "--", name: "Eastern Frisian", abc: ``, num: ""},
	{c3: "fry", c2: "fy", name: "Western Frisian", abc: ``, num: ""},
	{c3: "ful", c2: "ff", name: "Fulah", abc: ``, num: ""},
	{c3: "fur", c2: "--", name: "Friulian", abc: ``, num: ""},
	{c3: "gaa", c2: "--", name: "Ga", abc: ``, num: ""},
	{c3: "gay", c2: "--", name: "Gayo", abc: ``, num: ""},
	{c3: "gba", c2: "--", name: "Gbaya", abc: ``, num: ""},
	{c3: "gem", c2: "--", name: "Germanic languages", abc: ``, num: ""},
	{c3: "gez", c2: "--", name: "Geez", abc: ``, num: ""},
	{c3: "gil", c2: "--", name: "Gilbertese", abc: ``, num: ""},
	{c3: "gla", c2: "gd", name: "Gaelic, Scottish Gaelic", abc: ``, num: ""},
	{c3: "gle", c2: "ga", name: "Irish", abc: ``, num: ""},
	{c3: "glg", c2: "gl", name: "Galician", abc: ``, num: ""},
	{c3: "glv", c2: "gv", name: "Manx", abc: ``, num: ""},
	{c3: "gmh", c2: "--", name: "German, Middle High (ca. 1050–1500)", abc: ``, num: ""},
	{c3: "goh", c2: "--", name: "German, Old High (ca. 750–1050)", abc: ``, num: ""},
	{c3: "gon", c2: "--", name: "Gondi", abc: ``, num: ""},
	{c3: "gor", c2: "--", name: "Gorontalo", abc: ``, num: ""},
	{c3: "got", c2: "--", name: "Gothic", abc: ``, num: ""},
	{c3: "grb", c2: "--", name: "Grebo", abc: ``, num: ""},
	{c3: "grc", c2: "--", name: "Greek, Ancient (to 1453)", abc: ``, num: ""},
	{c3: "grn", c2: "gn", name: "Guarani", abc: ``, num: ""},
	{c3: "gsw", c2: "--", name: "Swiss German; Alemannic; Alsatian", abc: ``, num: ""},
	{c3: "guj", c2: "gu", name: "Gujarati", abc: ``, num: ""},
	{c3: "gwi", c2: "--", name: "Gwich'in", abc: ``, num: ""},
	{c3: "hai", c2: "--", name: "Haida", abc: ``, num: ""},
	{c3: "hat", c2: "ht", name: "Haitian, Haitian Creole", abc: ``, num: ""},
	{c3: "hau", c2: "ha", name: "Hausa (Hausa)", abc: ``, num: ""},
	{c3: "haw", c2: "--", name: "Hawaiian", abc: ``, num: ""},
	{c3: "hbs", c2: "sh", name: "Serbo-Croatian",
		abc: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`,
		num: `0-9`},
	{c3: "heb", c2: "he", name: "Hebrew",
		abc: `א ב ג ד ה ו ז ח ט י כ ך ל מ ם נ ן ס ע פ ף צ ץ ק ר ש ת`,
		// NOTE: The "geresh" ( ׳ ) is used to denote a single-digit Hebrew numeral.
		// The "gershayim" ( ״ ) is used to indicate a multi-digit Hebrew numeral.
		num: `0-9׳״`},
	{c3: "her", c2: "hz", name: "Herero", abc: ``, num: ""},
	{c3: "hil", c2: "--", name: "Hiligaynon", abc: ``, num: ""},
	{c3: "him", c2: "--", name: "Himachali languages; Pahari languages", abc: ``, num: ""},
	{c3: "hin", c2: "hi", name: "Hindi", abc: ``, num: ""},
	{c3: "hit", c2: "--", name: "Hittite", abc: ``, num: ""},
	{c3: "hmn", c2: "--", name: "Hmong; Mong", abc: ``, num: ""},
	{c3: "hmo", c2: "ho", name: "Hiri Motu", abc: ``, num: ""},
	{c3: "hrv", c2: "hr", name: "Croatian", abc: ``, num: ""},
	{c3: "hsb", c2: "--", name: "Upper Sorbian", abc: ``, num: ""},
	{c3: "hun", c2: "hu", name: "Hungarian",
		abc: `A Á B C D E É F G H I Í J K L M N O Ó Ö Ő P Q R S T U Ú Ü Ű V W X Y Z`,
		num: `0-9`},
	{c3: "hup", c2: "--", name: "Hupa", abc: ``, num: ""},
	{c3: "hye", c2: "hy", name: "Armenian", abc: ``, num: ""},
	{c3: "iba", c2: "--", name: "Iban", abc: ``, num: ""},
	{c3: "ibo", c2: "ig", name: "Igbo", abc: ``, num: ""},
	{c3: "ido", c2: "io", name: "Ido", abc: ``, num: ""},
	{c3: "iii", c2: "ii", name: "Sichuan Yi, Nuosu", abc: ``, num: ""},
	{c3: "ijo", c2: "--", name: "Ijo languages", abc: ``, num: ""},
	{c3: "iku", c2: "iu", name: "Inuktitut", abc: ``, num: ""},
	{c3: "ile", c2: "ie", name: "Interlingue, Occidental", abc: ``, num: ""},
	{c3: "ilo", c2: "--", name: "Iloko", abc: ``, num: ""},
	{c3: "ina", c2: "ia", name: "Interlingua (International Auxiliary Language Association)", abc: ``, num: ""},
	{c3: "inc", c2: "--", name: "Indic languages", abc: ``, num: ""},
	{c3: "ind", c2: "id", name: "Indonesian", abc: ``, num: ""},
	{c3: "ine", c2: "--", name: "Indo-European languages", abc: ``, num: ""},
	{c3: "inh", c2: "--", name: "Ingush", abc: ``, num: ""},
	{c3: "ipk", c2: "ik", name: "Inupiaq", abc: ``, num: ""},
	{c3: "ira", c2: "--", name: "Iranian languages", abc: ``, num: ""},
	{c3: "iro", c2: "--", name: "Iroquoian languages", abc: ``, num: ""},
	{c3: "isl", c2: "is", name: "Icelandic",
		abc: `A Á B D Ð E É F G H I Í J K L M N O Ó P R S T U Ú V X Y Ý Þ Æ Ö`,
		num: `0-9`},
	{c3: "ita", c2: "it", name: "Italian",
		abc: `A À B C D E È É F G H I Ì Í Î L M N O Ò Ó P Q R S T U Ù Ú V Z`,
		num: `0-9`},
	{c3: "jav", c2: "jv", name: "Javanese", abc: ``, num: ""},
	{c3: "jbo", c2: "--", name: "Lojban", abc: ``, num: ""},
	{c3: "jpn", c2: "ja", name: "Japanese", abc: ``, num: ""},
	{c3: "jpr", c2: "--", name: "Judeo-Persian", abc: ``, num: ""},
	{c3: "jrb", c2: "--", name: "Judeo-Arabic", abc: ``, num: ""},
	{c3: "kaa", c2: "--", name: "Kara-Kalpak", abc: ``, num: ""},
	{c3: "kab", c2: "--", name: "Kabyle", abc: ``, num: ""},
	{c3: "kac", c2: "--", name: "Kachin; Jingpho", abc: ``, num: ""},
	{c3: "kal", c2: "kl", name: "Kalaallisut, Greenlandic", abc: ``, num: ""},
	{c3: "kam", c2: "--", name: "Kamba", abc: ``, num: ""},
	{c3: "kan", c2: "kn", name: "Kannada", abc: ``, num: ""},
	{c3: "kar", c2: "--", name: "Karen languages", abc: ``, num: ""},
	{c3: "kas", c2: "ks", name: "Kashmiri", abc: ``, num: ""},
	{c3: "kat", c2: "ka", name: "Georgian", abc: ``, num: ""},
	{c3: "kau", c2: "kr", name: "Kanuri", abc: ``, num: ""},
	{c3: "kaw", c2: "--", name: "Kawi", abc: ``, num: ""},
	{c3: "kaz", c2: "kk", name: "Kazakh", abc: ``, num: ""},
	{c3: "kbd", c2: "--", name: "Kabardian", abc: ``, num: ""},
	{c3: "kha", c2: "--", name: "Khasi", abc: ``, num: ""},
	{c3: "khi", c2: "--", name: "Khoisan languages", abc: ``, num: ""},
	{c3: "khm", c2: "km", name: "Central Khmer", abc: ``, num: ""},
	{c3: "kho", c2: "--", name: "Khotanese; Sakan", abc: ``, num: ""},
	{c3: "kik", c2: "ki", name: "Kikuyu, Gikuyu", abc: ``, num: ""},
	{c3: "kin", c2: "rw", name: "Kinyarwanda", abc: ``, num: ""},
	{c3: "kir", c2: "ky", name: "Kirghiz, Kyrgyz", abc: ``, num: ""},
	{c3: "kmb", c2: "--", name: "Kimbundu", abc: ``, num: ""},
	{c3: "kok", c2: "--", name: "Konkani", abc: ``, num: ""},
	{c3: "kom", c2: "kv", name: "Komi", abc: ``, num: ""},
	{c3: "kon", c2: "kg", name: "Kongo", abc: ``, num: ""},
	{c3: "kor", c2: "ko", name: "Korean", abc: ``, num: ""},
	{c3: "kos", c2: "--", name: "Kosraean", abc: ``, num: ""},
	{c3: "kpe", c2: "--", name: "Kpelle", abc: ``, num: ""},
	{c3: "krc", c2: "--", name: "Karachay-Balkar", abc: ``, num: ""},
	{c3: "krl", c2: "--", name: "Karelian", abc: ``, num: ""},
	{c3: "kro", c2: "--", name: "Kru languages", abc: ``, num: ""},
	{c3: "kru", c2: "--", name: "Kurukh", abc: ``, num: ""},
	{c3: "kua", c2: "kj", name: "Kuanyama, Kwanyama", abc: ``, num: ""},
	{c3: "kum", c2: "--", name: "Kumyk", abc: ``, num: ""},
	{c3: "kur", c2: "ku", name: "Kurdish",
		abc: `ئ ا ب پ ت ج چ ح خ د ر ڕ ز ژ س ش ع غ ف ڤ ق ک گ ل ڵ م ن ھ ە و ۆ ؤ ی ێ ڒ ڔ ڶ ڷ ۊ ٚ  `,
		num: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩`},
	{c3: "kut", c2: "--", name: "Kutenai", abc: ``, num: ""},
	{c3: "lad", c2: "--", name: "Ladino", abc: ``, num: ""},
	{c3: "lah", c2: "--", name: "Lahnda", abc: ``, num: ""},
	{c3: "lam", c2: "--", name: "Lamba", abc: ``, num: ""},
	{c3: "lao", c2: "lo", name: "Lao", abc: ``, num: ""},
	{c3: "lat", c2: "la", name: "Latin", abc: ``, num: ""},
	{c3: "lav", c2: "lv", name: "Latvian", abc: ``, num: ""},
	{c3: "lez", c2: "--", name: "Lezghian", abc: ``, num: ""},
	{c3: "lim", c2: "li", name: "Limburgan, Limburger, Limburgish", abc: ``, num: ""},
	{c3: "lin", c2: "ln", name: "Lingala", abc: ``, num: ""},
	{c3: "lit", c2: "lt", name: "Lithuanian", abc: ``, num: ""},
	{c3: "lol", c2: "--", name: "Mongo", abc: ``, num: ""},
	{c3: "loz", c2: "--", name: "Lozi", abc: ``, num: ""},
	{c3: "ltz", c2: "lb", name: "Luxembourgish, Letzeburgesch", abc: ``, num: ""},
	{c3: "lua", c2: "--", name: "Luba-Lulua", abc: ``, num: ""},
	{c3: "lub", c2: "lu", name: "Luba-Katanga", abc: ``, num: ""},
	{c3: "lug", c2: "lg", name: "Ganda", abc: ``, num: ""},
	{c3: "lui", c2: "--", name: "Luiseno", abc: ``, num: ""},
	{c3: "lun", c2: "--", name: "Lunda", abc: ``, num: ""},
	{c3: "luo", c2: "--", name: "Luo (Kenya and Tanzania)", abc: ``, num: ""},
	{c3: "lus", c2: "--", name: "Lushai", abc: ``, num: ""},
	{c3: "mad", c2: "--", name: "Madurese", abc: ``, num: ""},
	{c3: "mag", c2: "--", name: "Magahi", abc: ``, num: ""},
	{c3: "mah", c2: "mh", name: "Marshallese", abc: ``, num: ""},
	{c3: "mai", c2: "--", name: "Maithili", abc: ``, num: ""},
	{c3: "mak", c2: "--", name: "Makasar", abc: ``, num: ""},
	{c3: "mal", c2: "ml", name: "Malayalam", abc: ``, num: ""},
	{c3: "man", c2: "--", name: "Mandingo", abc: ``, num: ""},
	{c3: "map", c2: "--", name: "Austronesian languages", abc: ``, num: ""},
	{c3: "mar", c2: "mr", name: "Marathi", abc: ``, num: ""},
	{c3: "mas", c2: "--", name: "Masai", abc: ``, num: ""},
	{c3: "mdf", c2: "--", name: "Moksha", abc: ``, num: ""},
	{c3: "mdr", c2: "--", name: "Mandar", abc: ``, num: ""},
	{c3: "men", c2: "--", name: "Mende", abc: ``, num: ""},
	{c3: "mga", c2: "--", name: "Irish, Middle (900–1200)", abc: ``, num: ""},
	{c3: "mic", c2: "--", name: "Mi'kmaq; Micmac", abc: ``, num: ""},
	{c3: "min", c2: "--", name: "Minangkabau", abc: ``, num: ""},
	{c3: "mis", c2: "--", name: "Uncoded languages", abc: ``, num: ""},
	{c3: "mkd", c2: "mk", name: "Macedonian",
		abc: `А Б В Г Д Ѓ Е Ж З Ѕ И Ј К Л Љ М Н Њ О П Р С Т Ќ У Ф Х Ц Ч Џ Ш`,
		num: `0-9`},
	{c3: "mkh", c2: "--", name: "Mon-Khmer languages", abc: ``, num: ""},
	{c3: "mlg", c2: "mg", name: "Malagasy", abc: ``, num: ""},
	{c3: "mlt", c2: "mt", name: "Maltese", abc: ``, num: ""},
	{c3: "mnc", c2: "--", name: "Manchu", abc: ``, num: ""},
	{c3: "mni", c2: "--", name: "Manipuri", abc: ``, num: ""},
	{c3: "mno", c2: "--", name: "Manobo languages", abc: ``, num: ""},
	{c3: "moh", c2: "--", name: "Mohawk", abc: ``, num: ""},
	{c3: "mon", c2: "mn", name: "Mongolian", abc: ``, num: ""},
	{c3: "mos", c2: "--", name: "Mossi", abc: ``, num: ""},
	{c3: "mri", c2: "mi", name: "Maori", abc: ``, num: ""},
	{c3: "msa", c2: "ms", name: "Malay", abc: ``, num: ""},
	{c3: "mul", c2: "--", name: "Multiple languages", abc: ``, num: ""},
	{c3: "mun", c2: "--", name: "Munda languages", abc: ``, num: ""},
	{c3: "mus", c2: "--", name: "Creek", abc: ``, num: ""},
	{c3: "mwl", c2: "--", name: "Mirandese", abc: ``, num: ""},
	{c3: "mwr", c2: "--", name: "Marwari", abc: ``, num: ""},
	{c3: "mya", c2: "my", name: "Burmese", abc: ``, num: ""},
	{c3: "myn", c2: "--", name: "Mayan languages", abc: ``, num: ""},
	{c3: "myv", c2: "--", name: "Erzya", abc: ``, num: ""},
	{c3: "nah", c2: "--", name: "Nahuatl languages", abc: ``, num: ""},
	{c3: "nai", c2: "--", name: "North American Indian languages", abc: ``, num: ""},
	{c3: "nap", c2: "--", name: "Neapolitan", abc: ``, num: ""},
	{c3: "nau", c2: "na", name: "Nauru", abc: ``, num: ""},
	{c3: "nav", c2: "nv", name: "Navajo, Navaho", abc: ``, num: ""},
	{c3: "nbl", c2: "nr", name: "South Ndebele", abc: ``, num: ""},
	{c3: "nde", c2: "nd", name: "North Ndebele", abc: ``, num: ""},
	{c3: "ndo", c2: "ng", name: "Ndonga", abc: ``, num: ""},
	{c3: "nds", c2: "--", name: "Low German; Low Saxon; German, Low; Saxon, Low", abc: ``, num: ""},
	{c3: "nep", c2: "ne", name: "Nepali", abc: ``, num: ""},
	{c3: "new", c2: "--", name: "Nepal Bhasa; Newari", abc: ``, num: ""},
	{c3: "nia", c2: "--", name: "Nias", abc: ``, num: ""},
	{c3: "nic", c2: "--", name: "Niger-Kordofanian languages", abc: ``, num: ""},
	{c3: "niu", c2: "--", name: "Niuean", abc: ``, num: ""},
	{c3: "nld", c2: "nl", name: "Dutch, Flemish",
		abc: `A Á Ä B C D E É Ë F G H I Í Ï J J́ K L M N O Ó Ö P Q R S T U Ú Ü V W X Y Ý Z`,
		num: `0-9`},
	{c3: "nno", c2: "nn", name: "Norwegian Nynorsk",
		abc: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		num: `0-9`},
	{c3: "nob", c2: "nb", name: "Norwegian Bokmål",
		abc: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		num: `0-9`},
	{c3: "nog", c2: "--", name: "Nogai", abc: ``, num: ""},
	{c3: "non", c2: "--", name: "Norse, Old", abc: ``, num: ""},
	{c3: "nor", c2: "no", name: "Norwegian",
		abc: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		num: `0-9`},
	{c3: "nqo", c2: "--", name: "N'Ko", abc: ``, num: ""},
	{c3: "nso", c2: "--", name: "Pedi; Sepedi; Northern Sotho", abc: ``, num: ""},
	{c3: "nub", c2: "--", name: "Nubian languages", abc: ``, num: ""},
	{c3: "nwc", c2: "--", name: "Classical Newari; Old Newari; Classical Nepal Bhasa", abc: ``, num: ""},
	{c3: "nya", c2: "ny", name: "Chichewa, Chewa, Nyanja", abc: ``, num: ""},
	{c3: "nym", c2: "--", name: "Nyamwezi", abc: ``, num: ""},
	{c3: "nyn", c2: "--", name: "Nyankole", abc: ``, num: ""},
	{c3: "nyo", c2: "--", name: "Nyoro", abc: ``, num: ""},
	{c3: "nzi", c2: "--", name: "Nzima", abc: ``, num: ""},
	{c3: "oci", c2: "oc", name: "Occitan", abc: ``, num: ""},
	{c3: "oji", c2: "oj", name: "Ojibwa", abc: ``, num: ""},
	{c3: "ori", c2: "or", name: "Oriya", abc: ``, num: ""},
	{c3: "orm", c2: "om", name: "Oromo", abc: ``, num: ""},
	{c3: "osa", c2: "--", name: "Osage", abc: ``, num: ""},
	{c3: "oss", c2: "os", name: "Ossetian, Ossetic", abc: ``, num: ""},
	{c3: "ota", c2: "--", name: "Turkish, Ottoman (1500–1928)", abc: ``, num: ""},
	{c3: "oto", c2: "--", name: "Otomian languages", abc: ``, num: ""},
	{c3: "paa", c2: "--", name: "Papuan languages", abc: ``, num: ""},
	{c3: "pag", c2: "--", name: "Pangasinan", abc: ``, num: ""},
	{c3: "pal", c2: "--", name: "Pahlavi", abc: ``, num: ""},
	{c3: "pam", c2: "--", name: "Pampanga; Kapampangan", abc: ``, num: ""},
	{c3: "pan", c2: "pa", name: "Punjabi, Panjabi", abc: ``, num: ""},
	{c3: "pap", c2: "--", name: "Papiamento", abc: ``, num: ""},
	{c3: "pau", c2: "--", name: "Palauan", abc: ``, num: ""},
	{c3: "peo", c2: "--", name: "Persian, Old (ca. 600–400 B.C.)", abc: ``, num: ""},
	{c3: "phi", c2: "--", name: "Philippine languages", abc: ``, num: ""},
	{c3: "phn", c2: "--", name: "Phoenician", abc: ``, num: ""},
	{c3: "pli", c2: "pi", name: "Pali", abc: ``, num: ""},
	{c3: "pol", c2: "pl", name: "Polish",
		abc: `A Ą B C Ć D E Ę F G H I J K L Ł M N Ń O Ó P Q R S Ś T U V W X Y Z Ź Ż`,
		num: `0-9`},
	{c3: "pon", c2: "--", name: "Pohnpeian", abc: ``, num: ""},
	{c3: "por", c2: "pt", name: "Portuguese",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á Â Ã À Ä Ç É Ê Ë Í Ï Ó Ô Õ Ú Ü`,
		num: `0-9`},
	{c3: "pra", c2: "--", name: "Prakrit languages", abc: ``, num: ""},
	{c3: "pro", c2: "--", name: "Provençal, Old (to 1500); Old Occitan (to 1500)", abc: ``, num: ""},
	{c3: "pus", c2: "ps", name: "Pashto, Pushto", abc: ``, num: ""},
	{c3: "que", c2: "qu", name: "Quechua", abc: ``, num: ""},
	{c3: "raj", c2: "--", name: "Rajasthani", abc: ``, num: ""},
	{c3: "rap", c2: "--", name: "Rapanui", abc: ``, num: ""},
	{c3: "rar", c2: "--", name: "Rarotongan; Cook Islands Maori", abc: ``, num: ""},
	{c3: "roa", c2: "--", name: "Romance languages", abc: ``, num: ""},
	{c3: "roh", c2: "rm", name: "Romansh", abc: ``, num: ""},
	{c3: "rom", c2: "--", name: "Romany", abc: ``, num: ""},
	{c3: "ron", c2: "ro", name: "Romanian, Moldavian, Moldovan", abc: ``, num: ""},
	{c3: "run", c2: "rn", name: "Rundi", abc: ``, num: ""},
	{c3: "rup", c2: "--", name: "Aromanian; Arumanian; Macedo-Romanian", abc: ``, num: ""},
	{c3: "rus", c2: "ru", name: "Russian",
		abc: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я`,
		num: `0-9`},
	{c3: "sad", c2: "--", name: "Sandawe", abc: ``, num: ""},
	{c3: "sag", c2: "sg", name: "Sango", abc: ``, num: ""},
	{c3: "sah", c2: "--", name: "Yakut", abc: ``, num: ""},
	{c3: "sai", c2: "--", name: "South American Indian languages", abc: ``, num: ""},
	{c3: "sal", c2: "--", name: "Salishan languages", abc: ``, num: ""},
	{c3: "sam", c2: "--", name: "Samaritan Aramaic", abc: ``, num: ""},
	{c3: "san", c2: "sa", name: "Sanskrit", abc: ``, num: ""},
	{c3: "sas", c2: "--", name: "Sasak", abc: ``, num: ""},
	{c3: "sat", c2: "--", name: "Santali", abc: ``, num: ""},
	{c3: "scn", c2: "--", name: "Sicilian", abc: ``, num: ""},
	{c3: "sco", c2: "--", name: "Scots", abc: ``, num: ""},
	{c3: "sel", c2: "--", name: "Selkup", abc: ``, num: ""},
	{c3: "sem", c2: "--", name: "Semitic languages", abc: ``, num: ""},
	{c3: "sga", c2: "--", name: "Irish, Old (to 900)", abc: ``, num: ""},
	{c3: "sgn", c2: "--", name: "Sign Languages", abc: ``, num: ""},
	{c3: "shn", c2: "--", name: "Shan", abc: ``, num: ""},
	{c3: "sid", c2: "--", name: "Sidamo", abc: ``, num: ""},
	{c3: "sin", c2: "si", name: "Sinhala, Sinhalese", abc: ``, num: ""},
	{c3: "sio", c2: "--", name: "Siouan languages", abc: ``, num: ""},
	{c3: "sit", c2: "--", name: "Sino-Tibetan languages", abc: ``, num: ""},
	{c3: "sla", c2: "--", name: "Slavic languages", abc: ``, num: ""},
	{c3: "slk", c2: "sk", name: "Slovak",
		abc: `A Á Ä B C Č D Ď E É F G H I Í J K L Ĺ Ľ M N Ň O Ó Ô P Q R Ŕ S Š T Ť U Ú V W X Y Ý Z Ž`,
		num: `0-9`},
	{c3: "slv", c2: "sl", name: "Slovenian",
		abc: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`,
		num: `0-9`},
	{c3: "sma", c2: "--", name: "Southern Sami", abc: ``, num: ""},
	{c3: "sme", c2: "se", name: "Northern Sami", abc: ``, num: ""},
	{c3: "smi", c2: "--", name: "Sami languages", abc: ``, num: ""},
	{c3: "smj", c2: "--", name: "Lule Sami", abc: ``, num: ""},
	{c3: "smn", c2: "--", name: "Inari Sami", abc: ``, num: ""},
	{c3: "smo", c2: "sm", name: "Samoan", abc: ``, num: ""},
	{c3: "sms", c2: "--", name: "Skolt Sami", abc: ``, num: ""},
	{c3: "sna", c2: "sn", name: "Shona", abc: ``, num: ""},
	{c3: "snd", c2: "sd", name: "Sindhi", abc: ``, num: ""},
	{c3: "snk", c2: "--", name: "Soninke", abc: ``, num: ""},
	{c3: "sog", c2: "--", name: "Sogdian", abc: ``, num: ""},
	{c3: "som", c2: "so", name: "Somali", abc: ``, num: ""},
	{c3: "son", c2: "--", name: "Songhai languages", abc: ``, num: ""},
	{c3: "sot", c2: "st", name: "Southern Sotho", abc: ``, num: ""},
	{c3: "spa", c2: "es", name: "Spanish, Castilian",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ñ Ó Ú Ü`,
		num: `0-9`},
	{c3: "sqi", c2: "sq", name: "Albanian", abc: ``, num: ""},
	{c3: "srd", c2: "sc", name: "Sardinian", abc: ``, num: ""},
	{c3: "srn", c2: "--", name: "Sranan Tongo", abc: ``, num: ""},
	{c3: "srp", c2: "sr", name: "Serbian",
		abc: `А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш`,
		num: `0-9`},
	{c3: "srr", c2: "--", name: "Serer", abc: ``, num: ""},
	{c3: "ssa", c2: "--", name: "Nilo-Saharan languages", abc: ``, num: ""},
	{c3: "ssw", c2: "ss", name: "Swati", abc: ``, num: ""},
	{c3: "suk", c2: "--", name: "Sukuma", abc: ``, num: ""},
	{c3: "sun", c2: "su", name: "Sundanese", abc: ``, num: ""},
	{c3: "sus", c2: "--", name: "Susu", abc: ``, num: ""},
	{c3: "sux", c2: "--", name: "Sumerian", abc: ``, num: ""},
	{c3: "swa", c2: "sw", name: "Swahili", abc: ``, num: ""},
	{c3: "swe", c2: "sv", name: "Swedish",
		abc: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Å Ä Ö`,
		num: `0-9`},
	{c3: "syc", c2: "--", name: "Classical Syriac", abc: ``, num: ""},
	{c3: "syr", c2: "--", name: "Syriac", abc: ``, num: ""},
	{c3: "tah", c2: "ty", name: "Tahitian", abc: ``, num: ""},
	{c3: "tai", c2: "--", name: "Tai languages", abc: ``, num: ""},
	{c3: "tam", c2: "ta", name: "Tamil", abc: ``, num: ""},
	{c3: "tat", c2: "tt", name: "Tatar", abc: ``, num: ""},
	{c3: "tel", c2: "te", name: "Telugu", abc: ``, num: ""},
	{c3: "tem", c2: "--", name: "Timne", abc: ``, num: ""},
	{c3: "ter", c2: "--", name: "Tereno", abc: ``, num: ""},
	{c3: "tet", c2: "--", name: "Tetum", abc: ``, num: ""},
	{c3: "tgk", c2: "tg", name: "Tajik", abc: ``, num: ""},
	{c3: "tgl", c2: "tl", name: "Tagalog", abc: ``, num: ""},
	{c3: "tha", c2: "th", name: "Thai",
		abc: `ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ
		ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ ฯ ะ ั า ำ  ิ  ี  ึ  ื  ุ  ู  ฺ เ แ โ ใ ๅ ไ  ็ ่ ้ ๊ ๋ ์ ํ ๎`,
		num: `๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙`},
	{c3: "tig", c2: "--", name: "Tigre", abc: ``, num: ""},
	{c3: "tir", c2: "ti", name: "Tigrinya", abc: ``, num: ""},
	{c3: "tiv", c2: "--", name: "Tiv", abc: ``, num: ""},
	{c3: "tkl", c2: "--", name: "Tokelau", abc: ``, num: ""},
	{c3: "tlh", c2: "--", name: "Klingon; tlhIngan-Hol", abc: ``, num: ""},
	{c3: "tli", c2: "--", name: "Tlingit", abc: ``, num: ""},
	{c3: "tmh", c2: "--", name: "Tamashek", abc: ``, num: ""},
	{c3: "tog", c2: "--", name: "Tonga (Nyasa)", abc: ``, num: ""},
	{c3: "ton", c2: "to", name: "Tonga (Tonga Islands)", abc: ``, num: ""},
	{c3: "tpi", c2: "--", name: "Tok Pisin", abc: ``, num: ""},
	{c3: "tsi", c2: "--", name: "Tsimshian", abc: ``, num: ""},
	{c3: "tsn", c2: "tn", name: "Tswana", abc: ``, num: ""},
	{c3: "tso", c2: "ts", name: "Tsonga", abc: ``, num: ""},
	{c3: "tuk", c2: "tk", name: "Turkmen", abc: ``, num: ""},
	{c3: "tum", c2: "--", name: "Tumbuka", abc: ``, num: ""},
	{c3: "tup", c2: "--", name: "Tupi languages", abc: ``, num: ""},
	{c3: "tur", c2: "tr", name: "Turkish",
		abc: `A Â B C Ç D E F G Ğ H I İ Î J K L M N O Ö P R S Ş T U Ü Û V Y Z Q W X ı`,
		num: `0-9`},
	{c3: "tut", c2: "--", name: "Altaic languages", abc: ``, num: ""},
	{c3: "tvl", c2: "--", name: "Tuvalu", abc: ``, num: ""},
	{c3: "twi", c2: "tw", name: "Twi", abc: ``, num: ""},
	{c3: "tyv", c2: "--", name: "Tuvinian", abc: ``, num: ""},
	{c3: "udm", c2: "--", name: "Udmurt", abc: ``, num: ""},
	{c3: "uga", c2: "--", name: "Ugaritic", abc: ``, num: ""},
	{c3: "uig", c2: "ug", name: "Uighur, Uyghur", abc: ``, num: ""},
	{c3: "ukr", c2: "uk", name: "Ukrainian",
		abc: `А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я`,
		num: `0-9`},
	{c3: "umb", c2: "--", name: "Umbundu", abc: ``, num: ""},
	{c3: "und", c2: "--", name: "Undetermined", abc: ``, num: ""},
	{c3: "urd", c2: "ur", name: "Urdu", abc: ``, num: ""},
	{c3: "uzb", c2: "uz", name: "Uzbek", abc: ``, num: ""},
	{c3: "vai", c2: "--", name: "Vai", abc: ``, num: ""},
	{c3: "ven", c2: "ve", name: "Venda", abc: ``, num: ""},
	{c3: "vie", c2: "vi", name: "Vietnamese",
		abc: `A Ă Â À Ằ Ầ Ả Ẳ Ẩ Ã Ẵ Ẫ Á Ắ Ấ Ạ Ặ Ậ B C D Đ E Ê È Ề Ẻ Ể Ẽ
		Ễ É Ế Ẹ Ệ G H I Ì Ỉ Ĩ Í Ị K L M N O Ô Ơ Ò Ồ Ờ Ỏ Ổ Ở Õ Ỗ Ỡ Ó Ố Ớ
		Ọ Ộ Ợ P Q R S T U Ư Ù Ừ Ủ Ử Ũ Ữ Ú Ứ Ụ Ự V X Y Ỳ Ỷ Ỹ Ý Ỵ`,
		num: `0-9`},
	{c3: "vol", c2: "vo", name: "Volapük", abc: ``, num: ""},
	{c3: "vot", c2: "--", name: "Votic", abc: ``, num: ""},
	{c3: "wak", c2: "--", name: "Wakashan languages", abc: ``, num: ""},
	{c3: "wal", c2: "--", name: "Wolaitta; Wolaytta", abc: ``, num: ""},
	{c3: "war", c2: "--", name: "Waray", abc: ``, num: ""},
	{c3: "was", c2: "--", name: "Washo", abc: ``, num: ""},
	{c3: "wen", c2: "--", name: "sorbian languages",
		abc: `A B C Č Ć D E Ě F G H I J K Ł L M N Ń O Ó P R Ř Ŕ S Š Ś T U W Y Z Ž Ź`,
		num: `0-9`},
	{c3: "wln", c2: "wa", name: "Walloon", abc: ``, num: ""},
	{c3: "wol", c2: "wo", name: "Wolof", abc: ``, num: ""},
	{c3: "xal", c2: "--", name: "Kalmyk; Oirat", abc: ``, num: ""},
	{c3: "xho", c2: "xh", name: "Xhosa", abc: ``, num: ""},
	{c3: "yao", c2: "--", name: "Yao", abc: ``, num: ""},
	{c3: "yap", c2: "--", name: "Yapese", abc: ``, num: ""},
	{c3: "yid", c2: "yi", name: "Yiddish", abc: ``, num: ""},
	{c3: "yor", c2: "yo", name: "Yoruba", abc: ``, num: ""},
	{c3: "ypk", c2: "--", name: "Yupik languages", abc: ``, num: ""},
	{c3: "zap", c2: "--", name: "Zapotec", abc: ``, num: ""},
	{c3: "zbl", c2: "--", name: "Blissymbols; Blissymbolics; Bliss", abc: ``, num: ""},
	{c3: "zen", c2: "--", name: "Zenaga", abc: ``, num: ""},
	{c3: "zgh", c2: "--", name: "Standard Moroccan Tamazight", abc: ``, num: ""},
	{c3: "zha", c2: "za", name: "Zhuang, Chuang", abc: ``, num: ""},
	{c3: "zho", c2: "zh", name: "Chinese", abc: ``, num: ""},
	{c3: "znd", c2: "--", name: "Zande languages", abc: ``, num: ""},
	{c3: "zul", c2: "zu", name: "Zulu", abc: ``, num: ""},
	{c3: "zun", c2: "--", name: "Zuni", abc: ``, num: ""},
	{c3: "zxx", c2: "--", name: "No linguistic content; Not applicable", abc: ``, num: ""},
	{c3: "zza", c2: "--", name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", abc: ``, num: ""},
}
