package tables

import (
	"regexp"
	"strings"
)

var ISO_639_1 = make(map[string]Language)
var ISO_639_2 = make(map[string]Language)
var Alpha = make(map[string]*regexp.Regexp)
var Alnum = make(map[string]*regexp.Regexp)

func init() {
	for _, lang := range languages {
		// set of ISO 639‑2 (three letter codes)
		ISO_639_2[lang.ISO_639_2] = lang

		// set of ISO 639‑1 (two letter codes)
		if lang.ISO_639_1 != "" {
			ISO_639_1[lang.ISO_639_1] = lang
		}

		abc := strings.ReplaceAll(lang.Alphabet, " ", "")
		num := strings.ReplaceAll(lang.Numerals, " ", "")
		if len(abc) > 0 {
			// Alpha
			rxabc := regexp.MustCompile(`^(?i)[` + abc + `]+$`)
			Alpha[lang.ISO_639_2] = rxabc
			if lang.ISO_639_1 != "" {
				Alpha[lang.ISO_639_1] = rxabc
			}

			// Alnum
			rxnum := regexp.MustCompile(`^(?i)[` + abc + num + `]+$`)
			Alnum[lang.ISO_639_2] = rxnum
			if lang.ISO_639_1 != "" {
				Alnum[lang.ISO_639_1] = rxnum
			}
		}

	}
}

// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

type Language struct {
	ISO_639_2 string // ISO 639‑2 (three letter codes)
	ISO_639_1 string // ISO 639‑1 (two letter codes)
	Name      string // english name of the language
	Alphabet  string // alphabet of the language
	Numerals  string // numerals of the language
	Decimal   rune   // the decimal separator of the language
}

var languages = []Language{
	{ISO_639_2: "aar", ISO_639_1: "aa", Name: "Afar", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`, Numerals: `0-9`},
	{ISO_639_2: "abk", ISO_639_1: "ab", Name: "Abkhazian", Alphabet: `А Б В Г Ӷ Д Е Ж З Ӡ И К Қ Ҟ Л М Н О П Ԥ Р С Т Ҭ У Ф Х Ҳ Ц Ҵ Ч Ҷ Ҽ Ҿ Ш Ы Ҩ Џ Ь Ә`, Numerals: `0-9`},
	{ISO_639_2: "ace", ISO_639_1: "", Name: "Achinese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ach", ISO_639_1: "", Name: "Acoli", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ada", ISO_639_1: "", Name: "Adangme", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ady", ISO_639_1: "", Name: "Adyghe; Adygei", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "afa", ISO_639_1: "", Name: "Afro-Asiatic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "afh", ISO_639_1: "", Name: "Afrihili", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "afr", ISO_639_1: "af", Name: "Afrikaans", Alphabet: `A Á B C D E É È Ê Ë F G H I Í Î Ï J K L M N O Ó Ô Ö P Q R S T U Ú Û Ü V W X Y Ý Z`, Numerals: `0-9`},
	{ISO_639_2: "ain", ISO_639_1: "", Name: "Ainu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "aka", ISO_639_1: "ak", Name: "Akan", Alphabet: `A B D E Ɛ F G H I K L M N O Ɔ P R S T U W Y`, Numerals: `0-9`},
	{ISO_639_2: "akk", ISO_639_1: "", Name: "Akkadian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "amh", ISO_639_1: "am", Name: "Amharic",
		Alphabet: `ሀ ሁ ሂ ሃ ሄ ህ ሆ ለ ሉ ሊ ላ ሌ ል ሎ ሐ ሑ ሒ ሓ ሔ ሕ ሖ መ ሙ ሚ ማ ሜ ም ሞ
		ሠ ሡ ሢ ሣ ሤ ሥ ሦ ረ ሩ ሪ ራ ሬ ር ሮ ሰ ሱ ሲ ሳ ሴ ስ ሶ ሸ ሹ ሺ ሻ ሼ ሽ ሾ ቀ ቁ ቂ ቃ ቄ ቅ ቆ
		ቐ ቑ ቒ ቓ ቔ ቕ ቖ በ ቡ ቢ ባ ቤ ብ ቦ ቨ ቩ ቪ ቫ ቬ ቭ ቮ ተ ቱ ቲ ታ ቴ ት ቶ ቸ ቹ ቺ ቻ ቼ ች ቾ
		ኀ ኁ ኂ ኃ ኄ ኅ ኆ ነ ኑ ኒ ና ኔ ን ኖ ኘ ኙ ኚ ኛ ኜ ኝ ኞ አ ኡ ኢ ኣ ኤ እ ኦ ከ ኩ ኪ ካ ኬ ክ ኮ
		ኸ ኹ ኺ ኻ ኼ ኽ ኾ ወ ዉ ዊ ዋ ዌ ው ዎ ዐ ዑ ዒ ዓ ዔ ዕ ዖ ዘ ዙ ዚ ዛ ዜ ዝ ዞ ዠ ዡ ዢ ዣ ዤ ዥ ዦ
		የ ዩ ዪ ያ ዬ ይ ዮ ደ ዱ ዲ ዳ ዴ ድ ዶ ዸ ዹ ዺ ዻ ዼ ዽ ዾ ጀ ጁ ጂ ጃ ጄ ጅ ጆ ገ ጉ ጊ ጋ ጌ ግ ጎ
		ጘ ጙ ጚ ጛ ጜ ጝ ጞ ጠ ጡ ጢ ጣ ጤ ጥ ጦ ጨ ጩ ጪ ጫ ጬ ጭ ጮ ጰ ጱ ጲ ጳ ጴ ጵ ጶ ጸ ጹ ጺ ጻ ጼ ጽ ጾ
		ፀ ፁ ፂ ፃ ፄ ፅ ፆ ፈ ፉ ፊ ፋ ፌ ፍ ፎ ፐ ፑ ፒ ፓ ፔ ፕ ፖ`,
		Numerals: `፩ ፪ ፫ ፬ ፭ ፮ ፯ ፰ ፱ ፲ ፳ ፴ ፵ ፶ ፷ ፸ ፹ ፺ ፻ ፼`},
	{ISO_639_2: "ale", ISO_639_1: "", Name: "Aleut", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "alg", ISO_639_1: "", Name: "Algonquian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "alt", ISO_639_1: "", Name: "Southern Altai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ang", ISO_639_1: "", Name: "English, Old (ca.450–1100)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "anp", ISO_639_1: "", Name: "Angika", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "apa", ISO_639_1: "", Name: "Apache languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ara", ISO_639_1: "ar", Name: "Arabic",
		Alphabet: `ء آ أ ؤ إ ئ ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ
		ف ق ك ل م ن ه و ي  ً  ٌ  ٍ  َ  ُ  ِ  ّ  ْ  ٓ  ٔ  ٕ  ٰ  ٱ `,
		Numerals: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ 0-9`},
	{ISO_639_2: "arc", ISO_639_1: "", Name: "Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "arg", ISO_639_1: "an", Name: "Aragonese", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`, Numerals: `0-9`},
	{ISO_639_2: "arn", ISO_639_1: "", Name: "Mapudungun; Mapuche", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "arp", ISO_639_1: "", Name: "Arapaho", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "art", ISO_639_1: "", Name: "Artificial languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "arw", ISO_639_1: "", Name: "Arawak", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "asm", ISO_639_1: "as", Name: "Assamese",
		Alphabet: `অ অʼআ  ই ঈ উ ঊ ঋ এ ঐ ও ঔ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ
		ড ঢ ণ ত থ দ ধ ন প ফ ব ভ ম য ৰ ল ৱ শ ষ স হ ড় ঢ় য়`,
		Numerals: `০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯`},
	{ISO_639_2: "ast", ISO_639_1: "", Name: "Asturian; Bable; Leonese; Asturleonese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ath", ISO_639_1: "", Name: "Athapascan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "aus", ISO_639_1: "", Name: "Australian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ava", ISO_639_1: "av", Name: "Avaric", Alphabet: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ӏ`, Numerals: `0-9`},
	{ISO_639_2: "ave", ISO_639_1: "ae", Name: "Avestan",
		Alphabet: `𐬀  𐬁  𐬂 𐬃  𐬄 𐬅 𐬆 𐬇 𐬈 𐬉 𐬊 𐬋 𐬌 𐬍 𐬎 𐬏 𐬐 𐬑 𐬒 𐬓 𐬔 𐬕 𐬖 𐬗 𐬘 𐬙 𐬚
		𐬛 𐬜 𐬝 𐬞 𐬟  𐬠 𐬡 𐬢 𐬣 𐬤 𐬥 𐬦 𐬧 𐬨 𐬩 𐬪 𐬫 𐬬 𐬭 𐬯 𐬰 𐬱 𐬲 𐬳  𐬴  𐬵`,
		// According to http://www.heritageinstitute.com/zoroastrianism/pdf/avestanKaranjia.pdf
		// (Teach Yourself Avesta Language) The numerals in Avesta have only word forms.
		// There are no figures to indicate the numerals.
		Numerals: ``},
	{ISO_639_2: "awa", ISO_639_1: "", Name: "Awadhi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "aym", ISO_639_1: "ay", Name: "Aymara", Alphabet: `A Ä C H I Ï J K L M N Ñ P Q R S T U Ü W X Y '`, Numerals: `0-9`},
	{ISO_639_2: "aze", ISO_639_1: "az", Name: "Azerbaijani", Alphabet: `A B C Ç D E Ə F G Ğ H X I İ J K Q L M N O Ö P R S Ş T U Ü V Y Z ı`, Numerals: `0-9`},
	{ISO_639_2: "bad", ISO_639_1: "", Name: "Banda languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bai", ISO_639_1: "", Name: "Bamileke languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bak", ISO_639_1: "ba", Name: "Bashkir", Alphabet: ``},
	{ISO_639_2: "bal", ISO_639_1: "", Name: "Baluchi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bam", ISO_639_1: "bm", Name: "Bambara", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ban", ISO_639_1: "", Name: "Balinese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bas", ISO_639_1: "", Name: "Basa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bat", ISO_639_1: "", Name: "Baltic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bej", ISO_639_1: "", Name: "Beja; Bedawiyet", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bel", ISO_639_1: "be", Name: "Belarusian", Alphabet: `А Б В Г Д Е Ё Ж З І Й К Л М Н О П Р С Т У Ў Ф Х Ц Ч Ш Ы Ь Э Ю Я`, Numerals: `0-9`},
	{ISO_639_2: "bem", ISO_639_1: "", Name: "Bemba", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ben", ISO_639_1: "bn", Name: "Bengali", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ber", ISO_639_1: "", Name: "Berber languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bho", ISO_639_1: "", Name: "Bhojpuri", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bih", ISO_639_1: "bh", Name: "Bihari languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bik", ISO_639_1: "", Name: "Bikol", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bin", ISO_639_1: "", Name: "Bini; Edo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bis", ISO_639_1: "bi", Name: "Bislama", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bla", ISO_639_1: "", Name: "Siksika", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bnt", ISO_639_1: "", Name: "Bantu languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bod", ISO_639_1: "bo", Name: "Tibetan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bos", ISO_639_1: "bs", Name: "Bosnian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bra", ISO_639_1: "", Name: "Braj", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bre", ISO_639_1: "br", Name: "Breton", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "btk", ISO_639_1: "", Name: "Batak languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bua", ISO_639_1: "", Name: "Buriat", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bug", ISO_639_1: "", Name: "Buginese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "bul", ISO_639_1: "bg", Name: "Bulgarian", Alphabet: `А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ь Ю Я`, Numerals: `0-9`},
	{ISO_639_2: "byn", ISO_639_1: "", Name: "Blin; Bilin", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cad", ISO_639_1: "", Name: "Caddo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cai", ISO_639_1: "", Name: "Central American Indian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "car", ISO_639_1: "", Name: "Galibi Carib", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cat", ISO_639_1: "ca", Name: "Catalan, Valencian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cau", ISO_639_1: "", Name: "Caucasian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ceb", ISO_639_1: "", Name: "Cebuano", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cel", ISO_639_1: "", Name: "Celtic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ces", ISO_639_1: "cs", Name: "Czech", Alphabet: `A Á B C Č D Ď E É Ě F G H I Í J K L M N Ň O Ó P Q R Ř S Š T Ť U Ú Ů V W X Y Ý Z Ž`, Numerals: `0-9`},
	{ISO_639_2: "cha", ISO_639_1: "ch", Name: "Chamorro", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chb", ISO_639_1: "", Name: "Chibcha", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "che", ISO_639_1: "ce", Name: "Chechen", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chg", ISO_639_1: "", Name: "Chagatai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chk", ISO_639_1: "", Name: "Chuukese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chm", ISO_639_1: "", Name: "Mari", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chn", ISO_639_1: "", Name: "Chinook jargon", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cho", ISO_639_1: "", Name: "Choctaw", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chp", ISO_639_1: "", Name: "Chipewyan; Dene Suline", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chr", ISO_639_1: "", Name: "Cherokee", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chu", ISO_639_1: "cu", Name: "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chv", ISO_639_1: "cv", Name: "Chuvash", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "chy", ISO_639_1: "", Name: "Cheyenne", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cmc", ISO_639_1: "", Name: "Chamic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cnr", ISO_639_1: "", Name: "Montenegrin",
		// Accoding to https://en.wikipedia.org/wiki/Montenegrin_alphabet
		// Montenegrin seems to be using both the Latin and Cyrillic alphabet.
		Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š Ś T U V Z Ž Ź
		А Б В Г Д Ђ Е Ж З З́ И Ј К Л Љ М Н Њ О П Р С С́ Т Ћ У Ф Х Ц Ч Џ Ш`,
		Numerals: `0-9`},
	{ISO_639_2: "cnr", ISO_639_1: "", Name: "Montenegrin", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cop", ISO_639_1: "", Name: "Coptic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cor", ISO_639_1: "kw", Name: "Cornish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cos", ISO_639_1: "co", Name: "Corsican", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cpe", ISO_639_1: "", Name: "Creoles and pidgins, English based", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cpf", ISO_639_1: "", Name: "Creoles and pidgins, French-based", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cpp", ISO_639_1: "", Name: "Creoles and pidgins, Portuguese-based", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cre", ISO_639_1: "cr", Name: "Cree", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "crh", ISO_639_1: "", Name: "Crimean Tatar; Crimean Turkish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "crp", ISO_639_1: "", Name: "Creoles and pidgins", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "csb", ISO_639_1: "", Name: "Kashubian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cus", ISO_639_1: "", Name: "Cushitic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "cym", ISO_639_1: "cy", Name: "Welsh", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dak", ISO_639_1: "", Name: "Dakota", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dan", ISO_639_1: "da", Name: "Danish", Alphabet: `A Á B C D E É F G H I Í J K L M N O Ó P Q R S T U Ú V W X Y Ý Z Æ Ǽ Ø Ǿ Å`, Numerals: `0-9`},
	{ISO_639_2: "dar", ISO_639_1: "", Name: "Dargwa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "day", ISO_639_1: "", Name: "Land Dayak languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "del", ISO_639_1: "", Name: "Delaware", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "den", ISO_639_1: "", Name: "Slave (Athapascan)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "deu", ISO_639_1: "de", Name: "German", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ö Ü ß`, Numerals: `0-9`},
	{ISO_639_2: "dgr", ISO_639_1: "", Name: "Dogrib", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "din", ISO_639_1: "", Name: "Dinka", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "div", ISO_639_1: "dv", Name: "Divehi, Dhivehi, Maldivian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "doi", ISO_639_1: "", Name: "Dogri", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dra", ISO_639_1: "", Name: "Dravidian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dsb", ISO_639_1: "", Name: "Lower Sorbian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dua", ISO_639_1: "", Name: "Duala", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dum", ISO_639_1: "", Name: "Dutch, Middle (ca. 1050–1350)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dyu", ISO_639_1: "", Name: "Dyula", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "dzo", ISO_639_1: "dz", Name: "Dzongkha", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "efi", ISO_639_1: "", Name: "Efik", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "egy", ISO_639_1: "", Name: "Egyptian (Ancient)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "eka", ISO_639_1: "", Name: "Ekajuk", Alphabet: ``, Numerals: ""},
	// NOTE: The "dexia keraia" ( ´ ) and "aristeri keraia" ( ͵ ) are
	// used to indicate the numeric use of letters, for example ͵ΒΙΘʹ
	// represents the number 2019.
	{ISO_639_2: "ell", ISO_639_1: "el", Name: "Greek Modern (1453–)", Alphabet: `Α Β Γ Δ Ε Ζ Η Ή Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω Ϊ Ϋ Ά Ώ Έ Ί Ό Ύ ΰ`, Numerals: `0-9´͵`},
	{ISO_639_2: "elx", ISO_639_1: "", Name: "Elamite", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "eng", ISO_639_1: "en", Name: "English", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`, Numerals: `0-9`},
	{ISO_639_2: "enm", ISO_639_1: "", Name: "English, Middle (1100–1500)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "epo", ISO_639_1: "eo", Name: "Esperanto", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "est", ISO_639_1: "et", Name: "Estonian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "eus", ISO_639_1: "eu", Name: "Basque", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ewe", ISO_639_1: "ee", Name: "Ewe", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ewo", ISO_639_1: "", Name: "Ewondo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fan", ISO_639_1: "", Name: "Fang", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fao", ISO_639_1: "fo", Name: "Faroese", Alphabet: `A Á B D Ð E F G H I Í J K L M N O Ó P R S T U Ú V Y Ý Æ Ø`, Numerals: `0-9`},
	{ISO_639_2: "fas", ISO_639_1: "fa", Name: "Persian", Alphabet: `ء أ ئ ؤ ؤ ا ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی`, Numerals: `۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹`},
	{ISO_639_2: "fat", ISO_639_1: "", Name: "Fanti", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fij", ISO_639_1: "fj", Name: "Fijian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fil", ISO_639_1: "", Name: "Filipino; Pilipino", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fin", ISO_639_1: "fi", Name: "Finnish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fiu", ISO_639_1: "", Name: "Finno-Ugrian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fon", ISO_639_1: "", Name: "Fon", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fra", ISO_639_1: "fr", Name: "French", Alphabet: `A À Â Æ B C Ç D E É È Ê Ë F G H I Î Ï J K L M N O Ô Œ P Q R S T U Ù Û Ü V W X Y Ÿ Z`, Numerals: `0-9`},
	{ISO_639_2: "frm", ISO_639_1: "", Name: "French, Middle (ca. 1400–1600)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fro", ISO_639_1: "", Name: "French, Old (842–ca. 1400)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "frr", ISO_639_1: "", Name: "Northern Frisian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "frs", ISO_639_1: "", Name: "Eastern Frisian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fry", ISO_639_1: "fy", Name: "Western Frisian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ful", ISO_639_1: "ff", Name: "Fulah", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "fur", ISO_639_1: "", Name: "Friulian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gaa", ISO_639_1: "", Name: "Ga", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gay", ISO_639_1: "", Name: "Gayo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gba", ISO_639_1: "", Name: "Gbaya", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gem", ISO_639_1: "", Name: "Germanic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gez", ISO_639_1: "", Name: "Geez", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gil", ISO_639_1: "", Name: "Gilbertese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gla", ISO_639_1: "gd", Name: "Gaelic, Scottish Gaelic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gle", ISO_639_1: "ga", Name: "Irish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "glg", ISO_639_1: "gl", Name: "Galician", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "glv", ISO_639_1: "gv", Name: "Manx", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gmh", ISO_639_1: "", Name: "German, Middle High (ca. 1050–1500)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "goh", ISO_639_1: "", Name: "German, Old High (ca. 750–1050)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gon", ISO_639_1: "", Name: "Gondi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gor", ISO_639_1: "", Name: "Gorontalo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "got", ISO_639_1: "", Name: "Gothic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "grb", ISO_639_1: "", Name: "Grebo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "grc", ISO_639_1: "", Name: "Greek, Ancient (to 1453)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "grn", ISO_639_1: "gn", Name: "Guarani", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gsw", ISO_639_1: "", Name: "Swiss German; Alemannic; Alsatian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "guj", ISO_639_1: "gu", Name: "Gujarati", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "gwi", ISO_639_1: "", Name: "Gwich'in", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hai", ISO_639_1: "", Name: "Haida", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hat", ISO_639_1: "ht", Name: "Haitian, Haitian Creole", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hau", ISO_639_1: "ha", Name: "Hausa (Hausa)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "haw", ISO_639_1: "", Name: "Hawaiian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hbs", ISO_639_1: "sh", Name: "Serbo-Croatian", Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`, Numerals: `0-9`},
	// NOTE: The "geresh" ( ׳ ) is used to denote a single-digit Hebrew numeral.
	// The "gershayim" ( ״ ) is used to indicate a multi-digit Hebrew numeral.
	{ISO_639_2: "heb", ISO_639_1: "he", Name: "Hebrew", Alphabet: `א ב ג ד ה ו ז ח ט י כ ך ל מ ם נ ן ס ע פ ף צ ץ ק ר ש ת`, Numerals: `0-9׳״`},
	{ISO_639_2: "her", ISO_639_1: "hz", Name: "Herero", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hil", ISO_639_1: "", Name: "Hiligaynon", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "him", ISO_639_1: "", Name: "Himachali languages; Pahari languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hin", ISO_639_1: "hi", Name: "Hindi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hit", ISO_639_1: "", Name: "Hittite", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hmn", ISO_639_1: "", Name: "Hmong; Mong", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hmo", ISO_639_1: "ho", Name: "Hiri Motu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hrv", ISO_639_1: "hr", Name: "Croatian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hsb", ISO_639_1: "", Name: "Upper Sorbian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hun", ISO_639_1: "hu", Name: "Hungarian", Alphabet: `A Á B C D E É F G H I Í J K L M N O Ó Ö Ő P Q R S T U Ú Ü Ű V W X Y Z`, Numerals: `0-9`},
	{ISO_639_2: "hup", ISO_639_1: "", Name: "Hupa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "hye", ISO_639_1: "hy", Name: "Armenian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "iba", ISO_639_1: "", Name: "Iban", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ibo", ISO_639_1: "ig", Name: "Igbo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ido", ISO_639_1: "io", Name: "Ido", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "iii", ISO_639_1: "ii", Name: "Sichuan Yi, Nuosu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ijo", ISO_639_1: "", Name: "Ijo languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "iku", ISO_639_1: "iu", Name: "Inuktitut", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ile", ISO_639_1: "ie", Name: "Interlingue, Occidental", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ilo", ISO_639_1: "", Name: "Iloko", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ina", ISO_639_1: "ia", Name: "Interlingua (International Auxiliary Language Association)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "inc", ISO_639_1: "", Name: "Indic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ind", ISO_639_1: "id", Name: "Indonesian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ine", ISO_639_1: "", Name: "Indo-European languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "inh", ISO_639_1: "", Name: "Ingush", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ipk", ISO_639_1: "ik", Name: "Inupiaq", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ira", ISO_639_1: "", Name: "Iranian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "iro", ISO_639_1: "", Name: "Iroquoian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "isl", ISO_639_1: "is", Name: "Icelandic", Alphabet: `A Á B D Ð E É F G H I Í J K L M N O Ó P R S T U Ú V X Y Ý Þ Æ Ö`, Numerals: `0-9`},
	{ISO_639_2: "ita", ISO_639_1: "it", Name: "Italian", Alphabet: `A À B C D E È É F G H I Ì Í Î L M N O Ò Ó P Q R S T U Ù Ú V Z`, Numerals: `0-9`},
	{ISO_639_2: "jav", ISO_639_1: "jv", Name: "Javanese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "jbo", ISO_639_1: "", Name: "Lojban", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "jpn", ISO_639_1: "ja", Name: "Japanese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "jpr", ISO_639_1: "", Name: "Judeo-Persian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "jrb", ISO_639_1: "", Name: "Judeo-Arabic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kaa", ISO_639_1: "", Name: "Kara-Kalpak", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kab", ISO_639_1: "", Name: "Kabyle", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kac", ISO_639_1: "", Name: "Kachin; Jingpho", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kal", ISO_639_1: "kl", Name: "Kalaallisut, Greenlandic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kam", ISO_639_1: "", Name: "Kamba", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kan", ISO_639_1: "kn", Name: "Kannada", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kar", ISO_639_1: "", Name: "Karen languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kas", ISO_639_1: "ks", Name: "Kashmiri", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kat", ISO_639_1: "ka", Name: "Georgian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kau", ISO_639_1: "kr", Name: "Kanuri", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kaw", ISO_639_1: "", Name: "Kawi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kaz", ISO_639_1: "kk", Name: "Kazakh", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kbd", ISO_639_1: "", Name: "Kabardian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kha", ISO_639_1: "", Name: "Khasi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "khi", ISO_639_1: "", Name: "Khoisan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "khm", ISO_639_1: "km", Name: "Central Khmer", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kho", ISO_639_1: "", Name: "Khotanese; Sakan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kik", ISO_639_1: "ki", Name: "Kikuyu, Gikuyu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kin", ISO_639_1: "rw", Name: "Kinyarwanda", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kir", ISO_639_1: "ky", Name: "Kirghiz, Kyrgyz", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kmb", ISO_639_1: "", Name: "Kimbundu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kok", ISO_639_1: "", Name: "Konkani", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kom", ISO_639_1: "kv", Name: "Komi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kon", ISO_639_1: "kg", Name: "Kongo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kor", ISO_639_1: "ko", Name: "Korean", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kos", ISO_639_1: "", Name: "Kosraean", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kpe", ISO_639_1: "", Name: "Kpelle", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "krc", ISO_639_1: "", Name: "Karachay-Balkar", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "krl", ISO_639_1: "", Name: "Karelian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kro", ISO_639_1: "", Name: "Kru languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kru", ISO_639_1: "", Name: "Kurukh", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kua", ISO_639_1: "kj", Name: "Kuanyama, Kwanyama", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kum", ISO_639_1: "", Name: "Kumyk", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "kur", ISO_639_1: "ku", Name: "Kurdish", Alphabet: `ئ ا ب پ ت ج چ ح خ د ر ڕ ز ژ س ش ع غ ف ڤ ق ک گ ل ڵ م ن ھ ە و ۆ ؤ ی ێ ڒ ڔ ڶ ڷ ۊ ٚ  `, Numerals: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩`},
	{ISO_639_2: "kut", ISO_639_1: "", Name: "Kutenai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lad", ISO_639_1: "", Name: "Ladino", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lah", ISO_639_1: "", Name: "Lahnda", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lam", ISO_639_1: "", Name: "Lamba", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lao", ISO_639_1: "lo", Name: "Lao", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lat", ISO_639_1: "la", Name: "Latin", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lav", ISO_639_1: "lv", Name: "Latvian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lez", ISO_639_1: "", Name: "Lezghian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lim", ISO_639_1: "li", Name: "Limburgan, Limburger, Limburgish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lin", ISO_639_1: "ln", Name: "Lingala", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lit", ISO_639_1: "lt", Name: "Lithuanian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lol", ISO_639_1: "", Name: "Mongo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "loz", ISO_639_1: "", Name: "Lozi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ltz", ISO_639_1: "lb", Name: "Luxembourgish, Letzeburgesch", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lua", ISO_639_1: "", Name: "Luba-Lulua", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lub", ISO_639_1: "lu", Name: "Luba-Katanga", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lug", ISO_639_1: "lg", Name: "Ganda", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lui", ISO_639_1: "", Name: "Luiseno", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lun", ISO_639_1: "", Name: "Lunda", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "luo", ISO_639_1: "", Name: "Luo (Kenya and Tanzania)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "lus", ISO_639_1: "", Name: "Lushai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mad", ISO_639_1: "", Name: "Madurese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mag", ISO_639_1: "", Name: "Magahi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mah", ISO_639_1: "mh", Name: "Marshallese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mai", ISO_639_1: "", Name: "Maithili", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mak", ISO_639_1: "", Name: "Makasar", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mal", ISO_639_1: "ml", Name: "Malayalam", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "man", ISO_639_1: "", Name: "Mandingo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "map", ISO_639_1: "", Name: "Austronesian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mar", ISO_639_1: "mr", Name: "Marathi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mas", ISO_639_1: "", Name: "Masai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mdf", ISO_639_1: "", Name: "Moksha", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mdr", ISO_639_1: "", Name: "Mandar", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "men", ISO_639_1: "", Name: "Mende", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mga", ISO_639_1: "", Name: "Irish, Middle (900–1200)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mic", ISO_639_1: "", Name: "Mi'kmaq; Micmac", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "min", ISO_639_1: "", Name: "Minangkabau", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mis", ISO_639_1: "", Name: "Uncoded languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mkd", ISO_639_1: "mk", Name: "Macedonian", Alphabet: `А Б В Г Д Ѓ Е Ж З Ѕ И Ј К Л Љ М Н Њ О П Р С Т Ќ У Ф Х Ц Ч Џ Ш`, Numerals: `0-9`},
	{ISO_639_2: "mkh", ISO_639_1: "", Name: "Mon-Khmer languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mlg", ISO_639_1: "mg", Name: "Malagasy", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mlt", ISO_639_1: "mt", Name: "Maltese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mnc", ISO_639_1: "", Name: "Manchu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mni", ISO_639_1: "", Name: "Manipuri", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mno", ISO_639_1: "", Name: "Manobo languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "moh", ISO_639_1: "", Name: "Mohawk", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mon", ISO_639_1: "mn", Name: "Mongolian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mos", ISO_639_1: "", Name: "Mossi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mri", ISO_639_1: "mi", Name: "Maori", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "msa", ISO_639_1: "ms", Name: "Malay", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mul", ISO_639_1: "", Name: "Multiple languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mun", ISO_639_1: "", Name: "Munda languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mus", ISO_639_1: "", Name: "Creek", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mwl", ISO_639_1: "", Name: "Mirandese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mwr", ISO_639_1: "", Name: "Marwari", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "mya", ISO_639_1: "my", Name: "Burmese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "myn", ISO_639_1: "", Name: "Mayan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "myv", ISO_639_1: "", Name: "Erzya", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nah", ISO_639_1: "", Name: "Nahuatl languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nai", ISO_639_1: "", Name: "North American Indian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nap", ISO_639_1: "", Name: "Neapolitan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nau", ISO_639_1: "na", Name: "Nauru", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nav", ISO_639_1: "nv", Name: "Navajo, Navaho", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nbl", ISO_639_1: "nr", Name: "South Ndebele", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nde", ISO_639_1: "nd", Name: "North Ndebele", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ndo", ISO_639_1: "ng", Name: "Ndonga", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nds", ISO_639_1: "", Name: "Low German; Low Saxon; German, Low; Saxon, Low", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nep", ISO_639_1: "ne", Name: "Nepali", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "new", ISO_639_1: "", Name: "Nepal Bhasa; Newari", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nia", ISO_639_1: "", Name: "Nias", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nic", ISO_639_1: "", Name: "Niger-Kordofanian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "niu", ISO_639_1: "", Name: "Niuean", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nld", ISO_639_1: "nl", Name: "Dutch, Flemish", Alphabet: `A Á Ä B C D E É Ë F G H I Í Ï J J́ K L M N O Ó Ö P Q R S T U Ú Ü V W X Y Ý Z`, Numerals: `0-9`},
	{ISO_639_2: "nno", ISO_639_1: "nn", Name: "Norwegian Nynorsk", Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`, Numerals: `0-9`},
	{ISO_639_2: "nob", ISO_639_1: "nb", Name: "Norwegian Bokmål", Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`, Numerals: `0-9`},
	{ISO_639_2: "nog", ISO_639_1: "", Name: "Nogai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "non", ISO_639_1: "", Name: "Norse, Old", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nor", ISO_639_1: "no", Name: "Norwegian", Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`, Numerals: `0-9`},
	{ISO_639_2: "nqo", ISO_639_1: "", Name: "N'Ko", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nso", ISO_639_1: "", Name: "Pedi; Sepedi; Northern Sotho", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nub", ISO_639_1: "", Name: "Nubian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nwc", ISO_639_1: "", Name: "Classical Newari; Old Newari; Classical Nepal Bhasa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nya", ISO_639_1: "ny", Name: "Chichewa, Chewa, Nyanja", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nym", ISO_639_1: "", Name: "Nyamwezi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nyn", ISO_639_1: "", Name: "Nyankole", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nyo", ISO_639_1: "", Name: "Nyoro", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "nzi", ISO_639_1: "", Name: "Nzima", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "oci", ISO_639_1: "oc", Name: "Occitan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "oji", ISO_639_1: "oj", Name: "Ojibwa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ori", ISO_639_1: "or", Name: "Oriya", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "orm", ISO_639_1: "om", Name: "Oromo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "osa", ISO_639_1: "", Name: "Osage", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "oss", ISO_639_1: "os", Name: "Ossetian, Ossetic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ota", ISO_639_1: "", Name: "Turkish, Ottoman (1500–1928)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "oto", ISO_639_1: "", Name: "Otomian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "paa", ISO_639_1: "", Name: "Papuan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pag", ISO_639_1: "", Name: "Pangasinan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pal", ISO_639_1: "", Name: "Pahlavi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pam", ISO_639_1: "", Name: "Pampanga; Kapampangan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pan", ISO_639_1: "pa", Name: "Punjabi, Panjabi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pap", ISO_639_1: "", Name: "Papiamento", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pau", ISO_639_1: "", Name: "Palauan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "peo", ISO_639_1: "", Name: "Persian, Old (ca. 600–400 B.C.)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "phi", ISO_639_1: "", Name: "Philippine languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "phn", ISO_639_1: "", Name: "Phoenician", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pli", ISO_639_1: "pi", Name: "Pali", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pol", ISO_639_1: "pl", Name: "Polish", Alphabet: `A Ą B C Ć D E Ę F G H I J K L Ł M N Ń O Ó P Q R S Ś T U V W X Y Z Ź Ż`, Numerals: `0-9`},
	{ISO_639_2: "pon", ISO_639_1: "", Name: "Pohnpeian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "por", ISO_639_1: "pt", Name: "Portuguese", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á Â Ã À Ä Ç É Ê Ë Í Ï Ó Ô Õ Ú Ü`, Numerals: `0-9`},
	{ISO_639_2: "pra", ISO_639_1: "", Name: "Prakrit languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pro", ISO_639_1: "", Name: "Provençal, Old (to 1500); Old Occitan (to 1500)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "pus", ISO_639_1: "ps", Name: "Pashto, Pushto", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "que", ISO_639_1: "qu", Name: "Quechua", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "raj", ISO_639_1: "", Name: "Rajasthani", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "rap", ISO_639_1: "", Name: "Rapanui", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "rar", ISO_639_1: "", Name: "Rarotongan; Cook Islands Maori", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "roa", ISO_639_1: "", Name: "Romance languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "roh", ISO_639_1: "rm", Name: "Romansh", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "rom", ISO_639_1: "", Name: "Romany", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ron", ISO_639_1: "ro", Name: "Romanian, Moldavian, Moldovan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "run", ISO_639_1: "rn", Name: "Rundi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "rup", ISO_639_1: "", Name: "Aromanian; Arumanian; Macedo-Romanian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "rus", ISO_639_1: "ru", Name: "Russian", Alphabet: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я`, Numerals: `0-9`},
	{ISO_639_2: "sad", ISO_639_1: "", Name: "Sandawe", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sag", ISO_639_1: "sg", Name: "Sango", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sah", ISO_639_1: "", Name: "Yakut", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sai", ISO_639_1: "", Name: "South American Indian languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sal", ISO_639_1: "", Name: "Salishan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sam", ISO_639_1: "", Name: "Samaritan Aramaic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "san", ISO_639_1: "sa", Name: "Sanskrit", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sas", ISO_639_1: "", Name: "Sasak", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sat", ISO_639_1: "", Name: "Santali", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "scn", ISO_639_1: "", Name: "Sicilian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sco", ISO_639_1: "", Name: "Scots", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sel", ISO_639_1: "", Name: "Selkup", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sem", ISO_639_1: "", Name: "Semitic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sga", ISO_639_1: "", Name: "Irish, Old (to 900)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sgn", ISO_639_1: "", Name: "Sign Languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "shn", ISO_639_1: "", Name: "Shan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sid", ISO_639_1: "", Name: "Sidamo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sin", ISO_639_1: "si", Name: "Sinhala, Sinhalese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sio", ISO_639_1: "", Name: "Siouan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sit", ISO_639_1: "", Name: "Sino-Tibetan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sla", ISO_639_1: "", Name: "Slavic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "slk", ISO_639_1: "sk", Name: "Slovak", Alphabet: `A Á Ä B C Č D Ď E É F G H I Í J K L Ĺ Ľ M N Ň O Ó Ô P Q R Ŕ S Š T Ť U Ú V W X Y Ý Z Ž`, Numerals: `0-9`},
	{ISO_639_2: "slv", ISO_639_1: "sl", Name: "Slovenian", Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`, Numerals: `0-9`},
	{ISO_639_2: "sma", ISO_639_1: "", Name: "Southern Sami", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sme", ISO_639_1: "se", Name: "Northern Sami", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "smi", ISO_639_1: "", Name: "Sami languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "smj", ISO_639_1: "", Name: "Lule Sami", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "smn", ISO_639_1: "", Name: "Inari Sami", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "smo", ISO_639_1: "sm", Name: "Samoan", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sms", ISO_639_1: "", Name: "Skolt Sami", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sna", ISO_639_1: "sn", Name: "Shona", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "snd", ISO_639_1: "sd", Name: "Sindhi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "snk", ISO_639_1: "", Name: "Soninke", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sog", ISO_639_1: "", Name: "Sogdian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "som", ISO_639_1: "so", Name: "Somali", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "son", ISO_639_1: "", Name: "Songhai languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sot", ISO_639_1: "st", Name: "Southern Sotho", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "spa", ISO_639_1: "es", Name: "Spanish, Castilian", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ñ Ó Ú Ü`, Numerals: `0-9`},
	{ISO_639_2: "sqi", ISO_639_1: "sq", Name: "Albanian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "srd", ISO_639_1: "sc", Name: "Sardinian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "srn", ISO_639_1: "", Name: "Sranan Tongo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "srp", ISO_639_1: "sr", Name: "Serbian", Alphabet: `А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш`, Numerals: `0-9`},
	{ISO_639_2: "srr", ISO_639_1: "", Name: "Serer", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ssa", ISO_639_1: "", Name: "Nilo-Saharan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ssw", ISO_639_1: "ss", Name: "Swati", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "suk", ISO_639_1: "", Name: "Sukuma", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sun", ISO_639_1: "su", Name: "Sundanese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sus", ISO_639_1: "", Name: "Susu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "sux", ISO_639_1: "", Name: "Sumerian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "swa", ISO_639_1: "sw", Name: "Swahili", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "swe", ISO_639_1: "sv", Name: "Swedish", Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Å Ä Ö`, Numerals: `0-9`},
	{ISO_639_2: "syc", ISO_639_1: "", Name: "Classical Syriac", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "syr", ISO_639_1: "", Name: "Syriac", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tah", ISO_639_1: "ty", Name: "Tahitian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tai", ISO_639_1: "", Name: "Tai languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tam", ISO_639_1: "ta", Name: "Tamil", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tat", ISO_639_1: "tt", Name: "Tatar", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tel", ISO_639_1: "te", Name: "Telugu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tem", ISO_639_1: "", Name: "Timne", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ter", ISO_639_1: "", Name: "Tereno", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tet", ISO_639_1: "", Name: "Tetum", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tgk", ISO_639_1: "tg", Name: "Tajik", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tgl", ISO_639_1: "tl", Name: "Tagalog", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tha", ISO_639_1: "th", Name: "Thai",
		Alphabet: `ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ
		ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ ฯ ะ ั า ำ  ิ  ี  ึ  ื  ุ  ู  ฺ เ แ โ ใ ๅ ไ  ็ ่ ้ ๊ ๋ ์ ํ ๎`,
		Numerals: `๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙`},
	{ISO_639_2: "tig", ISO_639_1: "", Name: "Tigre", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tir", ISO_639_1: "ti", Name: "Tigrinya", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tiv", ISO_639_1: "", Name: "Tiv", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tkl", ISO_639_1: "", Name: "Tokelau", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tlh", ISO_639_1: "", Name: "Klingon; tlhIngan-Hol", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tli", ISO_639_1: "", Name: "Tlingit", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tmh", ISO_639_1: "", Name: "Tamashek", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tog", ISO_639_1: "", Name: "Tonga (Nyasa)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ton", ISO_639_1: "to", Name: "Tonga (Tonga Islands)", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tpi", ISO_639_1: "", Name: "Tok Pisin", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tsi", ISO_639_1: "", Name: "Tsimshian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tsn", ISO_639_1: "tn", Name: "Tswana", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tso", ISO_639_1: "ts", Name: "Tsonga", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tuk", ISO_639_1: "tk", Name: "Turkmen", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tum", ISO_639_1: "", Name: "Tumbuka", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tup", ISO_639_1: "", Name: "Tupi languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tur", ISO_639_1: "tr", Name: "Turkish", Alphabet: `A Â B C Ç D E F G Ğ H I İ Î J K L M N O Ö P R S Ş T U Ü Û V Y Z Q W X ı`, Numerals: `0-9`},
	{ISO_639_2: "tut", ISO_639_1: "", Name: "Altaic languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tvl", ISO_639_1: "", Name: "Tuvalu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "twi", ISO_639_1: "tw", Name: "Twi", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "tyv", ISO_639_1: "", Name: "Tuvinian", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "udm", ISO_639_1: "", Name: "Udmurt", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "uga", ISO_639_1: "", Name: "Ugaritic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "uig", ISO_639_1: "ug", Name: "Uighur, Uyghur", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ukr", ISO_639_1: "uk", Name: "Ukrainian", Alphabet: `А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я`, Numerals: `0-9`},
	{ISO_639_2: "umb", ISO_639_1: "", Name: "Umbundu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "und", ISO_639_1: "", Name: "Undetermined", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "urd", ISO_639_1: "ur", Name: "Urdu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "uzb", ISO_639_1: "uz", Name: "Uzbek", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "vai", ISO_639_1: "", Name: "Vai", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ven", ISO_639_1: "ve", Name: "Venda", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "vie", ISO_639_1: "vi", Name: "Vietnamese",
		Alphabet: `A Ă Â À Ằ Ầ Ả Ẳ Ẩ Ã Ẵ Ẫ Á Ắ Ấ Ạ Ặ Ậ B C D Đ E Ê È Ề Ẻ Ể Ẽ
		Ễ É Ế Ẹ Ệ G H I Ì Ỉ Ĩ Í Ị K L M N O Ô Ơ Ò Ồ Ờ Ỏ Ổ Ở Õ Ỗ Ỡ Ó Ố Ớ
		Ọ Ộ Ợ P Q R S T U Ư Ù Ừ Ủ Ử Ũ Ữ Ú Ứ Ụ Ự V X Y Ỳ Ỷ Ỹ Ý Ỵ`,
		Numerals: `0-9`},
	{ISO_639_2: "vol", ISO_639_1: "vo", Name: "Volapük", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "vot", ISO_639_1: "", Name: "Votic", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "wak", ISO_639_1: "", Name: "Wakashan languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "wal", ISO_639_1: "", Name: "Wolaitta; Wolaytta", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "war", ISO_639_1: "", Name: "Waray", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "was", ISO_639_1: "", Name: "Washo", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "wen", ISO_639_1: "", Name: "sorbian languages", Alphabet: `A B C Č Ć D E Ě F G H I J K Ł L M N Ń O Ó P R Ř Ŕ S Š Ś T U W Y Z Ž Ź`, Numerals: `0-9`},
	{ISO_639_2: "wln", ISO_639_1: "wa", Name: "Walloon", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "wol", ISO_639_1: "wo", Name: "Wolof", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "xal", ISO_639_1: "", Name: "Kalmyk; Oirat", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "xho", ISO_639_1: "xh", Name: "Xhosa", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "yao", ISO_639_1: "", Name: "Yao", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "yap", ISO_639_1: "", Name: "Yapese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "yid", ISO_639_1: "yi", Name: "Yiddish", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "yor", ISO_639_1: "yo", Name: "Yoruba", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "ypk", ISO_639_1: "", Name: "Yupik languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zap", ISO_639_1: "", Name: "Zapotec", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zbl", ISO_639_1: "", Name: "Blissymbols; Blissymbolics; Bliss", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zen", ISO_639_1: "", Name: "Zenaga", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zgh", ISO_639_1: "", Name: "Standard Moroccan Tamazight", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zha", ISO_639_1: "za", Name: "Zhuang, Chuang", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zho", ISO_639_1: "zh", Name: "Chinese", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "znd", ISO_639_1: "", Name: "Zande languages", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zul", ISO_639_1: "zu", Name: "Zulu", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zun", ISO_639_1: "", Name: "Zuni", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zxx", ISO_639_1: "", Name: "No linguistic content; Not applicable", Alphabet: ``, Numerals: ""},
	{ISO_639_2: "zza", ISO_639_1: "", Name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", Alphabet: ``, Numerals: ""},
}
