package tables

import (
	"regexp"
	"strings"
)

var ISO639_1 = make(map[string]Language)
var ISO639_2 = make(map[string]Language)
var Alpha = make(map[string]*regexp.Regexp)
var Alnum = make(map[string]*regexp.Regexp)

func init() {
	for _, lang := range languages {
		// set of ISO 639‑2 (two letter codes)
		ISO639_2[lang.Code3] = lang

		// set of ISO 639‑1 (two letter codes)
		if lang.Code2 != "" {
			ISO639_1[lang.Code2] = lang
		}

		abc := strings.ReplaceAll(lang.Alphabet, " ", "")
		num := strings.ReplaceAll(lang.Numerals, " ", "")
		if len(abc) > 0 {
			// Alpha
			rxabc := regexp.MustCompile(`^(?i)[` + abc + `]+$`)
			Alpha[lang.Code3] = rxabc
			if lang.Code2 != "" {
				Alpha[lang.Code2] = rxabc
			}

			// Alnum
			rxnum := regexp.MustCompile(`^(?i)[` + abc + num + `]+$`)
			Alnum[lang.Code3] = rxnum
			if lang.Code2 != "" {
				Alnum[lang.Code2] = rxnum
			}
		}

	}
}

// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

type Language struct {
	Code3    string // ISO 639‑2 (three letter codes)
	Code2    string // ISO 639‑1 (two letter codes)
	Name     string // english name of the language
	Alphabet string // alphabet of the language
	Numerals string // numerals of the language
	Decimal  rune   // the decimal separator of the language
}

var languages = []Language{
	{Code3: "aar", Code2: "aa", Name: "Afar",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		Numerals: `0-9`},
	{Code3: "abk", Code2: "ab", Name: "Abkhazian",
		Alphabet: `А Б В Г Ӷ Д Е Ж З Ӡ И К Қ Ҟ Л М Н О П Ԥ Р С Т Ҭ У Ф Х Ҳ Ц Ҵ Ч Ҷ Ҽ Ҿ Ш Ы Ҩ Џ Ь Ә`,
		Numerals: `0-9`},
	{Code3: "ace", Code2: "", Name: "Achinese", Alphabet: ``, Numerals: ""},
	{Code3: "ach", Code2: "", Name: "Acoli", Alphabet: ``, Numerals: ""},
	{Code3: "ada", Code2: "", Name: "Adangme", Alphabet: ``, Numerals: ""},
	{Code3: "ady", Code2: "", Name: "Adyghe; Adygei", Alphabet: ``, Numerals: ""},
	{Code3: "afa", Code2: "", Name: "Afro-Asiatic languages", Alphabet: ``, Numerals: ""},
	{Code3: "afh", Code2: "", Name: "Afrihili", Alphabet: ``, Numerals: ""},
	{Code3: "afr", Code2: "af", Name: "Afrikaans",
		Alphabet: `A Á B C D E É È Ê Ë F G H I Í Î Ï J K L M N O Ó Ô Ö P Q R S T U Ú Û Ü V W X Y Ý Z`,
		Numerals: `0-9`},
	{Code3: "ain", Code2: "", Name: "Ainu", Alphabet: ``, Numerals: ""},
	{Code3: "aka", Code2: "ak", Name: "Akan",
		Alphabet: `A B D E Ɛ F G H I K L M N O Ɔ P R S T U W Y`,
		Numerals: `0-9`},
	{Code3: "akk", Code2: "", Name: "Akkadian", Alphabet: ``, Numerals: ""},
	{Code3: "amh", Code2: "am", Name: "Amharic",
		Alphabet: `ሀ ሁ ሂ ሃ ሄ ህ ሆ ለ ሉ ሊ ላ ሌ ል ሎ ሐ ሑ ሒ ሓ ሔ ሕ ሖ መ ሙ ሚ ማ ሜ ም ሞ
		ሠ ሡ ሢ ሣ ሤ ሥ ሦ ረ ሩ ሪ ራ ሬ ር ሮ ሰ ሱ ሲ ሳ ሴ ስ ሶ ሸ ሹ ሺ ሻ ሼ ሽ ሾ ቀ ቁ ቂ ቃ ቄ ቅ ቆ
		ቐ ቑ ቒ ቓ ቔ ቕ ቖ በ ቡ ቢ ባ ቤ ብ ቦ ቨ ቩ ቪ ቫ ቬ ቭ ቮ ተ ቱ ቲ ታ ቴ ት ቶ ቸ ቹ ቺ ቻ ቼ ች ቾ
		ኀ ኁ ኂ ኃ ኄ ኅ ኆ ነ ኑ ኒ ና ኔ ን ኖ ኘ ኙ ኚ ኛ ኜ ኝ ኞ አ ኡ ኢ ኣ ኤ እ ኦ ከ ኩ ኪ ካ ኬ ክ ኮ
		ኸ ኹ ኺ ኻ ኼ ኽ ኾ ወ ዉ ዊ ዋ ዌ ው ዎ ዐ ዑ ዒ ዓ ዔ ዕ ዖ ዘ ዙ ዚ ዛ ዜ ዝ ዞ ዠ ዡ ዢ ዣ ዤ ዥ ዦ
		የ ዩ ዪ ያ ዬ ይ ዮ ደ ዱ ዲ ዳ ዴ ድ ዶ ዸ ዹ ዺ ዻ ዼ ዽ ዾ ጀ ጁ ጂ ጃ ጄ ጅ ጆ ገ ጉ ጊ ጋ ጌ ግ ጎ
		ጘ ጙ ጚ ጛ ጜ ጝ ጞ ጠ ጡ ጢ ጣ ጤ ጥ ጦ ጨ ጩ ጪ ጫ ጬ ጭ ጮ ጰ ጱ ጲ ጳ ጴ ጵ ጶ ጸ ጹ ጺ ጻ ጼ ጽ ጾ
		ፀ ፁ ፂ ፃ ፄ ፅ ፆ ፈ ፉ ፊ ፋ ፌ ፍ ፎ ፐ ፑ ፒ ፓ ፔ ፕ ፖ`,
		Numerals: `፩ ፪ ፫ ፬ ፭ ፮ ፯ ፰ ፱ ፲ ፳ ፴ ፵ ፶ ፷ ፸ ፹ ፺ ፻ ፼`},
	{Code3: "ale", Code2: "", Name: "Aleut", Alphabet: ``, Numerals: ""},
	{Code3: "alg", Code2: "", Name: "Algonquian languages", Alphabet: ``, Numerals: ""},
	{Code3: "alt", Code2: "", Name: "Southern Altai", Alphabet: ``, Numerals: ""},
	{Code3: "ang", Code2: "", Name: "English, Old (ca.450–1100)", Alphabet: ``, Numerals: ""},
	{Code3: "anp", Code2: "", Name: "Angika", Alphabet: ``, Numerals: ""},
	{Code3: "apa", Code2: "", Name: "Apache languages", Alphabet: ``, Numerals: ""},
	{Code3: "ara", Code2: "ar", Name: "Arabic",
		Alphabet: `ء آ أ ؤ إ ئ ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ
		ف ق ك ل م ن ه و ي  ً  ٌ  ٍ  َ  ُ  ِ  ّ  ْ  ٓ  ٔ  ٕ  ٰ  ٱ `,
		Numerals: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ 0-9`},
	{Code3: "arc", Code2: "", Name: "Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)", Alphabet: ``, Numerals: ""},
	{Code3: "arg", Code2: "an", Name: "Aragonese",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		Numerals: `0-9`},
	{Code3: "arn", Code2: "", Name: "Mapudungun; Mapuche", Alphabet: ``, Numerals: ""},
	{Code3: "arp", Code2: "", Name: "Arapaho", Alphabet: ``, Numerals: ""},
	{Code3: "art", Code2: "", Name: "Artificial languages", Alphabet: ``, Numerals: ""},
	{Code3: "arw", Code2: "", Name: "Arawak", Alphabet: ``, Numerals: ""},
	{Code3: "asm", Code2: "as", Name: "Assamese",
		Alphabet: `অ অʼআ  ই ঈ উ ঊ ঋ এ ঐ ও ঔ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ
		ড ঢ ণ ত থ দ ধ ন প ফ ব ভ ম য ৰ ল ৱ শ ষ স হ ড় ঢ় য়`,
		Numerals: `০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯`},
	{Code3: "ast", Code2: "", Name: "Asturian; Bable; Leonese; Asturleonese", Alphabet: ``, Numerals: ""},
	{Code3: "ath", Code2: "", Name: "Athapascan languages", Alphabet: ``, Numerals: ""},
	{Code3: "aus", Code2: "", Name: "Australian languages", Alphabet: ``, Numerals: ""},
	{Code3: "ava", Code2: "av", Name: "Avaric",
		Alphabet: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ӏ`,
		Numerals: `0-9`},
	{Code3: "ave", Code2: "ae", Name: "Avestan",
		Alphabet: `𐬀  𐬁  𐬂 𐬃  𐬄 𐬅 𐬆 𐬇 𐬈 𐬉 𐬊 𐬋 𐬌 𐬍 𐬎 𐬏 𐬐 𐬑 𐬒 𐬓 𐬔 𐬕 𐬖 𐬗 𐬘 𐬙 𐬚
		𐬛 𐬜 𐬝 𐬞 𐬟  𐬠 𐬡 𐬢 𐬣 𐬤 𐬥 𐬦 𐬧 𐬨 𐬩 𐬪 𐬫 𐬬 𐬭 𐬯 𐬰 𐬱 𐬲 𐬳  𐬴  𐬵`,
		// According to http://www.heritageinstitute.com/zoroastrianism/pdf/avestanKaranjia.pdf
		// (Teach Yourself Avesta Language) The numerals in Avesta have only word forms.
		// There are no figures to indicate the numerals.
		Numerals: ``},
	{Code3: "awa", Code2: "", Name: "Awadhi", Alphabet: ``, Numerals: ""},
	{Code3: "aym", Code2: "ay", Name: "Aymara",
		Alphabet: `A Ä C H I Ï J K L M N Ñ P Q R S T U Ü W X Y '`,
		Numerals: `0-9`},
	{Code3: "aze", Code2: "az", Name: "Azerbaijani",
		Alphabet: `A B C Ç D E Ə F G Ğ H X I İ J K Q L M N O Ö P R S Ş T U Ü V Y Z ı`,
		Numerals: `0-9`},
	{Code3: "bad", Code2: "", Name: "Banda languages", Alphabet: ``, Numerals: ""},
	{Code3: "bai", Code2: "", Name: "Bamileke languages", Alphabet: ``, Numerals: ""},
	{Code3: "bak", Code2: "ba", Name: "Bashkir", Alphabet: ``},
	{Code3: "bal", Code2: "", Name: "Baluchi", Alphabet: ``, Numerals: ""},
	{Code3: "bam", Code2: "bm", Name: "Bambara", Alphabet: ``, Numerals: ""},
	{Code3: "ban", Code2: "", Name: "Balinese", Alphabet: ``, Numerals: ""},
	{Code3: "bas", Code2: "", Name: "Basa", Alphabet: ``, Numerals: ""},
	{Code3: "bat", Code2: "", Name: "Baltic languages", Alphabet: ``, Numerals: ""},
	{Code3: "bej", Code2: "", Name: "Beja; Bedawiyet", Alphabet: ``, Numerals: ""},
	{Code3: "bel", Code2: "be", Name: "Belarusian",
		Alphabet: `А Б В Г Д Е Ё Ж З І Й К Л М Н О П Р С Т У Ў Ф Х Ц Ч Ш Ы Ь Э Ю Я`,
		Numerals: `0-9`},
	{Code3: "bem", Code2: "", Name: "Bemba", Alphabet: ``, Numerals: ""},
	{Code3: "ben", Code2: "bn", Name: "Bengali", Alphabet: ``, Numerals: ""},
	{Code3: "ber", Code2: "", Name: "Berber languages", Alphabet: ``, Numerals: ""},
	{Code3: "bho", Code2: "", Name: "Bhojpuri", Alphabet: ``, Numerals: ""},
	{Code3: "bih", Code2: "bh", Name: "Bihari languages", Alphabet: ``, Numerals: ""},
	{Code3: "bik", Code2: "", Name: "Bikol", Alphabet: ``, Numerals: ""},
	{Code3: "bin", Code2: "", Name: "Bini; Edo", Alphabet: ``, Numerals: ""},
	{Code3: "bis", Code2: "bi", Name: "Bislama", Alphabet: ``, Numerals: ""},
	{Code3: "bla", Code2: "", Name: "Siksika", Alphabet: ``, Numerals: ""},
	{Code3: "bnt", Code2: "", Name: "Bantu languages", Alphabet: ``, Numerals: ""},
	{Code3: "bod", Code2: "bo", Name: "Tibetan", Alphabet: ``, Numerals: ""},
	{Code3: "bos", Code2: "bs", Name: "Bosnian", Alphabet: ``, Numerals: ""},
	{Code3: "bra", Code2: "", Name: "Braj", Alphabet: ``, Numerals: ""},
	{Code3: "bre", Code2: "br", Name: "Breton", Alphabet: ``, Numerals: ""},
	{Code3: "btk", Code2: "", Name: "Batak languages", Alphabet: ``, Numerals: ""},
	{Code3: "bua", Code2: "", Name: "Buriat", Alphabet: ``, Numerals: ""},
	{Code3: "bug", Code2: "", Name: "Buginese", Alphabet: ``, Numerals: ""},
	{Code3: "bul", Code2: "bg", Name: "Bulgarian",
		Alphabet: `А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ь Ю Я`,
		Numerals: `0-9`},
	{Code3: "byn", Code2: "", Name: "Blin; Bilin", Alphabet: ``, Numerals: ""},
	{Code3: "cad", Code2: "", Name: "Caddo", Alphabet: ``, Numerals: ""},
	{Code3: "cai", Code2: "", Name: "Central American Indian languages", Alphabet: ``, Numerals: ""},
	{Code3: "car", Code2: "", Name: "Galibi Carib", Alphabet: ``, Numerals: ""},
	{Code3: "cat", Code2: "ca", Name: "Catalan, Valencian", Alphabet: ``, Numerals: ""},
	{Code3: "cau", Code2: "", Name: "Caucasian languages", Alphabet: ``, Numerals: ""},
	{Code3: "ceb", Code2: "", Name: "Cebuano", Alphabet: ``, Numerals: ""},
	{Code3: "cel", Code2: "", Name: "Celtic languages", Alphabet: ``, Numerals: ""},
	{Code3: "ces", Code2: "cs", Name: "Czech",
		Alphabet: `A Á B C Č D Ď E É Ě F G H I Í J K L M N Ň O Ó P Q R Ř S Š T Ť U Ú Ů V W X Y Ý Z Ž`,
		Numerals: `0-9`},
	{Code3: "cha", Code2: "ch", Name: "Chamorro", Alphabet: ``, Numerals: ""},
	{Code3: "chb", Code2: "", Name: "Chibcha", Alphabet: ``, Numerals: ""},
	{Code3: "che", Code2: "ce", Name: "Chechen", Alphabet: ``, Numerals: ""},
	{Code3: "chg", Code2: "", Name: "Chagatai", Alphabet: ``, Numerals: ""},
	{Code3: "chk", Code2: "", Name: "Chuukese", Alphabet: ``, Numerals: ""},
	{Code3: "chm", Code2: "", Name: "Mari", Alphabet: ``, Numerals: ""},
	{Code3: "chn", Code2: "", Name: "Chinook jargon", Alphabet: ``, Numerals: ""},
	{Code3: "cho", Code2: "", Name: "Choctaw", Alphabet: ``, Numerals: ""},
	{Code3: "chp", Code2: "", Name: "Chipewyan; Dene Suline", Alphabet: ``, Numerals: ""},
	{Code3: "chr", Code2: "", Name: "Cherokee", Alphabet: ``, Numerals: ""},
	{Code3: "chu", Code2: "cu", Name: "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", Alphabet: ``, Numerals: ""},
	{Code3: "chv", Code2: "cv", Name: "Chuvash", Alphabet: ``, Numerals: ""},
	{Code3: "chy", Code2: "", Name: "Cheyenne", Alphabet: ``, Numerals: ""},
	{Code3: "cmc", Code2: "", Name: "Chamic languages", Alphabet: ``, Numerals: ""},
	{Code3: "cnr", Code2: "", Name: "Montenegrin",
		// Accoding to https://en.wikipedia.org/wiki/Montenegrin_alphabet
		// Montenegrin seems to be using both the Latin and Cyrillic alphabet.
		Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š Ś T U V Z Ž Ź
		А Б В Г Д Ђ Е Ж З З́ И Ј К Л Љ М Н Њ О П Р С С́ Т Ћ У Ф Х Ц Ч Џ Ш`,
		Numerals: `0-9`},
	{Code3: "cnr", Code2: "", Name: "Montenegrin", Alphabet: ``, Numerals: ""},
	{Code3: "cop", Code2: "", Name: "Coptic", Alphabet: ``, Numerals: ""},
	{Code3: "cor", Code2: "kw", Name: "Cornish", Alphabet: ``, Numerals: ""},
	{Code3: "cos", Code2: "co", Name: "Corsican", Alphabet: ``, Numerals: ""},
	{Code3: "cpe", Code2: "", Name: "Creoles and pidgins, English based", Alphabet: ``, Numerals: ""},
	{Code3: "cpf", Code2: "", Name: "Creoles and pidgins, French-based", Alphabet: ``, Numerals: ""},
	{Code3: "cpp", Code2: "", Name: "Creoles and pidgins, Portuguese-based", Alphabet: ``, Numerals: ""},
	{Code3: "cre", Code2: "cr", Name: "Cree", Alphabet: ``, Numerals: ""},
	{Code3: "crh", Code2: "", Name: "Crimean Tatar; Crimean Turkish", Alphabet: ``, Numerals: ""},
	{Code3: "crp", Code2: "", Name: "Creoles and pidgins", Alphabet: ``, Numerals: ""},
	{Code3: "csb", Code2: "", Name: "Kashubian", Alphabet: ``, Numerals: ""},
	{Code3: "cus", Code2: "", Name: "Cushitic languages", Alphabet: ``, Numerals: ""},
	{Code3: "cym", Code2: "cy", Name: "Welsh", Alphabet: ``, Numerals: ""},
	{Code3: "dak", Code2: "", Name: "Dakota", Alphabet: ``, Numerals: ""},
	{Code3: "dan", Code2: "da", Name: "Danish",
		Alphabet: `A Á B C D E É F G H I Í J K L M N O Ó P Q R S T U Ú V W X Y Ý Z Æ Ǽ Ø Ǿ Å`,
		Numerals: `0-9`},
	{Code3: "dar", Code2: "", Name: "Dargwa", Alphabet: ``, Numerals: ""},
	{Code3: "day", Code2: "", Name: "Land Dayak languages", Alphabet: ``, Numerals: ""},
	{Code3: "del", Code2: "", Name: "Delaware", Alphabet: ``, Numerals: ""},
	{Code3: "den", Code2: "", Name: "Slave (Athapascan)", Alphabet: ``, Numerals: ""},
	{Code3: "deu", Code2: "de", Name: "German",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ö Ü ß`,
		Numerals: `0-9`},
	{Code3: "dgr", Code2: "", Name: "Dogrib", Alphabet: ``, Numerals: ""},
	{Code3: "din", Code2: "", Name: "Dinka", Alphabet: ``, Numerals: ""},
	{Code3: "div", Code2: "dv", Name: "Divehi, Dhivehi, Maldivian", Alphabet: ``, Numerals: ""},
	{Code3: "doi", Code2: "", Name: "Dogri", Alphabet: ``, Numerals: ""},
	{Code3: "dra", Code2: "", Name: "Dravidian languages", Alphabet: ``, Numerals: ""},
	{Code3: "dsb", Code2: "", Name: "Lower Sorbian", Alphabet: ``, Numerals: ""},
	{Code3: "dua", Code2: "", Name: "Duala", Alphabet: ``, Numerals: ""},
	{Code3: "dum", Code2: "", Name: "Dutch, Middle (ca. 1050–1350)", Alphabet: ``, Numerals: ""},
	{Code3: "dyu", Code2: "", Name: "Dyula", Alphabet: ``, Numerals: ""},
	{Code3: "dzo", Code2: "dz", Name: "Dzongkha", Alphabet: ``, Numerals: ""},
	{Code3: "efi", Code2: "", Name: "Efik", Alphabet: ``, Numerals: ""},
	{Code3: "egy", Code2: "", Name: "Egyptian (Ancient)", Alphabet: ``, Numerals: ""},
	{Code3: "eka", Code2: "", Name: "Ekajuk", Alphabet: ``, Numerals: ""},
	{Code3: "ell", Code2: "el", Name: "Greek Modern (1453–)",
		Alphabet: `Α Β Γ Δ Ε Ζ Η Ή Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω Ϊ Ϋ Ά Ώ Έ Ί Ό Ύ ΰ`,
		// NOTE: The "dexia keraia" ( ´ ) and "aristeri keraia" ( ͵ ) are
		// used to indicate the numeric use of letters, for example ͵ΒΙΘʹ
		// represents the number 2019.
		Numerals: `0-9´͵`},
	{Code3: "elx", Code2: "", Name: "Elamite", Alphabet: ``, Numerals: ""},
	{Code3: "eng", Code2: "en", Name: "English",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z`,
		Numerals: `0-9`},
	{Code3: "enm", Code2: "", Name: "English, Middle (1100–1500)", Alphabet: ``, Numerals: ""},
	{Code3: "epo", Code2: "eo", Name: "Esperanto", Alphabet: ``, Numerals: ""},
	{Code3: "est", Code2: "et", Name: "Estonian", Alphabet: ``, Numerals: ""},
	{Code3: "eus", Code2: "eu", Name: "Basque", Alphabet: ``, Numerals: ""},
	{Code3: "ewe", Code2: "ee", Name: "Ewe", Alphabet: ``, Numerals: ""},
	{Code3: "ewo", Code2: "", Name: "Ewondo", Alphabet: ``, Numerals: ""},
	{Code3: "fan", Code2: "", Name: "Fang", Alphabet: ``, Numerals: ""},
	{Code3: "fao", Code2: "fo", Name: "Faroese",
		Alphabet: `A Á B D Ð E F G H I Í J K L M N O Ó P R S T U Ú V Y Ý Æ Ø`,
		Numerals: `0-9`},
	{Code3: "fas", Code2: "fa", Name: "Persian",
		Alphabet: `ء أ ئ ؤ ؤ ا ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی`,
		Numerals: `۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹`},
	{Code3: "fat", Code2: "", Name: "Fanti", Alphabet: ``, Numerals: ""},
	{Code3: "fij", Code2: "fj", Name: "Fijian", Alphabet: ``, Numerals: ""},
	{Code3: "fil", Code2: "", Name: "Filipino; Pilipino", Alphabet: ``, Numerals: ""},
	{Code3: "fin", Code2: "fi", Name: "Finnish", Alphabet: ``, Numerals: ""},
	{Code3: "fiu", Code2: "", Name: "Finno-Ugrian languages", Alphabet: ``, Numerals: ""},
	{Code3: "fon", Code2: "", Name: "Fon", Alphabet: ``, Numerals: ""},
	{Code3: "fra", Code2: "fr", Name: "French",
		Alphabet: `A À Â Æ B C Ç D E É È Ê Ë F G H I Î Ï J K L M N O Ô Œ P Q R S T U Ù Û Ü V W X Y Ÿ Z`,
		Numerals: `0-9`},
	{Code3: "frm", Code2: "", Name: "French, Middle (ca. 1400–1600)", Alphabet: ``, Numerals: ""},
	{Code3: "fro", Code2: "", Name: "French, Old (842–ca. 1400)", Alphabet: ``, Numerals: ""},
	{Code3: "frr", Code2: "", Name: "Northern Frisian", Alphabet: ``, Numerals: ""},
	{Code3: "frs", Code2: "", Name: "Eastern Frisian", Alphabet: ``, Numerals: ""},
	{Code3: "fry", Code2: "fy", Name: "Western Frisian", Alphabet: ``, Numerals: ""},
	{Code3: "ful", Code2: "ff", Name: "Fulah", Alphabet: ``, Numerals: ""},
	{Code3: "fur", Code2: "", Name: "Friulian", Alphabet: ``, Numerals: ""},
	{Code3: "gaa", Code2: "", Name: "Ga", Alphabet: ``, Numerals: ""},
	{Code3: "gay", Code2: "", Name: "Gayo", Alphabet: ``, Numerals: ""},
	{Code3: "gba", Code2: "", Name: "Gbaya", Alphabet: ``, Numerals: ""},
	{Code3: "gem", Code2: "", Name: "Germanic languages", Alphabet: ``, Numerals: ""},
	{Code3: "gez", Code2: "", Name: "Geez", Alphabet: ``, Numerals: ""},
	{Code3: "gil", Code2: "", Name: "Gilbertese", Alphabet: ``, Numerals: ""},
	{Code3: "gla", Code2: "gd", Name: "Gaelic, Scottish Gaelic", Alphabet: ``, Numerals: ""},
	{Code3: "gle", Code2: "ga", Name: "Irish", Alphabet: ``, Numerals: ""},
	{Code3: "glg", Code2: "gl", Name: "Galician", Alphabet: ``, Numerals: ""},
	{Code3: "glv", Code2: "gv", Name: "Manx", Alphabet: ``, Numerals: ""},
	{Code3: "gmh", Code2: "", Name: "German, Middle High (ca. 1050–1500)", Alphabet: ``, Numerals: ""},
	{Code3: "goh", Code2: "", Name: "German, Old High (ca. 750–1050)", Alphabet: ``, Numerals: ""},
	{Code3: "gon", Code2: "", Name: "Gondi", Alphabet: ``, Numerals: ""},
	{Code3: "gor", Code2: "", Name: "Gorontalo", Alphabet: ``, Numerals: ""},
	{Code3: "got", Code2: "", Name: "Gothic", Alphabet: ``, Numerals: ""},
	{Code3: "grb", Code2: "", Name: "Grebo", Alphabet: ``, Numerals: ""},
	{Code3: "grc", Code2: "", Name: "Greek, Ancient (to 1453)", Alphabet: ``, Numerals: ""},
	{Code3: "grn", Code2: "gn", Name: "Guarani", Alphabet: ``, Numerals: ""},
	{Code3: "gsw", Code2: "", Name: "Swiss German; Alemannic; Alsatian", Alphabet: ``, Numerals: ""},
	{Code3: "guj", Code2: "gu", Name: "Gujarati", Alphabet: ``, Numerals: ""},
	{Code3: "gwi", Code2: "", Name: "Gwich'in", Alphabet: ``, Numerals: ""},
	{Code3: "hai", Code2: "", Name: "Haida", Alphabet: ``, Numerals: ""},
	{Code3: "hat", Code2: "ht", Name: "Haitian, Haitian Creole", Alphabet: ``, Numerals: ""},
	{Code3: "hau", Code2: "ha", Name: "Hausa (Hausa)", Alphabet: ``, Numerals: ""},
	{Code3: "haw", Code2: "", Name: "Hawaiian", Alphabet: ``, Numerals: ""},
	{Code3: "hbs", Code2: "sh", Name: "Serbo-Croatian",
		Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`,
		Numerals: `0-9`},
	{Code3: "heb", Code2: "he", Name: "Hebrew",
		Alphabet: `א ב ג ד ה ו ז ח ט י כ ך ל מ ם נ ן ס ע פ ף צ ץ ק ר ש ת`,
		// NOTE: The "geresh" ( ׳ ) is used to denote a single-digit Hebrew numeral.
		// The "gershayim" ( ״ ) is used to indicate a multi-digit Hebrew numeral.
		Numerals: `0-9׳״`},
	{Code3: "her", Code2: "hz", Name: "Herero", Alphabet: ``, Numerals: ""},
	{Code3: "hil", Code2: "", Name: "Hiligaynon", Alphabet: ``, Numerals: ""},
	{Code3: "him", Code2: "", Name: "Himachali languages; Pahari languages", Alphabet: ``, Numerals: ""},
	{Code3: "hin", Code2: "hi", Name: "Hindi", Alphabet: ``, Numerals: ""},
	{Code3: "hit", Code2: "", Name: "Hittite", Alphabet: ``, Numerals: ""},
	{Code3: "hmn", Code2: "", Name: "Hmong; Mong", Alphabet: ``, Numerals: ""},
	{Code3: "hmo", Code2: "ho", Name: "Hiri Motu", Alphabet: ``, Numerals: ""},
	{Code3: "hrv", Code2: "hr", Name: "Croatian", Alphabet: ``, Numerals: ""},
	{Code3: "hsb", Code2: "", Name: "Upper Sorbian", Alphabet: ``, Numerals: ""},
	{Code3: "hun", Code2: "hu", Name: "Hungarian",
		Alphabet: `A Á B C D E É F G H I Í J K L M N O Ó Ö Ő P Q R S T U Ú Ü Ű V W X Y Z`,
		Numerals: `0-9`},
	{Code3: "hup", Code2: "", Name: "Hupa", Alphabet: ``, Numerals: ""},
	{Code3: "hye", Code2: "hy", Name: "Armenian", Alphabet: ``, Numerals: ""},
	{Code3: "iba", Code2: "", Name: "Iban", Alphabet: ``, Numerals: ""},
	{Code3: "ibo", Code2: "ig", Name: "Igbo", Alphabet: ``, Numerals: ""},
	{Code3: "ido", Code2: "io", Name: "Ido", Alphabet: ``, Numerals: ""},
	{Code3: "iii", Code2: "ii", Name: "Sichuan Yi, Nuosu", Alphabet: ``, Numerals: ""},
	{Code3: "ijo", Code2: "", Name: "Ijo languages", Alphabet: ``, Numerals: ""},
	{Code3: "iku", Code2: "iu", Name: "Inuktitut", Alphabet: ``, Numerals: ""},
	{Code3: "ile", Code2: "ie", Name: "Interlingue, Occidental", Alphabet: ``, Numerals: ""},
	{Code3: "ilo", Code2: "", Name: "Iloko", Alphabet: ``, Numerals: ""},
	{Code3: "ina", Code2: "ia", Name: "Interlingua (International Auxiliary Language Association)", Alphabet: ``, Numerals: ""},
	{Code3: "inc", Code2: "", Name: "Indic languages", Alphabet: ``, Numerals: ""},
	{Code3: "ind", Code2: "id", Name: "Indonesian", Alphabet: ``, Numerals: ""},
	{Code3: "ine", Code2: "", Name: "Indo-European languages", Alphabet: ``, Numerals: ""},
	{Code3: "inh", Code2: "", Name: "Ingush", Alphabet: ``, Numerals: ""},
	{Code3: "ipk", Code2: "ik", Name: "Inupiaq", Alphabet: ``, Numerals: ""},
	{Code3: "ira", Code2: "", Name: "Iranian languages", Alphabet: ``, Numerals: ""},
	{Code3: "iro", Code2: "", Name: "Iroquoian languages", Alphabet: ``, Numerals: ""},
	{Code3: "isl", Code2: "is", Name: "Icelandic",
		Alphabet: `A Á B D Ð E É F G H I Í J K L M N O Ó P R S T U Ú V X Y Ý Þ Æ Ö`,
		Numerals: `0-9`},
	{Code3: "ita", Code2: "it", Name: "Italian",
		Alphabet: `A À B C D E È É F G H I Ì Í Î L M N O Ò Ó P Q R S T U Ù Ú V Z`,
		Numerals: `0-9`},
	{Code3: "jav", Code2: "jv", Name: "Javanese", Alphabet: ``, Numerals: ""},
	{Code3: "jbo", Code2: "", Name: "Lojban", Alphabet: ``, Numerals: ""},
	{Code3: "jpn", Code2: "ja", Name: "Japanese", Alphabet: ``, Numerals: ""},
	{Code3: "jpr", Code2: "", Name: "Judeo-Persian", Alphabet: ``, Numerals: ""},
	{Code3: "jrb", Code2: "", Name: "Judeo-Arabic", Alphabet: ``, Numerals: ""},
	{Code3: "kaa", Code2: "", Name: "Kara-Kalpak", Alphabet: ``, Numerals: ""},
	{Code3: "kab", Code2: "", Name: "Kabyle", Alphabet: ``, Numerals: ""},
	{Code3: "kac", Code2: "", Name: "Kachin; Jingpho", Alphabet: ``, Numerals: ""},
	{Code3: "kal", Code2: "kl", Name: "Kalaallisut, Greenlandic", Alphabet: ``, Numerals: ""},
	{Code3: "kam", Code2: "", Name: "Kamba", Alphabet: ``, Numerals: ""},
	{Code3: "kan", Code2: "kn", Name: "Kannada", Alphabet: ``, Numerals: ""},
	{Code3: "kar", Code2: "", Name: "Karen languages", Alphabet: ``, Numerals: ""},
	{Code3: "kas", Code2: "ks", Name: "Kashmiri", Alphabet: ``, Numerals: ""},
	{Code3: "kat", Code2: "ka", Name: "Georgian", Alphabet: ``, Numerals: ""},
	{Code3: "kau", Code2: "kr", Name: "Kanuri", Alphabet: ``, Numerals: ""},
	{Code3: "kaw", Code2: "", Name: "Kawi", Alphabet: ``, Numerals: ""},
	{Code3: "kaz", Code2: "kk", Name: "Kazakh", Alphabet: ``, Numerals: ""},
	{Code3: "kbd", Code2: "", Name: "Kabardian", Alphabet: ``, Numerals: ""},
	{Code3: "kha", Code2: "", Name: "Khasi", Alphabet: ``, Numerals: ""},
	{Code3: "khi", Code2: "", Name: "Khoisan languages", Alphabet: ``, Numerals: ""},
	{Code3: "khm", Code2: "km", Name: "Central Khmer", Alphabet: ``, Numerals: ""},
	{Code3: "kho", Code2: "", Name: "Khotanese; Sakan", Alphabet: ``, Numerals: ""},
	{Code3: "kik", Code2: "ki", Name: "Kikuyu, Gikuyu", Alphabet: ``, Numerals: ""},
	{Code3: "kin", Code2: "rw", Name: "Kinyarwanda", Alphabet: ``, Numerals: ""},
	{Code3: "kir", Code2: "ky", Name: "Kirghiz, Kyrgyz", Alphabet: ``, Numerals: ""},
	{Code3: "kmb", Code2: "", Name: "Kimbundu", Alphabet: ``, Numerals: ""},
	{Code3: "kok", Code2: "", Name: "Konkani", Alphabet: ``, Numerals: ""},
	{Code3: "kom", Code2: "kv", Name: "Komi", Alphabet: ``, Numerals: ""},
	{Code3: "kon", Code2: "kg", Name: "Kongo", Alphabet: ``, Numerals: ""},
	{Code3: "kor", Code2: "ko", Name: "Korean", Alphabet: ``, Numerals: ""},
	{Code3: "kos", Code2: "", Name: "Kosraean", Alphabet: ``, Numerals: ""},
	{Code3: "kpe", Code2: "", Name: "Kpelle", Alphabet: ``, Numerals: ""},
	{Code3: "krc", Code2: "", Name: "Karachay-Balkar", Alphabet: ``, Numerals: ""},
	{Code3: "krl", Code2: "", Name: "Karelian", Alphabet: ``, Numerals: ""},
	{Code3: "kro", Code2: "", Name: "Kru languages", Alphabet: ``, Numerals: ""},
	{Code3: "kru", Code2: "", Name: "Kurukh", Alphabet: ``, Numerals: ""},
	{Code3: "kua", Code2: "kj", Name: "Kuanyama, Kwanyama", Alphabet: ``, Numerals: ""},
	{Code3: "kum", Code2: "", Name: "Kumyk", Alphabet: ``, Numerals: ""},
	{Code3: "kur", Code2: "ku", Name: "Kurdish",
		Alphabet: `ئ ا ب پ ت ج چ ح خ د ر ڕ ز ژ س ش ع غ ف ڤ ق ک گ ل ڵ م ن ھ ە و ۆ ؤ ی ێ ڒ ڔ ڶ ڷ ۊ ٚ  `,
		Numerals: `٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩`},
	{Code3: "kut", Code2: "", Name: "Kutenai", Alphabet: ``, Numerals: ""},
	{Code3: "lad", Code2: "", Name: "Ladino", Alphabet: ``, Numerals: ""},
	{Code3: "lah", Code2: "", Name: "Lahnda", Alphabet: ``, Numerals: ""},
	{Code3: "lam", Code2: "", Name: "Lamba", Alphabet: ``, Numerals: ""},
	{Code3: "lao", Code2: "lo", Name: "Lao", Alphabet: ``, Numerals: ""},
	{Code3: "lat", Code2: "la", Name: "Latin", Alphabet: ``, Numerals: ""},
	{Code3: "lav", Code2: "lv", Name: "Latvian", Alphabet: ``, Numerals: ""},
	{Code3: "lez", Code2: "", Name: "Lezghian", Alphabet: ``, Numerals: ""},
	{Code3: "lim", Code2: "li", Name: "Limburgan, Limburger, Limburgish", Alphabet: ``, Numerals: ""},
	{Code3: "lin", Code2: "ln", Name: "Lingala", Alphabet: ``, Numerals: ""},
	{Code3: "lit", Code2: "lt", Name: "Lithuanian", Alphabet: ``, Numerals: ""},
	{Code3: "lol", Code2: "", Name: "Mongo", Alphabet: ``, Numerals: ""},
	{Code3: "loz", Code2: "", Name: "Lozi", Alphabet: ``, Numerals: ""},
	{Code3: "ltz", Code2: "lb", Name: "Luxembourgish, Letzeburgesch", Alphabet: ``, Numerals: ""},
	{Code3: "lua", Code2: "", Name: "Luba-Lulua", Alphabet: ``, Numerals: ""},
	{Code3: "lub", Code2: "lu", Name: "Luba-Katanga", Alphabet: ``, Numerals: ""},
	{Code3: "lug", Code2: "lg", Name: "Ganda", Alphabet: ``, Numerals: ""},
	{Code3: "lui", Code2: "", Name: "Luiseno", Alphabet: ``, Numerals: ""},
	{Code3: "lun", Code2: "", Name: "Lunda", Alphabet: ``, Numerals: ""},
	{Code3: "luo", Code2: "", Name: "Luo (Kenya and Tanzania)", Alphabet: ``, Numerals: ""},
	{Code3: "lus", Code2: "", Name: "Lushai", Alphabet: ``, Numerals: ""},
	{Code3: "mad", Code2: "", Name: "Madurese", Alphabet: ``, Numerals: ""},
	{Code3: "mag", Code2: "", Name: "Magahi", Alphabet: ``, Numerals: ""},
	{Code3: "mah", Code2: "mh", Name: "Marshallese", Alphabet: ``, Numerals: ""},
	{Code3: "mai", Code2: "", Name: "Maithili", Alphabet: ``, Numerals: ""},
	{Code3: "mak", Code2: "", Name: "Makasar", Alphabet: ``, Numerals: ""},
	{Code3: "mal", Code2: "ml", Name: "Malayalam", Alphabet: ``, Numerals: ""},
	{Code3: "man", Code2: "", Name: "Mandingo", Alphabet: ``, Numerals: ""},
	{Code3: "map", Code2: "", Name: "Austronesian languages", Alphabet: ``, Numerals: ""},
	{Code3: "mar", Code2: "mr", Name: "Marathi", Alphabet: ``, Numerals: ""},
	{Code3: "mas", Code2: "", Name: "Masai", Alphabet: ``, Numerals: ""},
	{Code3: "mdf", Code2: "", Name: "Moksha", Alphabet: ``, Numerals: ""},
	{Code3: "mdr", Code2: "", Name: "Mandar", Alphabet: ``, Numerals: ""},
	{Code3: "men", Code2: "", Name: "Mende", Alphabet: ``, Numerals: ""},
	{Code3: "mga", Code2: "", Name: "Irish, Middle (900–1200)", Alphabet: ``, Numerals: ""},
	{Code3: "mic", Code2: "", Name: "Mi'kmaq; Micmac", Alphabet: ``, Numerals: ""},
	{Code3: "min", Code2: "", Name: "Minangkabau", Alphabet: ``, Numerals: ""},
	{Code3: "mis", Code2: "", Name: "Uncoded languages", Alphabet: ``, Numerals: ""},
	{Code3: "mkd", Code2: "mk", Name: "Macedonian",
		Alphabet: `А Б В Г Д Ѓ Е Ж З Ѕ И Ј К Л Љ М Н Њ О П Р С Т Ќ У Ф Х Ц Ч Џ Ш`,
		Numerals: `0-9`},
	{Code3: "mkh", Code2: "", Name: "Mon-Khmer languages", Alphabet: ``, Numerals: ""},
	{Code3: "mlg", Code2: "mg", Name: "Malagasy", Alphabet: ``, Numerals: ""},
	{Code3: "mlt", Code2: "mt", Name: "Maltese", Alphabet: ``, Numerals: ""},
	{Code3: "mnc", Code2: "", Name: "Manchu", Alphabet: ``, Numerals: ""},
	{Code3: "mni", Code2: "", Name: "Manipuri", Alphabet: ``, Numerals: ""},
	{Code3: "mno", Code2: "", Name: "Manobo languages", Alphabet: ``, Numerals: ""},
	{Code3: "moh", Code2: "", Name: "Mohawk", Alphabet: ``, Numerals: ""},
	{Code3: "mon", Code2: "mn", Name: "Mongolian", Alphabet: ``, Numerals: ""},
	{Code3: "mos", Code2: "", Name: "Mossi", Alphabet: ``, Numerals: ""},
	{Code3: "mri", Code2: "mi", Name: "Maori", Alphabet: ``, Numerals: ""},
	{Code3: "msa", Code2: "ms", Name: "Malay", Alphabet: ``, Numerals: ""},
	{Code3: "mul", Code2: "", Name: "Multiple languages", Alphabet: ``, Numerals: ""},
	{Code3: "mun", Code2: "", Name: "Munda languages", Alphabet: ``, Numerals: ""},
	{Code3: "mus", Code2: "", Name: "Creek", Alphabet: ``, Numerals: ""},
	{Code3: "mwl", Code2: "", Name: "Mirandese", Alphabet: ``, Numerals: ""},
	{Code3: "mwr", Code2: "", Name: "Marwari", Alphabet: ``, Numerals: ""},
	{Code3: "mya", Code2: "my", Name: "Burmese", Alphabet: ``, Numerals: ""},
	{Code3: "myn", Code2: "", Name: "Mayan languages", Alphabet: ``, Numerals: ""},
	{Code3: "myv", Code2: "", Name: "Erzya", Alphabet: ``, Numerals: ""},
	{Code3: "nah", Code2: "", Name: "Nahuatl languages", Alphabet: ``, Numerals: ""},
	{Code3: "nai", Code2: "", Name: "North American Indian languages", Alphabet: ``, Numerals: ""},
	{Code3: "nap", Code2: "", Name: "Neapolitan", Alphabet: ``, Numerals: ""},
	{Code3: "nau", Code2: "na", Name: "Nauru", Alphabet: ``, Numerals: ""},
	{Code3: "nav", Code2: "nv", Name: "Navajo, Navaho", Alphabet: ``, Numerals: ""},
	{Code3: "nbl", Code2: "nr", Name: "South Ndebele", Alphabet: ``, Numerals: ""},
	{Code3: "nde", Code2: "nd", Name: "North Ndebele", Alphabet: ``, Numerals: ""},
	{Code3: "ndo", Code2: "ng", Name: "Ndonga", Alphabet: ``, Numerals: ""},
	{Code3: "nds", Code2: "", Name: "Low German; Low Saxon; German, Low; Saxon, Low", Alphabet: ``, Numerals: ""},
	{Code3: "nep", Code2: "ne", Name: "Nepali", Alphabet: ``, Numerals: ""},
	{Code3: "new", Code2: "", Name: "Nepal Bhasa; Newari", Alphabet: ``, Numerals: ""},
	{Code3: "nia", Code2: "", Name: "Nias", Alphabet: ``, Numerals: ""},
	{Code3: "nic", Code2: "", Name: "Niger-Kordofanian languages", Alphabet: ``, Numerals: ""},
	{Code3: "niu", Code2: "", Name: "Niuean", Alphabet: ``, Numerals: ""},
	{Code3: "nld", Code2: "nl", Name: "Dutch, Flemish",
		Alphabet: `A Á Ä B C D E É Ë F G H I Í Ï J J́ K L M N O Ó Ö P Q R S T U Ú Ü V W X Y Ý Z`,
		Numerals: `0-9`},
	{Code3: "nno", Code2: "nn", Name: "Norwegian Nynorsk",
		Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		Numerals: `0-9`},
	{Code3: "nob", Code2: "nb", Name: "Norwegian Bokmål",
		Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		Numerals: `0-9`},
	{Code3: "nog", Code2: "", Name: "Nogai", Alphabet: ``, Numerals: ""},
	{Code3: "non", Code2: "", Name: "Norse, Old", Alphabet: ``, Numerals: ""},
	{Code3: "nor", Code2: "no", Name: "Norwegian",
		Alphabet: `A Á Â Ā B C D E É È Ê Ē F G H I Í Ī J K L M N O Ó Ò Ô Ō P Q R S T U V W X Y Ý Z Æ Ø Å`,
		Numerals: `0-9`},
	{Code3: "nqo", Code2: "", Name: "N'Ko", Alphabet: ``, Numerals: ""},
	{Code3: "nso", Code2: "", Name: "Pedi; Sepedi; Northern Sotho", Alphabet: ``, Numerals: ""},
	{Code3: "nub", Code2: "", Name: "Nubian languages", Alphabet: ``, Numerals: ""},
	{Code3: "nwc", Code2: "", Name: "Classical Newari; Old Newari; Classical Nepal Bhasa", Alphabet: ``, Numerals: ""},
	{Code3: "nya", Code2: "ny", Name: "Chichewa, Chewa, Nyanja", Alphabet: ``, Numerals: ""},
	{Code3: "nym", Code2: "", Name: "Nyamwezi", Alphabet: ``, Numerals: ""},
	{Code3: "nyn", Code2: "", Name: "Nyankole", Alphabet: ``, Numerals: ""},
	{Code3: "nyo", Code2: "", Name: "Nyoro", Alphabet: ``, Numerals: ""},
	{Code3: "nzi", Code2: "", Name: "Nzima", Alphabet: ``, Numerals: ""},
	{Code3: "oci", Code2: "oc", Name: "Occitan", Alphabet: ``, Numerals: ""},
	{Code3: "oji", Code2: "oj", Name: "Ojibwa", Alphabet: ``, Numerals: ""},
	{Code3: "ori", Code2: "or", Name: "Oriya", Alphabet: ``, Numerals: ""},
	{Code3: "orm", Code2: "om", Name: "Oromo", Alphabet: ``, Numerals: ""},
	{Code3: "osa", Code2: "", Name: "Osage", Alphabet: ``, Numerals: ""},
	{Code3: "oss", Code2: "os", Name: "Ossetian, Ossetic", Alphabet: ``, Numerals: ""},
	{Code3: "ota", Code2: "", Name: "Turkish, Ottoman (1500–1928)", Alphabet: ``, Numerals: ""},
	{Code3: "oto", Code2: "", Name: "Otomian languages", Alphabet: ``, Numerals: ""},
	{Code3: "paa", Code2: "", Name: "Papuan languages", Alphabet: ``, Numerals: ""},
	{Code3: "pag", Code2: "", Name: "Pangasinan", Alphabet: ``, Numerals: ""},
	{Code3: "pal", Code2: "", Name: "Pahlavi", Alphabet: ``, Numerals: ""},
	{Code3: "pam", Code2: "", Name: "Pampanga; Kapampangan", Alphabet: ``, Numerals: ""},
	{Code3: "pan", Code2: "pa", Name: "Punjabi, Panjabi", Alphabet: ``, Numerals: ""},
	{Code3: "pap", Code2: "", Name: "Papiamento", Alphabet: ``, Numerals: ""},
	{Code3: "pau", Code2: "", Name: "Palauan", Alphabet: ``, Numerals: ""},
	{Code3: "peo", Code2: "", Name: "Persian, Old (ca. 600–400 B.C.)", Alphabet: ``, Numerals: ""},
	{Code3: "phi", Code2: "", Name: "Philippine languages", Alphabet: ``, Numerals: ""},
	{Code3: "phn", Code2: "", Name: "Phoenician", Alphabet: ``, Numerals: ""},
	{Code3: "pli", Code2: "pi", Name: "Pali", Alphabet: ``, Numerals: ""},
	{Code3: "pol", Code2: "pl", Name: "Polish",
		Alphabet: `A Ą B C Ć D E Ę F G H I J K L Ł M N Ń O Ó P Q R S Ś T U V W X Y Z Ź Ż`,
		Numerals: `0-9`},
	{Code3: "pon", Code2: "", Name: "Pohnpeian", Alphabet: ``, Numerals: ""},
	{Code3: "por", Code2: "pt", Name: "Portuguese",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á Â Ã À Ä Ç É Ê Ë Í Ï Ó Ô Õ Ú Ü`,
		Numerals: `0-9`},
	{Code3: "pra", Code2: "", Name: "Prakrit languages", Alphabet: ``, Numerals: ""},
	{Code3: "pro", Code2: "", Name: "Provençal, Old (to 1500); Old Occitan (to 1500)", Alphabet: ``, Numerals: ""},
	{Code3: "pus", Code2: "ps", Name: "Pashto, Pushto", Alphabet: ``, Numerals: ""},
	{Code3: "que", Code2: "qu", Name: "Quechua", Alphabet: ``, Numerals: ""},
	{Code3: "raj", Code2: "", Name: "Rajasthani", Alphabet: ``, Numerals: ""},
	{Code3: "rap", Code2: "", Name: "Rapanui", Alphabet: ``, Numerals: ""},
	{Code3: "rar", Code2: "", Name: "Rarotongan; Cook Islands Maori", Alphabet: ``, Numerals: ""},
	{Code3: "roa", Code2: "", Name: "Romance languages", Alphabet: ``, Numerals: ""},
	{Code3: "roh", Code2: "rm", Name: "Romansh", Alphabet: ``, Numerals: ""},
	{Code3: "rom", Code2: "", Name: "Romany", Alphabet: ``, Numerals: ""},
	{Code3: "ron", Code2: "ro", Name: "Romanian, Moldavian, Moldovan", Alphabet: ``, Numerals: ""},
	{Code3: "run", Code2: "rn", Name: "Rundi", Alphabet: ``, Numerals: ""},
	{Code3: "rup", Code2: "", Name: "Aromanian; Arumanian; Macedo-Romanian", Alphabet: ``, Numerals: ""},
	{Code3: "rus", Code2: "ru", Name: "Russian",
		Alphabet: `А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я`,
		Numerals: `0-9`},
	{Code3: "sad", Code2: "", Name: "Sandawe", Alphabet: ``, Numerals: ""},
	{Code3: "sag", Code2: "sg", Name: "Sango", Alphabet: ``, Numerals: ""},
	{Code3: "sah", Code2: "", Name: "Yakut", Alphabet: ``, Numerals: ""},
	{Code3: "sai", Code2: "", Name: "South American Indian languages", Alphabet: ``, Numerals: ""},
	{Code3: "sal", Code2: "", Name: "Salishan languages", Alphabet: ``, Numerals: ""},
	{Code3: "sam", Code2: "", Name: "Samaritan Aramaic", Alphabet: ``, Numerals: ""},
	{Code3: "san", Code2: "sa", Name: "Sanskrit", Alphabet: ``, Numerals: ""},
	{Code3: "sas", Code2: "", Name: "Sasak", Alphabet: ``, Numerals: ""},
	{Code3: "sat", Code2: "", Name: "Santali", Alphabet: ``, Numerals: ""},
	{Code3: "scn", Code2: "", Name: "Sicilian", Alphabet: ``, Numerals: ""},
	{Code3: "sco", Code2: "", Name: "Scots", Alphabet: ``, Numerals: ""},
	{Code3: "sel", Code2: "", Name: "Selkup", Alphabet: ``, Numerals: ""},
	{Code3: "sem", Code2: "", Name: "Semitic languages", Alphabet: ``, Numerals: ""},
	{Code3: "sga", Code2: "", Name: "Irish, Old (to 900)", Alphabet: ``, Numerals: ""},
	{Code3: "sgn", Code2: "", Name: "Sign Languages", Alphabet: ``, Numerals: ""},
	{Code3: "shn", Code2: "", Name: "Shan", Alphabet: ``, Numerals: ""},
	{Code3: "sid", Code2: "", Name: "Sidamo", Alphabet: ``, Numerals: ""},
	{Code3: "sin", Code2: "si", Name: "Sinhala, Sinhalese", Alphabet: ``, Numerals: ""},
	{Code3: "sio", Code2: "", Name: "Siouan languages", Alphabet: ``, Numerals: ""},
	{Code3: "sit", Code2: "", Name: "Sino-Tibetan languages", Alphabet: ``, Numerals: ""},
	{Code3: "sla", Code2: "", Name: "Slavic languages", Alphabet: ``, Numerals: ""},
	{Code3: "slk", Code2: "sk", Name: "Slovak",
		Alphabet: `A Á Ä B C Č D Ď E É F G H I Í J K L Ĺ Ľ M N Ň O Ó Ô P Q R Ŕ S Š T Ť U Ú V W X Y Ý Z Ž`,
		Numerals: `0-9`},
	{Code3: "slv", Code2: "sl", Name: "Slovenian",
		Alphabet: `A B C Č Ć D Đ E F G H I J K L M N O P R S Š T U V Z Ž`,
		Numerals: `0-9`},
	{Code3: "sma", Code2: "", Name: "Southern Sami", Alphabet: ``, Numerals: ""},
	{Code3: "sme", Code2: "se", Name: "Northern Sami", Alphabet: ``, Numerals: ""},
	{Code3: "smi", Code2: "", Name: "Sami languages", Alphabet: ``, Numerals: ""},
	{Code3: "smj", Code2: "", Name: "Lule Sami", Alphabet: ``, Numerals: ""},
	{Code3: "smn", Code2: "", Name: "Inari Sami", Alphabet: ``, Numerals: ""},
	{Code3: "smo", Code2: "sm", Name: "Samoan", Alphabet: ``, Numerals: ""},
	{Code3: "sms", Code2: "", Name: "Skolt Sami", Alphabet: ``, Numerals: ""},
	{Code3: "sna", Code2: "sn", Name: "Shona", Alphabet: ``, Numerals: ""},
	{Code3: "snd", Code2: "sd", Name: "Sindhi", Alphabet: ``, Numerals: ""},
	{Code3: "snk", Code2: "", Name: "Soninke", Alphabet: ``, Numerals: ""},
	{Code3: "sog", Code2: "", Name: "Sogdian", Alphabet: ``, Numerals: ""},
	{Code3: "som", Code2: "so", Name: "Somali", Alphabet: ``, Numerals: ""},
	{Code3: "son", Code2: "", Name: "Songhai languages", Alphabet: ``, Numerals: ""},
	{Code3: "sot", Code2: "st", Name: "Southern Sotho", Alphabet: ``, Numerals: ""},
	{Code3: "spa", Code2: "es", Name: "Spanish, Castilian",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ñ Ó Ú Ü`,
		Numerals: `0-9`},
	{Code3: "sqi", Code2: "sq", Name: "Albanian", Alphabet: ``, Numerals: ""},
	{Code3: "srd", Code2: "sc", Name: "Sardinian", Alphabet: ``, Numerals: ""},
	{Code3: "srn", Code2: "", Name: "Sranan Tongo", Alphabet: ``, Numerals: ""},
	{Code3: "srp", Code2: "sr", Name: "Serbian",
		Alphabet: `А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш`,
		Numerals: `0-9`},
	{Code3: "srr", Code2: "", Name: "Serer", Alphabet: ``, Numerals: ""},
	{Code3: "ssa", Code2: "", Name: "Nilo-Saharan languages", Alphabet: ``, Numerals: ""},
	{Code3: "ssw", Code2: "ss", Name: "Swati", Alphabet: ``, Numerals: ""},
	{Code3: "suk", Code2: "", Name: "Sukuma", Alphabet: ``, Numerals: ""},
	{Code3: "sun", Code2: "su", Name: "Sundanese", Alphabet: ``, Numerals: ""},
	{Code3: "sus", Code2: "", Name: "Susu", Alphabet: ``, Numerals: ""},
	{Code3: "sux", Code2: "", Name: "Sumerian", Alphabet: ``, Numerals: ""},
	{Code3: "swa", Code2: "sw", Name: "Swahili", Alphabet: ``, Numerals: ""},
	{Code3: "swe", Code2: "sv", Name: "Swedish",
		Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Å Ä Ö`,
		Numerals: `0-9`},
	{Code3: "syc", Code2: "", Name: "Classical Syriac", Alphabet: ``, Numerals: ""},
	{Code3: "syr", Code2: "", Name: "Syriac", Alphabet: ``, Numerals: ""},
	{Code3: "tah", Code2: "ty", Name: "Tahitian", Alphabet: ``, Numerals: ""},
	{Code3: "tai", Code2: "", Name: "Tai languages", Alphabet: ``, Numerals: ""},
	{Code3: "tam", Code2: "ta", Name: "Tamil", Alphabet: ``, Numerals: ""},
	{Code3: "tat", Code2: "tt", Name: "Tatar", Alphabet: ``, Numerals: ""},
	{Code3: "tel", Code2: "te", Name: "Telugu", Alphabet: ``, Numerals: ""},
	{Code3: "tem", Code2: "", Name: "Timne", Alphabet: ``, Numerals: ""},
	{Code3: "ter", Code2: "", Name: "Tereno", Alphabet: ``, Numerals: ""},
	{Code3: "tet", Code2: "", Name: "Tetum", Alphabet: ``, Numerals: ""},
	{Code3: "tgk", Code2: "tg", Name: "Tajik", Alphabet: ``, Numerals: ""},
	{Code3: "tgl", Code2: "tl", Name: "Tagalog", Alphabet: ``, Numerals: ""},
	{Code3: "tha", Code2: "th", Name: "Thai",
		Alphabet: `ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ
		ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ ฯ ะ ั า ำ  ิ  ี  ึ  ื  ุ  ู  ฺ เ แ โ ใ ๅ ไ  ็ ่ ้ ๊ ๋ ์ ํ ๎`,
		Numerals: `๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙`},
	{Code3: "tig", Code2: "", Name: "Tigre", Alphabet: ``, Numerals: ""},
	{Code3: "tir", Code2: "ti", Name: "Tigrinya", Alphabet: ``, Numerals: ""},
	{Code3: "tiv", Code2: "", Name: "Tiv", Alphabet: ``, Numerals: ""},
	{Code3: "tkl", Code2: "", Name: "Tokelau", Alphabet: ``, Numerals: ""},
	{Code3: "tlh", Code2: "", Name: "Klingon; tlhIngan-Hol", Alphabet: ``, Numerals: ""},
	{Code3: "tli", Code2: "", Name: "Tlingit", Alphabet: ``, Numerals: ""},
	{Code3: "tmh", Code2: "", Name: "Tamashek", Alphabet: ``, Numerals: ""},
	{Code3: "tog", Code2: "", Name: "Tonga (Nyasa)", Alphabet: ``, Numerals: ""},
	{Code3: "ton", Code2: "to", Name: "Tonga (Tonga Islands)", Alphabet: ``, Numerals: ""},
	{Code3: "tpi", Code2: "", Name: "Tok Pisin", Alphabet: ``, Numerals: ""},
	{Code3: "tsi", Code2: "", Name: "Tsimshian", Alphabet: ``, Numerals: ""},
	{Code3: "tsn", Code2: "tn", Name: "Tswana", Alphabet: ``, Numerals: ""},
	{Code3: "tso", Code2: "ts", Name: "Tsonga", Alphabet: ``, Numerals: ""},
	{Code3: "tuk", Code2: "tk", Name: "Turkmen", Alphabet: ``, Numerals: ""},
	{Code3: "tum", Code2: "", Name: "Tumbuka", Alphabet: ``, Numerals: ""},
	{Code3: "tup", Code2: "", Name: "Tupi languages", Alphabet: ``, Numerals: ""},
	{Code3: "tur", Code2: "tr", Name: "Turkish",
		Alphabet: `A Â B C Ç D E F G Ğ H I İ Î J K L M N O Ö P R S Ş T U Ü Û V Y Z Q W X ı`,
		Numerals: `0-9`},
	{Code3: "tut", Code2: "", Name: "Altaic languages", Alphabet: ``, Numerals: ""},
	{Code3: "tvl", Code2: "", Name: "Tuvalu", Alphabet: ``, Numerals: ""},
	{Code3: "twi", Code2: "tw", Name: "Twi", Alphabet: ``, Numerals: ""},
	{Code3: "tyv", Code2: "", Name: "Tuvinian", Alphabet: ``, Numerals: ""},
	{Code3: "udm", Code2: "", Name: "Udmurt", Alphabet: ``, Numerals: ""},
	{Code3: "uga", Code2: "", Name: "Ugaritic", Alphabet: ``, Numerals: ""},
	{Code3: "uig", Code2: "ug", Name: "Uighur, Uyghur", Alphabet: ``, Numerals: ""},
	{Code3: "ukr", Code2: "uk", Name: "Ukrainian",
		Alphabet: `А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ь Ю Я`,
		Numerals: `0-9`},
	{Code3: "umb", Code2: "", Name: "Umbundu", Alphabet: ``, Numerals: ""},
	{Code3: "und", Code2: "", Name: "Undetermined", Alphabet: ``, Numerals: ""},
	{Code3: "urd", Code2: "ur", Name: "Urdu", Alphabet: ``, Numerals: ""},
	{Code3: "uzb", Code2: "uz", Name: "Uzbek", Alphabet: ``, Numerals: ""},
	{Code3: "vai", Code2: "", Name: "Vai", Alphabet: ``, Numerals: ""},
	{Code3: "ven", Code2: "ve", Name: "Venda", Alphabet: ``, Numerals: ""},
	{Code3: "vie", Code2: "vi", Name: "Vietnamese",
		Alphabet: `A Ă Â À Ằ Ầ Ả Ẳ Ẩ Ã Ẵ Ẫ Á Ắ Ấ Ạ Ặ Ậ B C D Đ E Ê È Ề Ẻ Ể Ẽ
		Ễ É Ế Ẹ Ệ G H I Ì Ỉ Ĩ Í Ị K L M N O Ô Ơ Ò Ồ Ờ Ỏ Ổ Ở Õ Ỗ Ỡ Ó Ố Ớ
		Ọ Ộ Ợ P Q R S T U Ư Ù Ừ Ủ Ử Ũ Ữ Ú Ứ Ụ Ự V X Y Ỳ Ỷ Ỹ Ý Ỵ`,
		Numerals: `0-9`},
	{Code3: "vol", Code2: "vo", Name: "Volapük", Alphabet: ``, Numerals: ""},
	{Code3: "vot", Code2: "", Name: "Votic", Alphabet: ``, Numerals: ""},
	{Code3: "wak", Code2: "", Name: "Wakashan languages", Alphabet: ``, Numerals: ""},
	{Code3: "wal", Code2: "", Name: "Wolaitta; Wolaytta", Alphabet: ``, Numerals: ""},
	{Code3: "war", Code2: "", Name: "Waray", Alphabet: ``, Numerals: ""},
	{Code3: "was", Code2: "", Name: "Washo", Alphabet: ``, Numerals: ""},
	{Code3: "wen", Code2: "", Name: "sorbian languages",
		Alphabet: `A B C Č Ć D E Ě F G H I J K Ł L M N Ń O Ó P R Ř Ŕ S Š Ś T U W Y Z Ž Ź`,
		Numerals: `0-9`},
	{Code3: "wln", Code2: "wa", Name: "Walloon", Alphabet: ``, Numerals: ""},
	{Code3: "wol", Code2: "wo", Name: "Wolof", Alphabet: ``, Numerals: ""},
	{Code3: "xal", Code2: "", Name: "Kalmyk; Oirat", Alphabet: ``, Numerals: ""},
	{Code3: "xho", Code2: "xh", Name: "Xhosa", Alphabet: ``, Numerals: ""},
	{Code3: "yao", Code2: "", Name: "Yao", Alphabet: ``, Numerals: ""},
	{Code3: "yap", Code2: "", Name: "Yapese", Alphabet: ``, Numerals: ""},
	{Code3: "yid", Code2: "yi", Name: "Yiddish", Alphabet: ``, Numerals: ""},
	{Code3: "yor", Code2: "yo", Name: "Yoruba", Alphabet: ``, Numerals: ""},
	{Code3: "ypk", Code2: "", Name: "Yupik languages", Alphabet: ``, Numerals: ""},
	{Code3: "zap", Code2: "", Name: "Zapotec", Alphabet: ``, Numerals: ""},
	{Code3: "zbl", Code2: "", Name: "Blissymbols; Blissymbolics; Bliss", Alphabet: ``, Numerals: ""},
	{Code3: "zen", Code2: "", Name: "Zenaga", Alphabet: ``, Numerals: ""},
	{Code3: "zgh", Code2: "", Name: "Standard Moroccan Tamazight", Alphabet: ``, Numerals: ""},
	{Code3: "zha", Code2: "za", Name: "Zhuang, Chuang", Alphabet: ``, Numerals: ""},
	{Code3: "zho", Code2: "zh", Name: "Chinese", Alphabet: ``, Numerals: ""},
	{Code3: "znd", Code2: "", Name: "Zande languages", Alphabet: ``, Numerals: ""},
	{Code3: "zul", Code2: "zu", Name: "Zulu", Alphabet: ``, Numerals: ""},
	{Code3: "zun", Code2: "", Name: "Zuni", Alphabet: ``, Numerals: ""},
	{Code3: "zxx", Code2: "", Name: "No linguistic content; Not applicable", Alphabet: ``, Numerals: ""},
	{Code3: "zza", Code2: "", Name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", Alphabet: ``, Numerals: ""},
}
