// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"strings"
)

func (v *Validator) Validate() error {
	v.F1 = strings.TrimRight(v.F1, "abc")
	if v.F2 != nil {
		*v.F2 = strings.TrimRight(*v.F2, "xyz")
	}
	return nil
}
