// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.Email(v.User.Email) {
		return errors.New("User.Email must be a valid email address")
	}
	if v.User.Address != nil {
		if !valid.Zip(v.User.Address.Zip, "us") {
			return errors.New("User.Address.Zip must be a valid zip code")
		}
		if v.User.Address.Coords.Lat < -90 || v.User.Address.Coords.Lat > 90 {
			return errors.New("User.Address.Coords.Lat must be between: -90 and 90")
		}
		if v.User.Address.Coords.Long < -180 || v.User.Address.Coords.Long > 180 {
			return errors.New("User.Address.Coords.Long must be between: -180 and 180")
		}
	}
	return nil
}
