// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.Email(*v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if len(**v.F2) != 5 {
		return errors.New("F2 must be of length: 5")
	}
	return nil
}
