// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.Zip(v.F1, "us") {
		return errors.New("F1 must be a valid zip code")
	}
	if v.F2 != nil && !valid.Zip(*v.F2, "us") {
		return errors.New("F2 must be a valid zip code")
	}
	if !valid.Zip(v.F3, "gb") {
		return errors.New("F3 must be a valid zip code")
	}
	if v.F4 != nil && !valid.Zip(*v.F4, "ru") {
		return errors.New("F4 must be a valid zip code")
	}
	return nil
}
