// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.Decimal(v.F1, "en") {
		return errors.New("F1 string content must match a decimal number")
	}
	if v.F2 != nil && !valid.Decimal(*v.F2, "en") {
		return errors.New("F2 string content must match a decimal number")
	}
	if !valid.Decimal(v.F3, "bg") {
		return errors.New("F3 string content must match a decimal number")
	}
	if v.F4 != nil && !valid.Decimal(*v.F4, "hu") {
		return errors.New("F4 string content must match a decimal number")
	}
	return nil
}
