// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.HexColor(v.F1) {
		return errors.New("F1 must represent a valid hexadecimal color code")
	}
	if v.F2 != nil && !valid.HexColor(*v.F2) {
		return errors.New("F2 must represent a valid hexadecimal color code")
	}
	return nil
}
