// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"net/url"
)

func (v Validator) Validate() error {
	v.F1 = url.PathEscape(v.F1)
	if v.F2 != nil {
		*v.F2 = url.PathEscape(*v.F2)
	}
	return nil
}
