// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v Validator) Validate() error {
	if !valid.UUID(v.F1, 4) {
		return errors.New("F1 must be a valid UUID")
	}
	if v.F2 != nil && !valid.UUID(*v.F2, 4) {
		return errors.New("F2 must be a valid UUID")
	}
	if !valid.UUID(v.F3, 3) {
		return errors.New("F3 must be a valid UUID")
	}
	if !valid.UUID(v.F4, 4) {
		return errors.New("F4 must be a valid UUID")
	}
	if !valid.UUID(v.F5, 5) {
		return errors.New("F5 must be a valid UUID")
	}
	return nil
}
