// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"github.com/frk/valid/cmd/internal/generator/testdata/mypkg"
)

func (v T03Validator) Validate() error {
	ea := new(mypkg.ErrorList)

	if v.F1 == "" {
		ea.Error("F1", v.F1, "required")
	}
	if len(v.F2) == 0 {
		ea.Error("F2", v.F2, "required")
	} else if len(v.F2) > 9 {
		ea.Error("F2", v.F2, "len", "", 9)
	}
	return ea.Out()
}
