// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

func (v T04Validator) Validate() error {
	if v.F1 == "" {
		return v.ec.Error("F1", v.F1, "required")
	}
	if len(v.F2) == 0 {
		return v.ec.Error("F2", v.F2, "required")
	} else if len(v.F2) > 9 {
		return v.ec.Error("F2", v.F2, "len", "", 9)
	}
	return nil
}
