// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"strconv"
)

func (v *Validator) Validate() error {
	v.F1 = strconv.Quote(v.F1)
	if v.F2 != nil {
		*v.F2 = strconv.Quote(*v.F2)
	}
	return nil
}
