// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"net/url"
)

func (v *Validator) Validate() error {
	v.F1 = url.QueryEscape(v.F1)
	if v.F2 != nil {
		*v.F2 = url.QueryEscape(*v.F2)
	}
	return nil
}
