// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.In(v.F1, "foo", "bar", "baz") {
		return errors.New("F1 must be in the list")
	}
	if v.F2 != nil && !valid.In(*v.F2, 10, 20, 30, 40) {
		return errors.New("F2 must be in the list")
	}
	return nil
}
