// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
)

func (v T01Validator) Validate() error {
	if v.F1 == "" {
		return errors.New("F1 is required")
	}
	if len(v.F2) == 0 {
		return errors.New("F2 is required")
	}
	if len(v.F3) == 0 {
		return errors.New("F3 is required")
	}
	if v.F4 == 0 {
		return errors.New("F4 is required")
	}
	if v.F5 == 0 {
		return errors.New("F5 is required")
	}
	if v.F6 == 0.0 {
		return errors.New("F6 is required")
	}
	if v.F7 == false {
		return errors.New("F7 is required")
	}
	if v.F8 == nil {
		return errors.New("F8 is required")
	}
	if v.F9 == nil {
		return errors.New("F9 is required")
	}
	return nil
}
