// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
)

func (v T02Validator) Validate() error {
	if v.F1 == nil {
		return errors.New("F1 cannot be nil")
	}
	if v.F2 == nil {
		return errors.New("F2 cannot be nil")
	}
	if v.F3 == nil {
		return errors.New("F3 cannot be nil")
	}
	if v.F4 == nil {
		return errors.New("F4 cannot be nil")
	}
	if v.F5 == nil {
		return errors.New("F5 cannot be nil")
	}
	if v.F6 == nil {
		return errors.New("F6 cannot be nil")
	}
	return nil
}
