// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
)

func (v T16Validator) Validate() error {
	if v.F1 == "" {
		return errors.New("F1 is required")
	} else if !v.F1.IsValid() {
		return errors.New("F1 is not valid")
	}
	if v.F2 != nil && !v.F2.IsValid() {
		return errors.New("F2 is not valid")
	}
	if v.F3 != nil && *v.F3 != nil && !(**v.F3).IsValid() {
		return errors.New("F3 is not valid")
	}
	if v.F4 != nil && !(*v.F4).IsValid() {
		return errors.New("F4 is not valid")
	}
	return nil
}
