// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T23Validator) Validate() error {
	if !valid.Base64(v.F1, false) {
		return errors.New("F1 must be a valid base64 string")
	}
	if v.F2 != nil && *v.F2 != nil && !valid.Base64(**v.F2, true) {
		return errors.New("F2 must be a valid base64 string")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.Base64(**v.F3, false) {
		return errors.New("F3 must be a valid base64 string")
	}
	return nil
}
