// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T27Validator) Validate() error {
	if !valid.FQDN(v.F1) {
		return errors.New("F1 must be a valid FQDN")
	}
	if !valid.FQDN(v.F2) {
		return errors.New("F2 must be a valid FQDN")
	}
	if v.F3 != nil && !valid.FQDN(*v.F3) {
		return errors.New("F3 must be a valid FQDN")
	}
	if v.F4 != nil && !valid.FQDN(*v.F4) {
		return errors.New("F4 must be a valid FQDN")
	}
	if v.F5 != nil && !valid.FQDN(*v.F5) {
		return errors.New("F5 must be a valid FQDN")
	}
	return nil
}
