// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T29Validator) Validate() error {
	if !valid.HexColor(v.F1) {
		return errors.New("F1 must represent a valid hexadecimal color code")
	}
	if v.F2 != nil && *v.F2 != nil && !valid.HexColor(**v.F2) {
		return errors.New("F2 must represent a valid hexadecimal color code")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.HexColor(**v.F3) {
		return errors.New("F3 must represent a valid hexadecimal color code")
	}
	return nil
}
