// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T30Validator) Validate() error {
	if !valid.IP(v.F1, 0) {
		return errors.New("F1 must be a valid IP")
	}
	if v.F2 != nil && *v.F2 != nil && !valid.IP(**v.F2, 4) {
		return errors.New("F2 must be a valid IP")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.IP(**v.F3, 6) {
		return errors.New("F3 must be a valid IP")
	}
	return nil
}
