// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T37Validator) Validate() error {
	if !valid.UpperCase(v.F1) {
		return errors.New("F1 must contain only upper-case characters")
	}
	if v.F2 != nil && *v.F2 != nil && !valid.UpperCase(**v.F2) {
		return errors.New("F2 must contain only upper-case characters")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.UpperCase(**v.F3) {
		return errors.New("F3 must contain only upper-case characters")
	}
	return nil
}
