// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T39Validator) Validate() error {
	if !valid.UUID(v.F1, 4) {
		return errors.New("F1 must be a valid UUID")
	}
	if v.F2 != nil && *v.F2 != nil && !valid.UUID(**v.F2, 5) {
		return errors.New("F2 must be a valid UUID")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.UUID(**v.F3, 3) {
		return errors.New("F3 must be a valid UUID")
	}
	return nil
}
