// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

func (v T41Validator) Validate() error {
	if v.F1 == "" {
		return v.ec.Error("F1", v.F1, "required")
	} else if v.F1 != "foo" {
		return v.ec.Error("F1", v.F1, "eq", "foo")
	}
	return nil
}
