// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func init() {
	valid.RegisterRegexp(`foo`)
	valid.RegisterRegexp(`^[a-z]+\[[0-9]+\]$`)
	valid.RegisterRegexp(`\w+`)
}

func (v T44Validator) Validate() error {
	if !valid.Match(v.F1, `foo`) {
		return errors.New("F1 must match the regular expression: \"foo\"")
	}
	if v.F2 != nil && !valid.Match(*v.F2, `^[a-z]+\[[0-9]+\]$`) {
		return errors.New("F2 must match the regular expression: \"^[a-z]+\\\\[[0-9]+\\\\]$\"")
	}
	if v.F3 == nil || *v.F3 == nil || **v.F3 == "" {
		return errors.New("F3 is required")
	} else if !valid.Match(**v.F3, `\w+`) {
		return errors.New("F3 must match the regular expression: \"\\\\w+\"")
	}
	return nil
}
