// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
)

func (v T45aValidator) Validate() error {
	if err := v.beforevalidate(); err != nil {
		return err
	}
	if v.F1 == "" {
		return errors.New("F1 is required")
	}
	if err := v.AfterValidate(); err != nil {
		return err
	}
	return nil
}

func (v T45bValidator) Validate() error {
	if err := v.beforevalidate(); err != nil {
		return err
	}
	if v.F1 == "" {
		v.ea.Error("F1", v.F1, "required")
	}
	if err := v.ea.Out(); err != nil {
		return err
	}
	if err := v.AfterValidate(); err != nil {
		return err
	}
	return nil
}
