// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
	"strings"

	"github.com/frk/valid"
)

func (v T50Validator) Validate() error {
	if !valid.Email(v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if !valid.Hex(v.F2) {
		return errors.New("F2 must be a valid hexadecimal string")
	} else if len(v.F2) < 8 || len(v.F2) > 128 {
		return errors.New("F2 must be of length between: 8 and 128 (inclusive)")
	}
	if !strings.HasPrefix(v.F3, "foo") {
		return errors.New("F3 must be prefixed with: \"foo\"")
	} else if !strings.Contains(v.F3, "bar") {
		return errors.New("F3 must contain substring: \"bar\"")
	} else if !strings.HasSuffix(v.F3, "baz") && !strings.HasSuffix(v.F3, "quux") {
		return errors.New("F3 must be suffixed with: \"baz\" or \"quux\"")
	} else if len(v.F3) < 8 || len(v.F3) > 64 {
		return errors.New("F3 must be of length between: 8 and 64 (inclusive)")
	}
	return nil
}
