// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T51Validator) Validate() error {
	if len(v.F1) == 0 {
		return errors.New("F1 is required")
	} else {
		for _, e := range v.F1 {
			if !valid.Email(e) {
				return errors.New("F1 must be a valid email address")
			}
		}
	}
	if len(v.F2) < 1 {
		return errors.New("F2 must be of length at least: 1")
	} else {
		for _, e := range v.F2 {
			if !valid.Email(e) {
				return errors.New("F2 must be a valid email address")
			}
		}
	}
	return nil
}
