// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T53Validator) Validate() error {
	for _, e := range v.F1 {
		if !valid.Email(e) {
			return errors.New("F1 must be a valid email address")
		}
	}
	for k := range v.F2 {
		if !valid.Email(k) {
			return errors.New("F2 must be a valid email address")
		}
	}
	for k, e := range v.F3 {
		if !valid.Email(k) {
			return errors.New("F3 must be a valid email address")
		}
		if !valid.Phone(e, "us") {
			return errors.New("F3 must be a valid phone number")
		}
	}
	if v.F4 != nil && *v.F4 != nil && **v.F4 != nil {
		for k, e := range ***v.F4 {
			if k != nil && *k != nil && !valid.Phone(**k, "us") {
				return errors.New("F4 must be a valid phone number")
			}
			if e != nil && *e != nil && **e != nil && (***e < 18 || ***e > 64) {
				return errors.New("F4 must be between: 18 and 64")
			}
		}
	}
	return nil
}
