// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T54Validator) Validate() error {
	for _, e1 := range v.F5 {
		for k2, e2 := range e1 {
			if k2 != nil {
				for k3, e3 := range *k2 {
					if !valid.Email(k3) {
						return errors.New("F5 must be a valid email address")
					}
					if !valid.Phone(e3, "ca") {
						return errors.New("F5 must be a valid phone number")
					}
				}
			}
			if len(e2) > 10 {
				return errors.New("F5 must be of length at most: 10")
			} else {
				for _, e3 := range e2 {
					if e3 < -54 || e3 > 256 {
						return errors.New("F5 must be between: -54 and 256")
					}
				}
			}
		}
	}
	return nil
}
