// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T54Validator) Validate() error {
	for _, e := range v.F5 {
		for k, e2 := range e {
			if k != nil {
				for k, e := range *k {
					if !valid.Email(k) {
						return errors.New("F5 must be a valid email address")
					}
					if !valid.Phone(e, "ca") {
						return errors.New("F5 must be a valid phone number")
					}
				}
			}
			if len(e2) > 10 {
				return errors.New("F5 must be of length at most: 10")
			} else {
				for _, e := range e2 {
					if e < -54 || e > 256 {
						return errors.New("F5 must be between: -54 and 256")
					}
				}
			}
		}
	}
	return nil
}
