// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T61Validator) Validate() error {
	if v.F.F1 != nil && !valid.Email(*v.F.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if v.F2 == nil || *v.F2 == "" {
		return errors.New("F2 is required")
	}
	if v.F3 != nil && len(*v.F3) != 42 {
		return errors.New("F3 must be of length: 42")
	}
	if v.F4 == "" {
		return errors.New("F4 is required")
	}
	return nil
}
