// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v T62Validator) Validate() error {
	if v.F1 != nil && !valid.Email(*v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if v.F2 != nil {
		if *v.F2 < 8 {
			return errors.New("F2 must be greater than or equal to: 8")
		} else if *v.F2 > 128 {
			return errors.New("F2 must be less than or equal to: 128")
		}
	}
	return nil
}
