// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.LatLong(v.F1, false) {
		return errors.New("F1 must be a valid latitude-longitude coordinate")
	}
	if v.F2 != nil && !valid.LatLong(*v.F2, true) {
		return errors.New("F2 must be a valid latitude-longitude coordinate")
	}
	return nil
}
