// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
)

func (v *Validator) Validate() error {
	if v.F1 < 3.14 || v.F1 > 42 {
		return errors.New("F1 must be between: 3.14 and 42")
	}
	if v.F2 != nil && (*v.F2 < -8 || *v.F2 > 256) {
		return errors.New("F2 must be between: -8 and 256")
	}
	if v.F3 == nil || *v.F3 == 0 {
		return errors.New("F3 is required")
	} else if *v.F3 < 1 || *v.F3 > 2 {
		return errors.New("F3 must be between: 1 and 2")
	}
	return nil
}
