// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
)

func (v *Validator) Validate() error {
	if v.F1 > 3.14 {
		return errors.New("F1 must be less than or equal to: 3.14")
	}
	if v.F2 != nil && *v.F2 > 314 {
		return errors.New("F2 must be less than or equal to: 314")
	}
	if v.F3 == nil || *v.F3 == 0 {
		return errors.New("F3 is required")
	} else if *v.F3 > 31 {
		return errors.New("F3 must be less than or equal to: 31")
	}
	return nil
}
