// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"fmt"
)

func (v Validator) Validate() error {
	if v.F2 <= v.F1 {
		return fmt.Errorf("F2 must be greater than: %v", v.F1)
	}
	if v.S1.S2.F2 <= v.S1.S2.F1 {
		return fmt.Errorf("S1.S2.F2 must be greater than: %v", v.S1.S2.F1)
	}
	if v.S1.S3.F2 <= v.S1.S3.F1 {
		return fmt.Errorf("S1.S3.F2 must be greater than: %v", v.S1.S3.F1)
	}
	if v.S1.F1 <= v.S1.S2.F1 {
		return fmt.Errorf("S1.F1 must be greater than: %v", v.S1.S2.F1)
	}
	if v.S1.F2 <= v.S1.S3.F1 {
		return fmt.Errorf("S1.F2 must be greater than: %v", v.S1.S3.F1)
	}
	return nil
}
