// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"strings"
)

func (v *Validator) Validate() error {
	v.F1 = strings.TrimSuffix(v.F1, "foo")
	if v.F2 != nil {
		*v.F2 = strings.TrimSuffix(*v.F2, "bar")
	}
	return nil
}
