// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if !valid.Hash(v.F1, "md5") {
		return errors.New("F1 must be a valid hash")
	}
	if v.F2 != nil && !valid.Hash(*v.F2, "sha512") {
		return errors.New("F2 must be a valid hash")
	}
	return nil
}
