// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func (v *Validator) Validate() error {
	if v.F1 != "" && !valid.Email(v.F1) {
		return errors.New("F1 must be a valid email address")
	}
	if v.F2 != nil && *v.F2 > 0 && *v.F2 != 42 {
		return errors.New("F2 must be equal to: 42")
	}
	if v.F3 != nil && *v.F3 != nil && **v.F3 != "" {
		if len(**v.F3) > 24 {
			return errors.New("F3 must be of length at most: 24")
		} else if !valid.Alnum(**v.F3, "en") {
			return errors.New("F3 must be an alphanumeric string")
		}
	}
	return nil
}
