// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
)

func (v *Validator) Validate() error {
	if v.F1 == "foo" || v.F1 == "bar" {
		return errors.New("F1 must not be equal to: \"foo\" or \"bar\"")
	}
	if v.F2 != nil && (*v.F2 == 64 || *v.F2 == 128) {
		return errors.New("F2 must not be equal to: 64 or 128")
	}
	if v.F3 == "foo" || v.F3 == 0.8 || v.F3 == true {
		return errors.New("F3 must not be equal to: \"foo\" or 0.8 or true")
	}
	return nil
}
