// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
	"unicode/utf8"
)

func (v *Validator) Validate() error {
	if utf8.RuneCountInString(v.F1) != 8 {
		return errors.New("F1 must have rune count: 8")
	}
	if v.F2 != nil && (utf8.RuneCountInString(*v.F2) < 8 || utf8.RuneCountInString(*v.F2) > 16) {
		return errors.New("F2 must have rune count between: 8 and 16 (inclusive)")
	}
	if utf8.RuneCount(v.F3) < 8 {
		return errors.New("F3 must have rune count at least: 8")
	}
	if v.F4 != nil && utf8.RuneCount(*v.F4) > 16 {
		return errors.New("F4 must have rune count at most: 16")
	}
	return nil
}
