// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"

	"github.com/frk/valid"
)

func init() {
	valid.RegisterRegexp(`foo`)
	valid.RegisterRegexp(`\w+`)
	valid.RegisterRegexp(`^[a-z]+\[[0-9]+\]$`)
}

func (v Validator) Validate() error {
	if !valid.Match(v.F1, `foo`) {
		return errors.New("F1 must match the regular expression: \"foo\"")
	}
	if !valid.Match(v.F2, `\w+`) {
		return errors.New("F2 must match the regular expression: \"\\\\w+\"")
	}
	if v.F3 != nil && !valid.Match(*v.F3, `^[a-z]+\[[0-9]+\]$`) {
		return errors.New("F3 must match the regular expression: \"^[a-z]+\\\\[[0-9]+\\\\]$\"")
	}
	return nil
}
