// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

func (v *FooValidator) Validate() error {
	return nil
}

func (v *BarValidator) Validate() error {
	return nil
}

func (v *BazValidator) Validate() error {
	return nil
}
