// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
	"time"
)

func (v Validator) Validate() error {
	if v.F1 == "" {
		return errors.New("F1 is required")
	}
	if v.F2 == 0.0 {
		return errors.New("F2 is required")
	}
	if v.F3 == nil {
		return errors.New("F3 is required")
	}
	if v.F4 == (time.Time{}) {
		return errors.New("F4 is required")
	}
	if v.P1 == nil || *v.P1 == "" {
		return errors.New("P1 is required")
	}
	if v.P2 == nil || *v.P2 == nil || **v.P2 == 0.0 {
		return errors.New("P2 is required")
	}
	if v.P3 == nil || *v.P3 == nil {
		return errors.New("P3 is required")
	}
	if v.P4 == nil || *v.P4 == (time.Time{}) {
		return errors.New("P4 is required")
	}
	return nil
}
