// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"errors"
	"go/ast"
)

func (v *Validator) Validate() error {
	if v.F1 != foo && v.F1 != bar && v.F1 != baz {
		return errors.New("F1 must be one of")
	}
	if v.F2 != ast.Bad && v.F2 != ast.Pkg && v.F2 != ast.Con && v.F2 != ast.Typ && v.F2 != ast.Var && v.F2 != ast.Fun && v.F2 != ast.Lbl {
		return errors.New("F2 must be one of")
	}
	return nil
}
