// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"strings"
)

func (v Validator) Validate() error {
	v.F1 = strings.Repeat(v.F1, 2)
	if v.F2 != nil {
		*v.F2 = strings.Repeat(*v.F2, 5)
	}
	return nil
}
