// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package imports

import (
	"errors"

	"github.com/frk/valid/cmd/internal/generator/testdata/mypkg"
)

func (v T01Validator) Validate() error {
	if !is_foo(v.F1) {
		return errors.New("F1 is not valid")
	}
	if !isBar(v.f2) {
		return errors.New("f2 is not valid")
	}
	if !IsBaz(v.f3) {
		return errors.New("f3 is not valid")
	}
	if !mypkg.MyRule(v.F4) {
		return errors.New("F4 is not valid")
	}
	if !mypkg.MyRule2(v.f5) {
		return errors.New("f5 is not valid")
	}
	return nil
}
