// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"html"
)

func (v Validator) Validate() error {
	v.F1 = html.EscapeString(v.F1)
	if v.F2 != nil {
		*v.F2 = html.EscapeString(*v.F2)
	}
	return nil
}
