// DO NOT EDIT. This file was generated by "github.com/frk/valid".

package testdata

import (
	"errors"
)

func (v Validator) Validate() error {
	if len(v.F1) != 8 {
		return errors.New("F1 must be of length: 8")
	}
	if v.F2 != nil && (len(*v.F2) < 8 || len(*v.F2) > 16) {
		return errors.New("F2 must be of length between: 8 and 16 (inclusive)")
	}
	if len(v.F3) < 8 {
		return errors.New("F3 must be of length at least: 8")
	}
	if v.F4 != nil && (len(*v.F4) > 16) {
		return errors.New("F4 must be of length at most: 16")
	}
	return nil
}
