// Code generated by "github.com/frk/valid". DO NOT EDIT.

package testdata

import (
	"strings"
)

func (v *Validator) Validate() error {
	v.F1 = strings.ToValidUTF8(v.F1, "")
	if v.F2 != nil {
		*v.F2 = strings.ToValidUTF8(*v.F2, "")
	}
	return nil
}
